### ISSUE TITLE
[BUG] Account section disappears when app is idle with in-app browser web pages opened or closed

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#9662] opened 2024-05-17 00:28 UTC
**Description:** 
The account selection drop-down disappears at the top of the Wallet screen while web pages are open and the user toggles between the in-app browser and the Wallet screen. The issue also occurs when the app is idle and reopened without any web pages open. 

The glitch eventually resolves on its own toggling between screens.

**Expected behavior:** 
The accounts drop-down is always displayed at the top of the Wallet home screen page, allowing the user to switch between accounts. 

**Recordings**: 

https://github.com/MetaMask/metamask-mobile/assets/22276767/b4bf811a-a24a-41ea-bcf6-01dc5d96ab7d

https://github.com/MetaMask/metamask-mobile/assets/22276767/763b314a-a2c7-427f-a165-b9d690356471

**Comment by gantunesr** [comment] 2024-05-21 12:26
@sethkfman @SamuelSalas is this a new bug or is it already in prod?

**Comment by SamuelSalas** [comment] 2024-05-22 16:17
I have not being able to replicate this issue on prod v7.22. Compare with 7.23, which you just need to but the app on background to reproduce it.

**Comment by gantunesr** [comment] 2024-05-22 16:33
Thanks @SamuelSalas.

I'm still trying to pinpoint the culprit but the accounts team have not merged any PRs that could have caused this in this release. So far this seems like an issue introduced by another team.

**Comment by owencraston** [comment] 2024-05-22 17:28
@SamuelSalas the only pr that I could think of that interacted with this screen is [this one](https://github.com/MetaMask/metamask-mobile/pull/8664). This PR was merged and released in 7.18.0 which indicates to me that it is not the problem since you mentioned that you cannot reproduce on 7.22.

**Closed** 2024-05-23 19:21 UTC
Labels: type-bug, Sev1-high, team-accounts, regression-RC, INVALID-ISSUE-TEMPLATE, release-7.23.0, regression-RC-7.23.0
