### ISSUE TITLE
WalletConnect v2 implementation does not support Optional Namespaces.

### ISSUE THREAD

**Issue by jxom** [MetaMask/metamask-mobile#6703] opened 2023-06-25 22:04 UTC
**Describe the bug**

MetaMask Mobile's WalletConnect v2 implementation does not support Optional Namespaces, thus breaking multichain DApps - users cannot switch network. This was previously working in MM Mobile + WalletConnect v1.

**To Reproduce**

1. Head to https://stackblitz.com/edit/vitejs-vite-bhhzgv
2. Connect
3. Try switch to Polygon
4. Error.

**Expected behavior**

You are able to switch chains.

**Comment by 0xWhiteleaf** [comment] 2023-06-28 08:18
I would like to add more precision.
This bug is due to the fact that **Metamask ignores (or misshandle) the `optionalChains` parameter** and therefore does not include these chains in the "allowed" chains of the session.

This is resulting in an error when we try to request chain switch:
```json
error={ "message": "Chain 'eip155:137' not approved. Please use one of the following: eip155:1"}
```

How the connection is initiated client-side:
```js
await EthereumProvider.init({
  projectId: process.env.TEST_PROJECT_ID,
  chains: [1], // chains added to required namespaces
  optionalChains: [77, 99, 137] // chains added to optional namespaces
  ...
})
```

**Comment by iketw** [comment] 2023-07-24 22:05
Any updates on this?

**Comment by mohandesjiri** [comment] 2023-07-31 10:33
Any update?
Too many dApps are already broken.

**Comment by mccabe-david** [comment] 2023-12-07 22:22
I'm still having issues with this. It seems MetaMask is indifferent whether Optional Namespaces are sent in the Proposal Namespace. Further, when the Required Namespace "chains" array length is greater than 1, MetaMask won't even connect...

**Comment by mccabe-david** [comment] 2023-12-07 22:26
Am I crazy or does setting chains undefined when the array length is not 1 make no sense? Like at least fall back on defaultChain if it exists. https://github.com/ElvisKrop/wagmi-dev-references/blob/020fc97e276e8d7fbbb918e840029593fa05e7e9/packages/connectors/src/walletConnect.ts#L304

**Comment by mthinh** [comment] 2023-12-19 09:05
Im also facing this issue

**Comment by siosio34** [comment] 2024-02-16 03:57
Any updates on this?

**Comment by microHoffman** [comment] 2024-05-29 13:37
I believe this is closed by accident, the issue is still present @gauthierpetetin

**Comment by gauthierpetetin** [comment] 2024-05-29 13:39
Thanks for flagging @microHoffman , I'll re-open it.

**Closed** 2024-09-04 21:20 UTC
Labels: type-bug, team-sdk, Sev2-normal, WalletConnect
