### ISSUE TITLE
Cannot login…

### ISSUE THREAD

**Issue by yukestar0210** [MetaMask/metamask-mobile#2989] opened 2021-08-09 06:07 UTC
MM suddenly says Error: cannot unlock without a previous vault.

what should I do for this??

![Uploading 34FE1684-D4C3-40EF-8431-7D2273EFAD7C.png…]()

**Comment by alvarenmeta** [comment] 2021-08-10 00:51
have samme issue and i think i dont have, 1 oaccount phrase, what can i do??

**Comment by alvarenmeta** [comment] 2021-08-10 00:52
mi cel is an iphone x

**Comment by alvarenmeta** [comment] 2021-08-10 00:53
i can not use my phrase because i lost 1 account there

**Comment by omnat** [comment] 2021-08-17 17:37
@yukestar0210 @alvarenmeta Can you share reproduction steps for this issue please?

**Comment by gantunesr** [comment] 2022-01-21 15:07
I'm going to close this issue for now. Please open a new one if the error persist.

**Closed by gantunesr** 2022-01-21 15:07 UTC
Labels: bug, needs-reproduction, needs-information, storage limit, community
