### ISSUE TITLE
[Bug]: Error: JSON Parse error: Unexpected token: o

### ISSUE THREAD

**Issue by DevDecayed** [MetaMask/metamask-mobile#8996] opened 2024-03-19 18:26 UTC
### Describe the bug

![image](https://github.com/MetaMask/metamask-mobile/assets/160261330/1ed59cde-e618-439f-9202-7d2ba5c064b0)
![image](https://github.com/MetaMask/metamask-mobile/assets/160261330/2ac0bb6b-8670-4f4c-add2-e2ebe9003a66)

Correct password is throwing Json parsing error instead of letting use the app. Incorrect password is correctly throwing the "Invalid password" validation error. 

### Expected behavior

Correct password should allow me to use the application. 

### Steps to reproduce

1. Historically use bio-metrics to login
2. Bio metrics was unresponsive. No error thrown, but also not logging in. 
3. Toggle bio metrics to false/off on the login screen 
4. Bio metrics toggle disappears 
5. input correct password string 

Error: JSON Parse error: Unexpected token: o 
Is thrown. 

Correct "Invalid Password" error is thrown with any other string that isn't correct password. 

### Error messages or log output

```shell
Error: JSON Parse error: Unexpected token: o
```

### Version

7.17.1

### Build type

None

### Device

S21 Ultra 5G

### Operating system

Android

### Additional context

I had been using bio metrics to login to the application. The night it happened, I was trying to login but the bio metrics was un responsive. It seemed to be erroring out, but no error was thrown. I tried to use the biometrics a few times without success, so, I decided to toggle the option off (assuming the toggle would stay there and give me the option to toggle back on) so that I can turn it back on again (oldest trick in the book). Toggle to use bio metrics disappeared. So I tried to login with the correct string/password and got the Json Parse error.  Any other string correctly tosses the invalid password error. 
I've cleared cache with no success.  I have not seen any mention of this particular parse error. 

I don't know how to replicate it without another phone, that I do not have. 
Please help! I'm locked out of a ton of funds. 

![image](https://github.com/MetaMask/metamask-mobile/assets/160261330/ada858b6-8936-4ffd-97ad-d3ff1e703170)

### Severity

Critical. Doesn't allow user to get into metamask wallet. If user has lost seed phrase, there is no way of recovering access.

**Comment by DevDecayed** [comment] 2024-03-19 18:40
This has been going on since version 7.14.0. That is when the error first appeared.  I update the app as soon as updates are pushed, but so far, none have addressed the issue.

**Comment by Cal-L** [comment] 2024-04-10 16:42
@DevDecayed Thanks for reporting this. Just had a question to help us better debug this:
- Are you able to consistently reproduce this bug and if so, what is the version(s) where you're experiencing it and the exact steps to reproduce (specifically referring to the steps leading up to a non responsive biometrics)?

**Comment by gauthierpetetin** [comment] 2024-04-11 15:46
@MetaMask/mobile-platform  here are steps worth testing:

1. Install version 7.13.0
2. Do a custom import of a random token (@DevDecayed do you remember what tokens you had in the wallet?)
3. Upgrade to version 7.14.0

**Comment by gauthierpetetin** [comment] 2024-04-17 13:16
Thanks for this additional context @DevDecayed 🙏

**Comment by DevDecayed** [comment] 2024-04-17 13:30
@gauthierpetetin 
No, thank you for all your hard work!

**Comment by gauthierpetetin** [comment] 2024-04-18 15:39
@jpcloureiro managed to break the application state to reproduce the error we're seeing here.
Next steps suggested:
- Have Redux debugger working to be able to play with the Redux state
- Ensure this doesn't break the Bitrise build

**Comment by gauthierpetetin** [comment] 2024-05-02 16:41
Hi @DevDecayed by any chance, were you using a keystone hardware wallet before this issue occured?

**Comment by DevDecayed** [comment] 2024-05-03 12:29
@gauthierpetetin 
I was not using any hardware wallet. This was my mobile hot wallet. 
As for reproducible? I am still getting the error message for the correct password, the wrong passwords throw the "invalid password" error message.

**Comment by gauthierpetetin** [comment] 2024-05-21 14:13
This might be fixed by the PR that will remove vault recreation log in: https://github.com/MetaMask/metamask-mobile/pull/9577
It will be part of release 7.23.0

**Comment by DevDecayed** [comment] 2024-05-21 16:38
This is wonderful news. I've been following the progress like a hawk. I will be eagerly waiting for 7.23.0 and confirm once that goes live. 
Thank you all.

**Comment by DevDecayed** [comment] 2024-06-04 12:43
No go with 7.23.0. 
Error still present. Cache was cleared and tried.

**Comment by gauthierpetetin** [comment] 2024-06-04 12:45
cc @MetaMask/mobile-platform for visibility

**Comment by DevDecayed** [comment] 2024-06-04 13:59
I see there was something handled for 7.24.0. It was a copy of this with the word [Sentry] added to the front. 
Will wait patiently for that patch and confirm once it's live.

**Comment by Gudahtt** [comment] 2024-07-16 14:25
It sounds like this was a vault corruption error, but it wasn't caused by our vault corruption flow. If we are able to reproduce this even artificially, we should ensure that parse errors for the vault trigger the vault corruption flow.

**Comment by gauthierpetetin** [comment] 2024-07-16 16:15
Here's an issue we'll work on soon: https://github.com/MetaMask/MetaMask-planning/issues/2832

**Comment by gauthierpetetin** [comment] 2024-08-01 16:39
Closing this issue since we're not able to reproduce. We'll re-open if it occurs again.

We've also implemented this mitigation: https://github.com/MetaMask/metamask-mobile/pull/10481

**Closed by gauthierpetetin** 2024-08-01 16:39 UTC
Labels: type-bug, Sev1-high, in-progress, team-mobile-platform, external-contributor, regression-prod-7.17.1

**Comment by Nikiiis** [comment] 2024-08-05 16:03
I have exactly the same problem.. can you please tell me how you solved it?

> Văd că s-a rezolvat ceva pentru 7.24.0. Era o copie a acesteia cu cuvântul [Sentry] adăugat pe față. Va aștepta cu răbdare acel patch și va confirma odată ce este live.

**Comment by gauthierpetetin** [comment] 2024-08-18 18:11
Hi @Nikiiis , can you please upgrade the app to latest version (7.28.1), and let us know if you still encounter this error? If so, can you send us steps to reproduce?

**Comment by Nikiiis** [comment] 2024-08-18 18:32
My version is 7.27.1... in the Play Market, no update is available

dum., 18 aug. 2024, 21:11 Gauthier Petetin ***@***.***> a
scris:

**Comment by gauthierpetetin** [comment] 2024-08-18 20:59
Thanks for your reply, I'll let you know when the release is available on the Play Market such that you can retry.
