### ISSUE TITLE
BUSD BEP-20: Error transfer using metamask mobile only

### ISSUE THREAD

**Issue by 21sky** [MetaMask/metamask-mobile#2929] opened 2021-07-22 12:07 UTC
**Describe the bug**
Error when do **BEP-20** transaction( **BUSD** ) through **web3** or **ether.js** return ` Warning! Error encountered during contract execution [invalid opcode: opcode 0xa9 not defined] `
The contract also changed to contract creation

The issue only happen on **metamask mobile**, using the same script working on using **metamask browser extension**, and **other Wallets**.

**Screenshots**
Error shown when transfer **BUSD** using **metamask mobile**
![Screen Shot 2021-07-22 at 19 00 30](https://user-images.githubusercontent.com/78017960/126636234-3c1e68ad-93bc-4ee0-9371-b255231b64cc.png)

Successfull when transfer **BUSD** using **metamask browser extension**
![Screen Shot 2021-07-22 at 18 58 18](https://user-images.githubusercontent.com/78017960/126636197-78d89ba9-8906-45fb-bd0a-48f47bdba23d.png)

Different contract outcome when using **metamask mobile** and **metamask browser extension** with the same script
![Screen Shot 2021-07-22 at 19 01 54](https://user-images.githubusercontent.com/78017960/126636264-2b2eeb57-4063-4eb7-932e-d01a3a527547.png)

**Transfer Code Web3**
```
      await window.ethereum.enable()
      const senderAddress = '{{sender_address}}'
      const receiverAddress = '{{receiver_address}}'
      const busdAddress = '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56'
      const trfAmount = '0.001'

      const web3 = new Web3(window.ethereum)
      const contract = new web3.eth.Contract(bscContract.abi, busdAddress)

      contract.methods
        .transfer(receiverAddress, web3.utils.toWei(trfAmount, 'ether'))
        .send({ from: senderAddress })
        .then((res) => {
          console.log(res)
        })
        .catch((err) => {
          console.log(err)
        })
```

**To Reproduce**
1. Do transfer **BUSD** using **web3** or **ether.js** and run on **metamask mobile**
2. Find the transaction on [BSCScan](https://bscscan.com/)
3. See error

**Expected behavior**
Sucessfull **BUSD** transfer when using **metamask mobile**

**Smartphone:**
 - Device: Pocophone F1
 - OS: MIUI Global 12.0.3
 - App Version: v2.5.0

**Comment by frengkys** [comment] 2021-07-22 23:50
I have the same issue, metamask mobile return invalid opcode when do transfer

**Comment by inubaran** [comment] 2021-07-25 05:17
Same issue encountered on ios. Code works on metamask PC and Android but same error here when on ios (within metamask dapp browser). Walletconnect in metamask also stopped working for me after the upgrade to v2.6.0.

**Comment by apavlov812** [comment] 2021-07-25 17:51
I have the same issue, on Ios 14.7

**Comment by shikhars371** [comment] 2021-07-26 07:39
same problem

**Comment by aallamaa** [comment] 2021-07-26 12:06
same issue with ERC20

**Comment by andrekat** [comment] 2021-08-14 22:05
same issue .. did anyone find a solution for this yet?

**Comment by 21sky** [comment] 2021-08-16 03:48
> same issue .. did anyone find a solution for this yet?
> 
> #3022

not yet, havent found alternative way.
so im waiting for metamask side to fix this issue.

**Comment by terry108** [comment] 2021-08-16 07:51
same problem, transfer works on metamask PC

**Comment by andrepimenta** [comment] 2021-08-17 16:49
Duplicate of #2744

**Closed by andrepimenta** 2021-08-17 16:49 UTC
Labels: bug, custom network, community

**Comment by marbs99** [comment] 2022-01-30 17:56
please a complete code. Thanks alot
