### ISSUE TITLE
Error: Cannot fetch an chain id [ios]

### ISSUE THREAD

**Issue by ppenter** [MetaMask/metamask-mobile#2754] opened 2021-06-07 14:05 UTC
**Describe the bug**
When add a custom RPC network in ios metamask. it returned **cannot fetch chaion id . Is your RPC URL correct?**. But in chrome is works properly.

**Screenshots**
(Chrome extension)
![image](https://user-images.githubusercontent.com/55227490/121030370-51bdfe00-c7a1-11eb-8d54-485247ea5d32.png)

(iOS app)
![image](https://user-images.githubusercontent.com/55227490/121030660-95b10300-c7a1-11eb-9f7b-94cc7b5fcc34.png)

**The URL are the same.

**Smartphone (please complete the following information):**
 - Device: iPhone xs max
 - OS: [e.g. iOS14.6]
 - App Version 2.4.0

**Comment by gantunesr** [comment] 2022-02-23 00:39
Dupe of #2754

**Closed by gantunesr** 2022-02-23 00:39 UTC
Labels: bug, community
