### ISSUE TITLE
[Bug]: Attempts to send a transaction occasionally result in an error stating 'Cannot read property chainId of undefined' 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#12389] opened 2024-11-22 03:07 UTC
### Describe the bug

Attempts to send a transaction occasionally result in an error stating `Cannot read property chainId of undefined` on Android device.
This error does not appear to be consistently triggered by specific actions but still can be easily reproduced, present on all Popular networks

I have seen this error in the develop on iOS as well but in RC can't reproduce it https://github.com/MetaMask/metamask-mobile/pull/12321#issuecomment-2486016571

### Expected behavior

- 

### Screenshots/Recordings

https://github.com/user-attachments/assets/8bc72682-d27f-4fd9-a0e1-26da7fb61186

### Steps to reproduce

1. Start a transaction on any network

### Detection stage

During release testing

### Version

7.36.0 (1501)

### Build type

None

### Device

Samsung S24+, iPhone 15

### Operating system

iOS, Android

**Comment by Unik0rnMaggie** [comment] 2024-11-24 10:50
Unable to reproduce on RC build 7.36.0 on device Pixel 6 Pro, OS: Android 14.

I obtained the build from [here](https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/7e0c5081d3c5e128/public-install-page/2bc791b8c282341bfcc0ada2f3b55638) 


https://github.com/user-attachments/assets/5da24ad7-364f-40c1-8cbb-d9ed32bae50e

**Comment by sleepytanya** [comment] 2024-11-26 01:11
Present in RC 7.36.0 (1503):




https://github.com/user-attachments/assets/a747d350-87e7-4c04-b995-0a21e3cf8d92

**Comment by OGPoyraz** [comment] 2024-12-10 09:10
@sleepytanya this should be fixed in https://github.com/MetaMask/metamask-mobile/pull/12273

I am pretty sure you were pushing the submit button quickly as before adding transaction to controller. So the PR above is fixing that issue with disabling button until transaction is added to controller. Could you check and let me know if this fix works?

**Comment by OGPoyraz** [comment] 2024-12-13 09:11
@sleepytanya closing this task but feel free to re-open and ping me if this occur again.

**Closed by OGPoyraz** 2024-12-13 09:11 UTC
Labels: type-bug, android, Sev1-high, team-confirmations, regression-RC-7.36.0
