### ISSUE TITLE
[Bug]: Tooltip won't close 

### ISSUE THREAD

**Issue by coreyjanssen** [MetaMask/metamask-mobile#10868] opened 2024-08-28 20:27 UTC
### Describe the bug

Send ETH -> When tapping on the amount for estimated gas fee, the speed options appear. I clicked the amount to edit priority, tapped Low, then the (i) icon beside the estimated time (Maybe in 1 minute). This brought a tooltip detailing what this means, but once the tooltip is opened, I cannot close it. It doesn't respond when I click the X or try to swipe away from it, so I must close MM and start all over again. 

### Expected behavior

I expected to be able to close a tooltip and continue my transaction. 

### Screenshots/Recordings

https://github.com/user-attachments/assets/696c0106-2b6d-4c6b-b12a-8c1af0592471

### Steps to reproduce

1. Go to "send ETH" and begin a transaction
2. Once on the Estimated changes/estimated gas fee screen, tap the blue-underlined amount of the gas fee
3. Edit priority to Low, then tap the red info icon next to the speed estimate (Maybe in 1 minute is what it said on my screen)

### Detection stage

In production (default)

### Version

v7.28.1 (1386)

### Build type

None

### Device

iPhone 13 mini

### Operating system

iOS

**Comment by bschorchit** [comment] 2024-10-09 11:14
Closing as a duplicate of https://github.com/MetaMask/metamask-mobile/issues/10948 which has been fixed

**Closed by bschorchit** 2024-10-09 11:14 UTC
Labels: type-bug, Sev2-normal, team-confirmations, area-design
