### ISSUE TITLE
Unable to confirm seed phrase backup if a word repeats

### ISSUE THREAD

**Issue by mightypenguin** [MetaMask/metamask-mobile#1255] opened 2020-01-02 18:36 UTC
If the same word appears in your backup phrase twice you cannot confirm it.
Nag screen presents a usability issue on some websites since it hides on screen content.

**Comment by brunobar79** [comment] 2020-01-06 20:08
Duplicate of #552

**Closed by brunobar79** 2020-01-06 20:08 UTC
