### ISSUE TITLE
Error when trying to send transaction iOS

### ISSUE THREAD

**Issue by georgeandrei** [MetaMask/metamask-mobile#1230] opened 2019-11-27 09:19 UTC
I have problem with newest metamask on iOS, it shows undefined is not an object.
Steps to reproduce:
Try to send any transaction
![35958531-A3A1-4A74-82BA-F18DB30E0559](https://user-images.githubusercontent.com/45980656/69710020-359ac480-1107-11ea-84e5-c55c015db196.png)

**Comment by estebanmino** [comment] 2019-12-11 14:44
hi @georgeandrei is this still happening for you? Could you provide more information of how you got here? Thanks!

**Comment by georgeandrei** [comment] 2019-12-16 08:47
hi @estebanmino , I opened this for one of the metamask users. He gets this error when trying to perform a simple transaction of DAI tokens. hope this helps..

**Comment by brunobar79** [comment] 2020-01-07 19:47
This should be fixed with https://github.com/MetaMask/gaba/pull/186
Please reopen if the issue is still there

**Closed by brunobar79** 2020-01-07 19:47 UTC
