### ISSUE TITLE
provide Android apk

### ISSUE THREAD

**Issue by icepy** [MetaMask/metamask-mobile#2734] opened 2021-05-29 01:11 UTC
**Describe the usability problem**

i can't Android app installed. 

we can't use google service and google play in China. 

if u can provide Android apk and i think it's cool. 

**Screenshots**
_If applicable, add screenshots or links to help explain the issue_

**Expected behavior**

i can use Android apk install

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by rickycodes** [comment] 2021-11-15 17:14
closing because this a dupe of: https://github.com/MetaMask/metamask-mobile/issues/1066

**Closed by rickycodes** 2021-11-15 17:14 UTC
Labels: community
