### ISSUE TITLE
Receipt callback is not called on Android Metamask Browser

### ISSUE THREAD

**Issue by PowerRyder** [MetaMask/metamask-mobile#1723] opened 2020-07-27 03:44 UTC
When using web3.eth.sendTransaction, the transaction is mined but Reciept callback is called on Android Metamask Browser v0.2.19. On Pc it works fine.

**Comment by rickycodes** [comment] 2020-09-09 14:55
closing because this is a duplicate of #1469

**Closed by rickycodes** 2020-09-09 14:55 UTC
Labels: bug
