### ISSUE TITLE
Unable to speed up or cancel a transaction that has been submitted

### ISSUE THREAD

**Issue by JasoonS** [MetaMask/metamask-mobile#1746] opened 2020-08-04 10:37 UTC
**Describe the bug**
Unable to speed up or cancel a transaction on a non-primary account.

**Screenshots**
![metamask](https://user-images.githubusercontent.com/6032276/89284360-f423c700-d64e-11ea-9492-b09e442b25a6.jpg)
![metamask2](https://user-images.githubusercontent.com/6032276/89284388-00a81f80-d64f-11ea-884f-db5e7945e6ef.jpg)

**To Reproduce**
Create a transaction with low gas from a non primary account (maybe it is also a problem with the primary account).

**Expected behavior**
If I have lots of Eth (as in more than 0.5 eth after the transaction) I should be able to speed up or cancel my transactions.

**Smartphone (please complete the following information):**
 - Device: OnePlus 5t
 - OS: Android 10
 - Version 10

I tried putting funds into the primary account (to see if that was the bug but that didn't help). I eventually had to manually cancel the transaction using the private key.

**Comment by ibrahimtaveras00** [comment] 2020-08-04 17:07
Thanks for reporting @JasoonS 
This is a duplicate of https://github.com/MetaMask/metamask-mobile/issues/1626 which is fixed with https://github.com/MetaMask/metamask-mobile/pull/1684 and will be released this week

**Closed by ibrahimtaveras00** 2020-08-04 17:07 UTC
Labels: bug
