### ISSUE TITLE
[Bug]: `Approval request with id not found` when rejecting an Approve tx which has incorrect nonce

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7311] opened 2023-09-25 08:36 UTC
### Describe the bug

**Problem**: whenever I triggered an Approval request and tried to Confirm the approval I got a nonce error (nonce was 1 number below the expected). Then, when I rejected that Approval, the wallet broke with the error:

` Approval request with id not found`

After closing the error, even if I then tried to cancel the transaction or close the modal, the wallet didn't respond, until I close the app completely and re-opened it again.

### Expected behavior

- Nonce should be correctly handled (different issue)
- Nonce should be able to be changed in the Approve tx, if the settings is enabled (different issue)
- In case the above doesn't happen, the wallet should still not break and allow you to Reject the transaction

### Screenshots

![Screenshot from 2023-09-25 10-13-02](https://github.com/MetaMask/metamask-mobile/assets/54408225/8466c650-3fd0-4b1c-a536-cb831d5bc682)

https://github.com/MetaMask/metamask-mobile/assets/54408225/616c6951-85b3-45c1-aa44-bcdb645ef0ff

### Steps to reproduce

1. Go to the test dapp
2. Trigger a Send ETH legacy transaction (with params below, in order to not be confirmed right after)
3. Deploy the ERC20 contract
4. Speed up the Send ETH legacy transaction
5. After confirmed click Approve
6. Try to submit the tx
7. See nonce error
8. Try to reject the tx
9. See MM breaks

```
sendButton.onclick = async () => {
      const result = await ethereum.request({
        method: 'eth_sendTransaction',
        params: [
          {
            from: accounts[0],
            to: '0x0c54FcCd2e384b4BB6f2E405Bf5Cbc15a017AaFb',
            value: '0x0',
            gasLimit: '0x5028',
            gasPrice: '0x2540be400',
            type: '0x0',
          },
        ],
      });
      console.log(result);
    };
```

### Version

develop 0afaaa87e048e3f0b963b67d5744caa2bf76b8d8

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by OGPoyraz** [comment] 2024-01-11 09:06
Hey @seaona @sleepytanya 
I couldn't reproduce the exact steps mentioned above, but as far as I understood the case is, while user is approving transaction on the approval modal, if another transaction is getting confirmed then there is a nonce mismatch error.

Back in the time when we created this bug report, there was shown a nonce error in the screen. I don't know who made the change. But currently if there is a transaction error after clicking "approve" button (See the video I attached, it's a nonce error), there is a new modal pop up and the approval immediately deleted from the screen and disappeared already. 

https://github.com/MetaMask/metamask-mobile/assets/7644512/2ae007d1-48f0-41ca-9d4f-f6f3eb1bb2fb

Please correct me if I am wrong but meaning that this issue already resolved.

**Comment by sleepytanya** [comment] 2024-01-12 05:23
I don't get an error on iOS test build (`main`):

https://github.com/MetaMask/metamask-mobile/assets/104780023/f4e482a9-e857-4a86-98d5-377349b31bd8

**Comment by sleepytanya** [comment] 2024-01-12 05:41
Real Android device - Samsung Galaxy Note 20, MetaMask v7.12.3 (1230):
After performing all the steps to reproduce I get an error 'nonce too low' for 'Approve' transaction.  I'm able to reject the transaction but any subsequent transaction get the same 'nonce too low' error.

https://github.com/MetaMask/metamask-mobile/assets/104780023/132d00b1-7543-43d8-9798-f5284d42cfe3

Calculated nonces for the transactions do not match the order in which transactions were created (1 - Legacy tx, 2 - Create token, 3 - Approve).
Legacy transaction - nonce 31:
![Screenshot_20240111_171305_MetaMask](https://github.com/MetaMask/metamask-mobile/assets/104780023/e78c83f8-6e5f-4743-a8b8-1c96dbadbf42)

Contract deployment - nonce 30:

![Screenshot_20240111_171258_MetaMask](https://github.com/MetaMask/metamask-mobile/assets/104780023/9b7c97fc-1df5-4f1c-9930-a8cbcf166530)

You can also see on the video that Contract deployment transaction is created with nonce 32, but on Activity tab it's nonce is 30.
<img width="481" alt="Screenshot 2024-01-12 at 12 38 03 AM" src="https://github.com/MetaMask/metamask-mobile/assets/104780023/b36ebf61-f816-475d-9bca-bbb69c1e6d1b">


State logs: 
[309048789655022.txt](https://github.com/MetaMask/metamask-mobile/files/13915042/309048789655022.txt)

**Comment by OGPoyraz** [comment] 2024-01-12 09:44
> After performing all the steps to reproduce I get an error 'nonce too low' for 'Approve' transaction. I'm able to reject the transaction but any subsequent transaction get the same 'nonce too low' error.
@sleepytanya exactly, I think this is different issue as it mentioned in the "Expected behaviour" section. Since app is not broken anymore and we don't see `Approval request with id not found` error, I will close this and open another for nonce mismatch error.

**Closed by OGPoyraz** 2024-01-12 09:44 UTC
Labels: type-bug, Sev2-normal, team-confirmations-system
