### ISSUE TITLE
Missing token address crasher when removing token

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3136] opened 2021-09-16 18:36 UTC
### **Description**

There was a new bug introduced in v3.3.0 where the app would crash when removing a token from the wallet. The bug is most likely a result of a missing address on a token.

### **Technical Details**

- TBD

### **Acceptance Criteria**

- Adding and removing tokens should still work

### **References**

- Sentry issue - https://sentry.io/organizations/metamask/issues/2651258350/?project=2299799&query[…]ed+release%3Aio.metamask%403.3.0%2B777&sort=freq&statsPeriod=14d

**Comment by gantunesr** [comment] 2022-03-21 22:33
I can't reproduce this crash. Closing this issue for the moment

**Closed by gantunesr** 2022-03-21 22:33 UTC
Labels: bug, technical research
