### ISSUE TITLE
"Next" buttons and buttons on browser become unresponsive, unpressable. (critical result - unable to send funds)

### ISSUE THREAD

**Issue by eddfr** [MetaMask/metamask-mobile#2679] opened 2021-05-13 08:01 UTC
This may be related to the bug where the "transaction submitted" notification becomes stuck.

Metamask Mobile suddenly does not respond when buttons are pressed, even when restarted or phone is rebooted, and even after the update to the newest version (2.20)

DEVICE: Vivo phone
 - OS: Vivo Rev 1.58.25 (Funtouch OS)
 - App Version 2.20

Severity: Assets unable to be sent.

**Comment by gantunesr** [comment] 2022-01-24 15:10
Hey @eddfr, is this still happening to you? If so, can you provide steps to reproduce it?

**Comment by gantunesr** [comment] 2022-01-25 14:53
Dupe of #2704

**Closed by gantunesr** 2022-01-25 14:53 UTC
Labels: bug, community
