### ISSUE TITLE
Metamask opens up but I can't connect to my dApp after that!

### ISSUE THREAD

**Issue by Risav03** [MetaMask/metamask-mobile#6376] opened 2023-05-12 10:45 UTC
### **Description**

I am developing a dApp using Rainbowkit and Wagmi for connecting wallet.

The Desktop version is working fine but when I open up my site from Chrome mobile I face a problem.

The Modal opens up, I choose Metamask and it redirects me to Metamask, but nothing happens after that, I recieve no pop-up to connect to the Dapp 

This is my dApp
https://beastversegame.com/wearemintingfortestpurposesonly

**Comment by duybuikardiachain** [comment] 2023-05-13 14:21
Same issue here, can't connect with DApps after upgrade to version 6.5.0
Working fine on 6.3.0

**Comment by Risav03** [comment] 2023-05-13 14:23
> Same issue here, can't connect with DApps after upgrade to version 6.5.0 Working fine on 6.3.0

For some reason it has started working for me now...
Try opening https://beastversegame.com/wearemintingfortestpurposesonly and connecting your wallet

**Comment by Samonnite** [comment] 2023-05-13 16:51
> > Same issue here, can't connect with DApps after upgrade to version 6.5.0 Working fine on 6.3.0
> 
> For some reason it has started working for me now... Try opening https://beastversegame.com/wearemintingfortestpurposesonly and connecting your wallet

How to resolve it?

**Comment by Risav03** [comment] 2023-05-13 16:55
I guess that's because I added Buffer to my dApp

Just install Buffer using npm or yarn and add this

global.Buffer = global.Buffer || require('buffer').Buffer

**Comment by anaamolnar** [comment] 2023-05-25 09:29
Hello @Risav03! Thanks for reporting! It seems the issue is solved. I will go ahead and close this issue. Feel free to open it again if that is not the case.

**Closed by anaamolnar** 2023-05-25 09:29 UTC
Labels: team-sdk

**Comment by anaamolnar** [comment] 2023-05-26 07:24
Hello, @idelburgo-iomob. Thanks for reporting! That sounds like a different issue. Would you mind creating another Github issue for it? Thank you!

**Comment by Risav03** [comment] 2023-05-26 07:59
> I have tried to connect through walletConnect to your app. And Metamask does not open up the modal to connect. Is your dApp operative with the fix you mentioned?

Yea it is perfectly working...through Google Chrome and metamask browser. I figured out it's better to let people access your site on mobile through a wallet's browser, even buyers prefer the same thing.
