### ISSUE TITLE
Pending confirmation banner blocks button.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#1467] opened 2020-04-02 03:07 UTC
![2723230A-5C37-4ED0-AD36-C416A09BCD32](https://user-images.githubusercontent.com/542863/78206691-62177200-7454-11ea-9cb2-02b7753ada3d.jpeg)

**Comment by danjm** [comment] 2020-04-02 11:45
Duplicate of https://github.com/MetaMask/metamask-mobile/issues/1414

**Comment by omnat** [comment] 2020-04-03 22:55
Closing as getting solved in #1414

**Closed by omnat** 2020-04-03 22:55 UTC
Labels: bug, duplicate
