### ISSUE TITLE
Browser Opens Multiple Tabs

### ISSUE THREAD

**Issue by leon-do** [MetaMask/metamask-mobile#3646] opened 2022-01-26 07:08 UTC
**Describe the bug**
_A clear and concise description of what the bug is_
Opening deep links with metamask mobile open multiple tabs.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_
https://user-images.githubusercontent.com/19412160/151118231-c70775e1-135e-4b1f-b2ed-d3cf561d0780.mp4

**To Reproduce**
_Steps to reproduce the behavior_
Please check video above

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android
 - App Version v3.8.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by atifbuttgss** [comment] 2022-01-26 07:12
Yes, I am facing this issue as well. and i thought it is on ChainSafe end but its on Meta Mask's end.

**Comment by gantunesr** [comment] 2022-01-26 13:34
Hey @leon-do,  thanks for reaching out, this is a dupe of #3525 and there's a fix in the PR #3570 which should be included in the following releases.

I'm closing this issue for the moment.

**Closed by gantunesr** 2022-01-26 13:34 UTC
Labels: bug
