### ISSUE TITLE
Browser: Not able to reconnect to uniswap with Android device

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#5290] opened 2022-11-22 23:53 UTC
**Describe the bug**
On android device when I connect wallet to uniswap.exchange for the first time, I then disconnect my wallet, and attempt to reconnect my wallet I do not get the option to connect with MetaMask anymore.  I tried closing and reopening app, clear browser history and data but still not able to select to connect with MetaMask.  Only way I have found to reconnect wallet to uniswap is to reinstall the app.  Haven't seen this with other DeFi like 1inch or pancakeswap.  Not an issue with iOS.  
https://recordit.co/b4KrvboZhi

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by blackdevelopa** [comment] 2022-11-23 13:14
Thanks @chrisleewilcox. I am unable to reproduce this on [iOS](http://recordit.co/m82khRLNmm). Suffice to say it's Android alone

**Comment by tommasini** [comment] 2022-12-20 18:13
Hey @chrisleewilcox we will close this since it's [duplicated](https://github.com/MetaMask/metamask-mobile/issues/5364) and it's under investigation

**Comment by chrisleewilcox** [comment] 2023-01-23 17:21
I would like issues written up by QA team to remain open until issues has been resolved.  If other issues are reported afterwards then we can mark those as duplicates but original issue reported should be driving the fix.

**Comment by chrisleewilcox** [comment] 2023-01-24 18:13
https://consensys.slack.com/archives/C017NBJL1S7/p1669841367454339

**Comment by hesterbruikman** [comment] 2023-04-27 09:04
Still able to reproduce:

OS: Android 11
Device: Samsung Galaxy S10e

Steps to reproduce
1. Open in-app browser
2. Navigate to app.uniswap.org via home.metamask.io
3. Connect wallet
4. Disconnect wallet
5. Revoke permissions
6. Open new tab
7. Navigate to app.uniswap.org via home.metamask.io
8. Tap Connect

**Comment by hesterbruikman** [comment] 2023-04-27 09:06
Also reported in #5364

**Comment by tommasini** [comment] 2023-07-13 22:27
Moved in to blocked
@hesterbruikman will reach out to uniswap to unblock

cc: @Cal-L

**Comment by ThalesBMC** [comment] 2023-08-16 17:02
any updates?

**Comment by infiniteflower** [comment] 2024-02-09 17:01
You can fix it for just one time by wiping the app storage. But once you go back to Uniswap webpage the issue resurfaces.

**Comment by spam0115** [comment] 2024-02-14 18:30
> You can fix it for just a single time by wiping the app storage, no reinstall needed. But after you successfully connect once, if you reload the Uniswap webpage the issue resurfaces.

If I wipe app storage, won't that erase my wallets?  I ran into this problem last night.  I'm using Trustwallet on android.

**Comment by jpcloureiro** [comment] 2024-07-03 15:23
Fixed with #7759

**Comment by jpcloureiro** [comment] 2024-07-03 15:37
Closing after production release

**Comment by jpcloureiro** [comment] 2024-07-04 10:08
To be shipped on next release

**Closed by jpcloureiro** 2024-07-04 10:08 UTC
Labels: type-bug, browser, android, Sev2-normal, technical research, team-mobile-platform
