### ISSUE TITLE
v0.2.18(455) the navigation bar appears in the middle of the screen

### ISSUE THREAD

**Issue by zhangzhongnan928** [MetaMask/metamask-mobile#1642] opened 2020-06-17 23:22 UTC
**Describe the bug**
the navigation bar appears in the middle of the screen

**Screenshots**
![IMG_3505](https://user-images.githubusercontent.com/33795543/84960441-f4bad980-b144-11ea-902a-8afb51d9357e.GIF)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: 13.5
 - Version v0.2.18(455)

**Comment by ibrahimtaveras00** [comment] 2020-06-17 23:39
sounds like a duplicate of https://github.com/MetaMask/metamask-mobile/issues/1630

**Closed by ibrahimtaveras00** 2020-06-17 23:39 UTC
Labels: bug
