### ISSUE TITLE
Isnt remembering session in specific site, keeps showing Twitter title after returning to previous site, Twitter isnt accepting Peepeth login unlike in desktip

### ISSUE THREAD

**Issue by DaniellMesquita** [MetaMask/metamask-mobile#1270] opened 2020-01-09 22:16 UTC
![Screenshot_20200109-191350](https://user-images.githubusercontent.com/6765277/72109416-b1567680-332d-11ea-81ab-cde5d10a26a0.png)
![Screenshot_20200109-191417](https://user-images.githubusercontent.com/6765277/72109420-b4516700-332d-11ea-97dd-fdd99f365631.png)

**Comment by brunobar79** [comment] 2020-01-21 23:48
This is a duplicate of #1244

**Closed by brunobar79** 2020-01-21 23:48 UTC
