### ISSUE TITLE
Deeplinks do not properly support ENS names

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1631] opened 2020-06-12 23:15 UTC
**Describe the bug**

If inputting an ENS name as the "TO" address in a deeplink, once navigating to Confirm view in app, there is a txn error.

**Screenshots**

Seen here = https://recordit.co/Jhko58hFfP

![Screen Shot 2020-06-12 at 7 11 28 PM](https://user-images.githubusercontent.com/41752922/84552957-89a27a80-ace0-11ea-8871-6429985b2584.png)

**To Reproduce**

1. Go to https://metamask.github.io/metamask-deeplinks website to create a deeplink (example = Payment Request > ETH Payment) 
2. Ensure target address is a valid ENS name
3. Open the deeplink on MM App
4. Tap Send button and txn error will pop up

**Expected behavior**

The ENS name should be recognized and user should be able to send txn without any error.

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Version any

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by AlexJupiter** [comment] 2022-04-27 12:26
I've added "needs-reproduction" since this is an old ticket, and if this still persists, we should fix this.

**Comment by sethkfman** [comment] 2023-07-11 21:12
Closed as issue was addressed #5758

**Closed by sethkfman** 2023-07-11 21:12 UTC
Labels: type-bug, needs-reproduction, Sev3-low, Priority - Medium, team-mobile-client
