### ISSUE TITLE
MetaMask: 'eth_accounts' unexpectedly updated accounts

### ISSUE THREAD

**Issue by xmaysonnave** [MetaMask/metamask-mobile#1675] opened 2020-07-07 09:19 UTC
Metamask Mobile v0.2.19 (32)

**Describe the bug**

Unable to receive the selected eth_accounts once the user confirmed the current account on Metamask Mobile.

I started to remote debug the app and got the following exception :

`MetaMask: 'eth_accounts' unexpectedly updated accounts. Please report this bug.`

This app is working with Metamask extension on Chrome an used to work with Metamask Mobile.

Here the logic implemented :

```
      // https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md
      await provider.request({ method: 'eth_requestAccounts' })
      // https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md
      accounts = await provider.request({ method: 'eth_accounts' })
      if (
        accounts === undefined ||
        accounts == null ||
        Array.isArray(accounts) === false ||
        accounts.length === 0
      ) {
        throw new Error('Unable to retrieve any Ethereum accounts...')
      }
```
The eth_requestAccounts triggers the UI. UX 'Connect to this site ?' Confirmed.
The eth_accounts generate the mentioned exception and the DApp receives an empty array.

**Expected behavior**
The eth_accounts call should send an array who contains the selected account.

**Smartphone (please complete the following information):**
 - Device: Redmi Note 7 Pro
 - OS: MIUI 11
 - Version 11.0.9.0

Thanks

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by rickycodes** [comment] 2020-07-14 15:32
@xmaysonnave I can't seem to reproduce this and I am wondering if it's still an issue for you? It's true that `accounts = await ethereum.request({ method: 'eth_accounts' })` returns and empty array _if_ the user hasn't connected to the dapp, but it seems to work fine once I am connected?:

```
accounts = await ethereum.request({ method: 'eth_accounts' })
["0xc7d3bfd..."]
```

**Comment by xmaysonnave** [comment] 2020-07-15 04:26
@rickycodes Thanks for your feedback.
Here is to reproduce the error.
Clear your privacy data.
1 - await provider.request({method:'requestAccounts'})
The UI popup to connect the Dapp to the current account
2 - await provider.request({method:'eth_accounts'})
No errors, but return an empty array
3 - Once this problems occured I tested with an await provider.enable()
The UI popup a second time to connect the Dapp
No errors and enable returns a populated array.

**Comment by AlexJupiter** [comment] 2022-04-27 12:37
@xmaysonnave I'm going to close this issue since there hasn't been any update in a long time. If this issue still persists let us know and perhaps we can re-open.

**Closed by AlexJupiter** 2022-04-27 12:37 UTC
Labels: bug, community

**Comment by 340rahul** [comment] 2023-01-05 12:38
We're still facing this issue. Is there a workaround?
