### ISSUE TITLE
Android: JSON RPC error on opensea item

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1242] opened 2019-12-09 23:54 UTC
This happens on Android only. There are some listings on opensea that show an error "Invalid JSON RPC response" such as this one = https://opensea.io/assets/0x4d3814d4da8083b41861dec2f45b4840e8b72d68/5583 thus making the buy now/make offer cta's non-selectable

Seen here = http://recordit.co/lk1gnjaljX

![image](https://user-images.githubusercontent.com/41752922/70482984-304d5a80-1ab5-11ea-892d-f074490b60e7.png)

Also, when I do reload and have the option to tap either CTA, tapping it does nothing; = http://recordit.co/0tdDAQmA57

@omnat also had the same issue:

Steps to reproduce: 
1) Open MetaMask mobile on an Android device (not sure this issue affects all Android devices).
2) Navigate to https://opensea.io/account. 
3) Tap an NFT.
4) Tap Sell.
5) Tap Post You Listing

Expected behavior is that you’ll see something like this:

![image](https://user-images.githubusercontent.com/41752922/73504771-7a103e00-439e-11ea-919d-a797ab810af8.png)

**Comment by rekmarks** [comment] 2020-02-11 17:09
In my own testing, confirmed that this works on iOS and fails as described above with Android on latest `develop`. I believe I have found the issue. Several errors are thrown in the console on iOS, but in Android we see this:
![image](https://user-images.githubusercontent.com/25517051/74260184-ebf55b00-4cad-11ea-808c-d10a89a4e00e.png)

We can surmise that the iOS and Android browsers have different access control settings. I'm going to see what I can find, and reach out to the OpenSea team if all else fails.

**Comment by benjlevesque** [comment] 2020-04-06 17:21
I'm getting HTTP POST calls blocked due to a CORS  policy: missing `No 'Access-Control-Allow-Origin' header is present on the requested resource`. My API, however, has this header corretly set. 

Using chrome debugger, I can see that the response of the OPTIONS call to my api contains no CORS header, but this instead:  `Client-Via: shouldInterceptRequest`, which seems to be related to React Native WebView on Android, as mentionned by @rekmarks .  

Is this the same issue mentionned here? will it fixed by #1427? 
In the meantime, is there a way to disable this?

**Closed** 2020-04-15 04:12 UTC
Labels: android, browser, bug, dapp-compatibility, needs-qa

**Comment by vladlensky** [comment] 2020-04-20 15:17
I have the same issue with firebase firestore requests `Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
Requests are working correctly in all browsers (Chrome, Mozilla, iOS Safari), except Metamask android browser.
