### ISSUE TITLE
Unable to unlock wallet with fingerprint scanner

### ISSUE THREAD

**Issue by rdymac** [MetaMask/metamask-mobile#1607] opened 2020-06-01 19:31 UTC
**Describe the bug**
User enables fingerprint scanner, but the app launches the eye / facial recognition scanner instead which is not setup nor in use in the phone.

If the user then goes a step backward and try login in with the password instead, the app fails with the following error: 

`Error: Unknown error: Could not encrypt value for service com.metamask`

If the user re-enables the sign-in with fingerprint feature and login with the password right away, the app 

**Smartphone (please complete the following information):**
- Samsung Galaxy S8+ 
- Android 9

**Comment by ibrahimtaveras00** [comment] 2020-06-01 19:44
Is it possible you can add the steps to reproduce this issue? 

I too own a Samsung (Note 9) and cannot reproduce this.

If you go to settings > Biometrics and security I am only using fingerprint and none of the above as user stated in saying _"which is not setup nor in use in the phone"_

![Screen Shot 2020-06-01 at 3 41 05 PM](https://user-images.githubusercontent.com/41752922/83447372-54637600-a41e-11ea-8c06-939cfc53decf.png)

And when I launch the app, I'm able to use fingerprint without any issues; seen here = https://recordit.co/x2qm64FRtp

It may be possible that the user does have Irises set up but doesn't realize it?  This can be checked on Samsung by going to settings > biometrics and security > Irises 

@estebanmino you have a Samsung device too right?  Are you able to reproduce?

**Comment by eliyastein** [comment] 2020-06-01 23:08
Hi Team,

I'm the initial reporter of this bug. Based on @ibrahimtaveras00 's feedback I checked my settings and I had irises registered, but not configured to unlock. I decided to remove the iris data, and this resolved my issue. I now get a fingerprint prompt when opening metamask and I'm able to unlock using the fingerprint.

Having said all that, the original experience did feel very much like a bug, especially not being able to log in with a password unless the sign in with fingerprint was toggled on. Either way, my issue is resolved, but I'm happy to help if you're trying to chase down this issue further. Please let me know.

**Comment by rdymac** [comment] 2020-06-02 11:50
I haven't checked the _Irises_ feature @ibrahimtaveras00, but I've myself tried enabling fingerprint in a Huawei P30 Lite and despite having the fingerprint slider enabled I'm never asked to use it, only the password text field is available. 

eliyastein gets a prompt to login with fingerprint after removing the Irises feature, I'll try to find something like that in Huawei.

**Comment by omnat** [comment] 2020-06-08 16:03
Noted @rdymac ! We are adding a way for user to trigger fingerprint sign-in on login screen. This should help you sign in with fingerprint even if fingerprint isn't asked for you (which by the way, seems like a device specific issue)

**Comment by duncan411** [comment] 2020-06-22 00:30
Im getting this error on an oppo with fingerprint enabled in settings:

Error: Unknown error: Could not encrypt value for service com.metamask

**Comment by FTBNFT** [comment] 2021-09-15 01:18
I am unable to login with my fingerprint. It says invalid password and that my fingerprint is not a match. This is the only way I have been logging in and now am unable to do so. All help would be awesome.

**Comment by FTBNFT** [comment] 2021-09-15 01:19
using a samsung s8, never had an issue until now

**Comment by FTBNFT** [comment] 2021-09-15 02:29
TG was able to recover with seed phras, reset the password. AND Biometrics working again :)

**Comment by AlexJupiter** [comment] 2022-04-27 12:23
This seems to be fixed now.

**Closed by AlexJupiter** 2022-04-27 12:23 UTC
Labels: bug, close issue candidate, android version compatibility, community

**Comment by M996** [comment] 2023-06-16 12:01
Hello, I am now experiencing an extremely similar issue using a RealMe C25. For several months only fingerprint was used to login to metamask, now metamask is requesting password and fingerprint login is no longer available. As a result, I am no longer able to login to metamask at all, is their a way to re-enable the fingerprint scanner?

**Comment by Kezuyaa** [comment] 2024-05-08 08:35
hello any update on this? on my xiaomi 12s my fingetprint is gone and i can't open my wallet is there any way to fix this??
