### ISSUE TITLE
Add token popup doesn't open

### ISSUE THREAD

**Issue by benjaminbouwyn** [MetaMask/metamask-mobile#2801] opened 2021-06-14 17:16 UTC
When I click on a link to add token to metamask, the popup doesn't open, and sometime the popup open few seconds/minutes later.

_Steps to reproduce the behavior_
1. Go to pancakeSwap for exemple
2. Click on "add to metamask" (from a pool listing for exemple)
4. Wait for the popup to open

iOS 14.6
Metamask 2.4.0

**Comment by benjaminbouwyn** [comment] 2021-06-14 17:37
It works if I kill the app and add a token from the first open tab, but if I switch tab it doesn't work anymore

**Comment by gantunesr** [comment] 2022-01-21 19:31
Hey @benjaminbouwyn, is this still an issue in the latest release?

**Comment by gantunesr** [comment] 2022-03-11 00:24
Dupe of #3722

**Closed by gantunesr** 2022-03-11 00:24 UTC
Labels: bug, community
