### ISSUE TITLE
eth_signTypedData request from WalletConnect v1 client fails silently 

### ISSUE THREAD

**Issue by bobwith2bees** [MetaMask/metamask-mobile#3887] opened 2022-03-12 16:38 UTC
**Describe the bug**
I have an app that leverages the WalletConnect protocol to pass a eth_signTypedData request to Metamask.  With the recent 4.1.1  Android and 4.2.2 IOS release that has some great improvements with WalletConnet (thank you)  but I am not seeing any response to my eth_signTypedData with Metamask wallets. 

**Screenshots**
Tapping on the Sign button closes the pop up... but that's all I can see.  No error, no results visible in my WalletConnect V1 client.
![2022-03-12_10-08-10](https://user-images.githubusercontent.com/81196211/158025969-cf904929-5938-4947-9394-5d694dfec4ab.jpg)
The form appears to be parsing correctly, as Metamask is presenting it well.
![2022-03-12_10-08-20](https://user-images.githubusercontent.com/81196211/158025978-53388c26-8f7b-40f0-aa23-504b8b09ff59.jpg)

**To Reproduce**
1. Connect a WalletClient App*. (My app specific instructions below)
2. Issue a  eth_signedTypeData request to the Metamask wallet
Metamask is showing the Signing request, and has clearly parsed the SignedTypeData information.
3. Tap on the sign button to continue
Dismisses the bottom sheet, but that is all that happens

**Expected behavior**
* Metamask to prompt the user to re-authenticate (if required) and sign the message. Or present an error.
* Return signature to the WalletConnect client via rpc.  
* Bonus points if we can navigate back to my app. ( But that's a whole other challenge that's out of scope.)

**Smartphone (please complete the following information):**
 - Google Pixel 3 XL (and others). Apple Iphone 13 Pro
 - OS: IOS and Android 
 - App Version 4.1.1 (Android) 4.2.2.(IOS)

If you need a client app here is how to recreate with Graflr v1.51 (It's a bit involved.)
* Download Graflr from the Apple or Google Play stores. https://apps.apple.com/us/app/graflr/id1467953199 or https://play.google.com/store/apps/details?id=com.fifthpint.graflr
* Open app and dismiss the tutorials. 
* Navigate to profile and sign in with any of the providers you choose.
* Back navigate to the Profile screen again.  Tap  the setting icon.
* Connect wallet
* Tab the middle G button navigation.  Accept all the intrusive bluetooth.,etc requests.  If in an emulator these will be skipped.
* On the Discovery screen... long press the word Active multiple times until you see artists appear in the window.   Pick an artist and tap on their picture icon to receive a collectible.
* Navigate to the Collection tab and find the collectible you received.  Tap on the right hand side Jewel to open the details panel of the collectible.  
* Tap on the 'Mint the Moment' to initiate the NFT minting process which sends the SignedTypeData request to Matamask.  
* Continue with the reproduction steps above.

I am the author of the Graflr app - and there is alway the possibility for operator error.  I have the same code working with the Rainbow and Trust Wallets.  Happy to help anyway I can.  

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bobwith2bees** [comment] 2022-03-13 15:35
Example of the form being sent, if the issue happens to be data/format sensitive.

```
{
  "types": {
    "EIP712Domain": [
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "version",
        "type": "string"
      },
      {
        "name": "chainId",
        "type": "uint256"
      },
      {
        "name": "verifyingContract",
        "type": "address"
      }
    ],
    "Part": [
      {
        "name": "account",
        "type": "address"
      },
      {
        "name": "value",
        "type": "uint96"
      }
    ],
    "Mint721": [
      {
        "name": "tokenId",
        "type": "uint256"
      },
      {
        "name": "tokenURI",
        "type": "string"
      },
      {
        "name": "creators",
        "type": "Part[]"
      },
      {
        "name": "royalties",
        "type": "Part[]"
      }
    ]
  },
  "primaryType": "Mint721",
  "domain": {
    "name": "Mint721",
    "version": "1",
    "chainId": 4,
    "salt": "0",
    "verifyingContract": "0xf565108F208136B1AffD55d19A6236b6b6b9786D"
  },
  "message": {
    "@type": "ERC721",
    "contract": "0xf565108F208136B1AffD55d19A6236b6b6b9786D",
    "tokenURI": "/ipfs/QmRkbpbKwTpdGMve5cCXBWELh8ZqnFRR3Ch2zsm6tqPd4y",
    "tokenId": "57821959090642343791910250240090585543967286493013648175904625818401167638817",
    "uri": "/ipfs/QmRkbpbKwTpdGMve5cCXBWELh8ZqnFRR3Ch2zsm6tqPd4y",
    "creators": [
      {
        "account": "0x7Fd611Af09BeFB5f47aBB19FCC25a22997aEb0b1",
        "value": 10000
      }
    ],
    "royalties": [
      {
        "account": "0x0496E4f8C08558C192Bc205f598539406f2f6d57",
        "value": 500
      }
    ]
  }
}
```

**Comment by gantunesr** [comment] 2022-03-17 19:50
Hey @bobwith2bees, what are the params you are sending for `eth_signTypedData`?

**Comment by bobwith2bees** [comment] 2022-03-18 14:33
@gantunesr 

I am following this documentation for signedTyped Data that has the account address in the _first_ position:
https://docs.walletconnect.com/json-rpc-api-methods/ethereum#eth_signtypeddata

Here is the full encoded message just before encrypting it on the rpc. 

```
{"id":1647613713314000,"jsonrpc":"2.0","method":"eth_signTypedData","params":["0x7Fd611Af09BeFB5f47aBB19FCC25a22997aEb0b1","{\"types\":{\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"}],\"Part\":[{\"name\":\"account\",\"type\":\"address\"},{\"name\":\"value\",\"type\":\"uint96\"}],\"Mint721\":[{\"name\":\"tokenId\",\"type\":\"uint256\"},{\"name\":\"tokenURI\",\"type\":\"string\"},{\"name\":\"creators\",\"type\":\"Part[]\"},{\"name\":\"royalties\",\"type\":\"Part[]\"}]},\"primaryType\":\"Mint721\",\"domain\":{\"name\":\"Mint721\",\"version\":\"1\",\"chainId\":4,\"salt\":\"0\",\"verifyingContract\":\"0xf565108F208136B1AffD55d19A6236b6b6b9786D\"},\"message\":{\"@type\":\"ERC721\",\"contract\":\"0xf565108F208136B1AffD55d19A6236b6b6b9786D\",\"tokenURI\":\"/ipfs/QmTgJ4Foe2wnsU4ed75XBrqQvLdyq974yB6Rw74zzpv1Hg\",\"tokenId\":\"57821959090642343791910250240090585543967286493013648175904625818401167638825\",\"uri\":\"/ipfs/QmTgJ4Foe2wnsU4ed75XBrqQvLdyq974yB6Rw74zzpv1Hg\",\"creators\":[{\"account\":\"0x7Fd611Af09BeFB5f47aBB19FCC25a22997aEb0b1\",\"value\":10000}],\"royalties\":[{\"account\":\"0x0496E4f8C08558C192Bc205f598539406f2f6d57\",\"value\":500}]}}"]}
```

Thanks for taking a look!

**Comment by bobwith2bees** [comment] 2022-05-12 02:02
Still an issue with v5.0.1(877) on Android.   
I have a sample app that can be used for reproducing this error.  Clone this repo https://gitlab.com/graflr/flutter_rarible_example 

Please feel free to reach out for more information.  I would love to help get this issue resolved.

**Comment by kevinwo** [comment] 2022-05-13 17:53
I'm encountering this same issue as well.

**Comment by zaydadnan08** [comment] 2022-06-13 00:32
Hey @bobwith2bees did you solve this issue? I need to do something similar but am wondering if it is possible with wallet connect. 
Please reply asap!

**Comment by zaydadnan08** [comment] 2022-06-13 17:32
@bobwith2bees if it's not too much trouble, can I ask how you know support minting? Do you still use metamask or did you create a new wallet for the app specifically?

**Comment by zaydadnan08** [comment] 2022-06-13 20:07
@bobwith2bees 

Thanks for replying I really appreciate it! 
Do you think the web3dart library would work for signing transactions on a flutter/dart app? I'm focused on trying to mint from a flutter dapp but need to get some kind of authentication working. If theres any projects that you know of which have successfully done this with wallet verification, please let me know, 

Right now, I'm just trying to figure out if this is possible to do at all. 
In terms of your polygon implementation, were users able to use their own wallets to authenticate. If so, which libraries/language did you switch to?

**Comment by zaydadnan08** [comment] 2022-06-13 20:31
@kevinwo did you find a solution? or figure out why the error is occurring?

**Comment by bobwith2bees** [comment] 2022-06-14 16:44
@zaydadnan08  - The repo link I provided works fine with Rainbow Wallet and TrustWallet to perform the SignedTypedData request using WalletConnect.  The same example code fails with Metamask Mobile - hence this bug.

The example app uses a Rarible protocol endpoint to mint and not a web3dart call. If you use web3dart to send your transactions via Infuria, you will have to override the web3dart Credentials class and have it leverage the WalletConnect wallet for signing.  (I THINK that can be done - I am looking to see who has done it.  This person was trying to do it - https://github.com/xclud/web3dart/issues/16)

**Comment by kevinwo** [comment] 2022-07-19 21:01
@zaydadnan08 @bobwith2bees I think this issue is now a duplicate of [this issue](https://github.com/MetaMask/metamask-mobile/issues/4441) which calls out the details of the bug. It seems like we just need to sit tight until it is fixed.

**Closed** 2022-12-16 14:44 UTC
Labels: type-bug, WalletConnect, stability-team
