### ISSUE TITLE
Send NFT collectibles change input decimal to HEX

### ISSUE THREAD

**Issue by moohooooo** [MetaMask/metamask-mobile#2482] opened 2021-04-08 05:14 UTC
I tried to send #475
![image](https://user-images.githubusercontent.com/128964/113971638-59295f80-9863-11eb-8163-191f397daf00.png)

But it sent #1141
![image](https://user-images.githubusercontent.com/128964/113971641-5c245000-9863-11eb-8f49-9905b268f1d7.png)

So, it means ... try to input as Decimal but it sent as HEX that's why it changed from 475 to 1141
![image](https://user-images.githubusercontent.com/128964/113971650-60506d80-9863-11eb-9f32-633ade214ebb.png)

And I tried to input 1141.... not work still convert 1141 to Decimal

**Comment by omnat** [comment] 2021-04-08 19:00
@moohooooo Can you please add more details on reproduction steps?

**Comment by omnat** [comment] 2021-04-08 19:18
Closing as duplicate of #2423

**Closed by omnat** 2021-04-08 19:18 UTC
Labels: bug, custom network, needs-information, severity2-normal
