### ISSUE TITLE
SVGs not showing token images

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2236] opened 2021-02-10 20:32 UTC
![image](https://user-images.githubusercontent.com/41752922/107568297-c9459d00-6bb4-11eb-8512-d47f3eb7ee45.png)

![image](https://user-images.githubusercontent.com/41752922/107568367-e24e4e00-6bb4-11eb-9c29-b3a3b0f639ed.png)

**To Reproduce**
1. Go to add asset screen (wallet > add tokens) or request token screen (burger menu > add funds > request payment)
2. Search AAVE or KEY (on iOS) or SKM (on both android/iOS)

**Expected behavior**

I should see the images for the associated token

**Smartphone (please complete the following information):**
 - Device: some on iOS some on android

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by sethkfman** [comment] 2023-07-11 21:24
Not able to reproduce in latest version, closing

**Closed by sethkfman** 2023-07-11 21:24 UTC
Labels: type-bug, Sev3-low, team-mobile-client
