### ISSUE TITLE
Release debug version of MetaMask Mobile

### ISSUE THREAD

**Issue by dzek69** [MetaMask/metamask-mobile#2786] opened 2021-06-11 18:46 UTC
I want to run debug version of MetaMask and painlessly debug my app with MetaMask built-in browser.

According to this: https://docs.metamask.io/guide/mobile-best-practices.html#debugging i need a non-release version of MetaMask Mobile.

Building one myself looks like a real pain:
- I need some env values I don't have and I don't know purpose 
- README suggests: "Get the values from another MetaMask Mobile developer" - but who exactly? I don't know anyone
- Building React Native apps is itself a painful experience (I've done that few times, now I have clean machine so setting this up would be at least 2 days wasted)

So I wanted to ask if it's possible to share *.apk of non-release verison of MetaMask Mobile. I think it's good idea to release it with each new version here: https://github.com/MetaMask/metamask-mobile/releases as an attachment

But if anyone could just share *.apk here, I'd be also greatful.

**Comment by tamdinh** [comment] 2021-08-25 16:36
I have the same problem!

**Comment by githubdoramon** [comment] 2021-09-06 16:40
Facing the same issue. Where could we get the .env variables? Or any way to debug the in-app browser so I can understand why my application fails to load some content on the MEtamask app?

Regards

**Comment by newhope** [comment] 2021-11-02 08:14
Agree, for the god sake, I may take an **extra 5'** from your app developers to release a debug built compared to us - the web developer - spend a **few hours each** to figure out how to build (and likely to debug the "build" process) of an Android or iOS app.

**Comment by rickycodes** [comment] 2021-11-15 17:16
closing because this is a dupe of https://github.com/MetaMask/metamask-mobile/issues/1066 (we also currently post the debug apks in `/releases` now.

**Closed by rickycodes** 2021-11-15 17:16 UTC
Labels: community
