### ISSUE TITLE
Mobile app not updating on transaction success, while it does in desktop browsers

### ISSUE THREAD

**Issue by johannesmols** [MetaMask/metamask-mobile#1111] opened 2019-09-26 20:20 UTC
Hello, I'm currently developing a React app that interacts with a contract on the Rinkeby test network, and ran into an issue when testing it in the mobile app.

Whenever I'm sending a transaction, the user is shown a pop-up with a loading spinner, and then finally a success or error message once there is an update on the transaction from web3.

However, on mobile, I can see that the transaction is successful by the app itself, but the pop-up never switches to the success message.

I'm really not sure how this could be a bug in my own application, as it works perfectly fine on desktop browsers, but also don't know what the issue could be.

My code looks like this:
```javascript
handleSubmit = async event => {
    event.preventDefault();

    this.setState({ modalOpen: true, modalState: "processing" });

    try {
        await this.state.electionFactory.methods
            .createElection(
                this.state.title,
                this.state.description,
                convertTimeStringToDate(this.state.startTime),
                convertTimeStringToDate(this.state.timeLimit)
            )
            .send({ from: this.state.userAddresses[0] });

        this.setState({ modalState: "success" });
    } catch (err) {
        this.setState({ modalState: "error", errorMessage: err.message });
    }
};
```

When the state is switched to "success", it should show that. Is there any way to debug this in the mobile app and perhaps `console.log` some information in some way?
Furthermore, when an error occurs (e.g. I cancel the transaction), the `err.message` is also empty on mobile, which it should never be. This also works on the desktop.

Any insight would be highly appreciated, thanks!

**Comment by brunobar79** [comment] 2019-11-17 16:59
Duplicate of #1209. Closing this one since 1209 has exact repro steps

**Closed by brunobar79** 2019-11-17 16:59 UTC
