### ISSUE TITLE
[Bug]: Estimated gas fee won't load

### ISSUE THREAD

**Issue by coreyjanssen** [MetaMask/metamask-mobile#10911] opened 2024-08-29 23:20 UTC
### Describe the bug

In the mobile app, I am trying to send funds. The screen that should display the estimated gas fee won't load the fee, so I can't proceed. 

### Screenshots/Recordings

https://github.com/user-attachments/assets/b289a45e-df0f-4c23-93e2-78858cd0751b

### Steps to reproduce

1. Send money flow
2. Enter an amount of $ to send, then continue
3. On the Confirm screen, the estimated gas fee module may not load for you!

 

### Detection stage

In production (default)

### Version

7.29.0 (1397)

### Build type

None

### Device

iPhone 13 Mini 

### Operating system

iOS

**Comment by Nick-Son** [comment] 2024-08-30 01:00
I will close this issue as it is a duplicate of #10895

**Closed by Nick-Son** 2024-08-30 01:00 UTC
Labels: type-bug
