### ISSUE TITLE
Provide android apk 

### ISSUE THREAD

**Issue by Lilyandlucy** [MetaMask/metamask-mobile#2752] opened 2021-06-07 12:11 UTC
In China, we can't download application from google play, and in the official website, their is no download path for apk...Please provide the apk download path for us, thanks

**Comment by AndreiD** [comment] 2021-06-11 18:36
you should be very careful. because anyone can compile it, trojan it, and present it as APK.....

**Comment by rickycodes** [comment] 2021-11-15 17:14
closing because this a dupe of https://github.com/MetaMask/metamask-mobile/issues/1066

**Closed by rickycodes** 2021-11-15 17:14 UTC
Labels: community
