### ISSUE TITLE
[Bug]: Deep links are broken on mobile FireFox

### ISSUE THREAD

**Issue by Sap333** [MetaMask/metamask-mobile#7928] opened 2023-11-25 13:09 UTC
### Describe the bug

Once you open on any Metamask's deep link a mobile Firefox the Metamask's server brakes the link.

### Expected behavior

Deep link must redirect to a site specified in the link.

### Steps to reproduce

1. Open [https://metamask.app.link/dapp/https://biswap.org](https://metamask.app.link/dapp/https://biswap.org) in Firefox on a mobile Android platform.
"https://biswap.org" URL must be opened.
2.But once the browser opens "metamask.app.link" web site the URL is changed to https://metamask.app.link/dapp/https://undefined (which it a bug). The last part of a URL is always changed to "undefined" in Firefox.

Everything works as expected in Chrome browser on the very same devices.

### Version

Doesn't matter

### Build type

None

### Device

Android mobile platform

### Operating system

Android

### Additional context

In all other browsers redirect works as expected.
The bug is at "metamask.app.link" JS code.
No idea where to send this bug report, but is concerns the Metamask mobile application, so I guess here.

### Severity

Deep links are usable on Android/Firefox.

**Comment by anaamolnar** [comment] 2023-11-27 23:28
Hello, @Sap333. Thank you for taking the time to write this report. I will pass this on to the team for review.

**Comment by A-Feder** [comment] 2023-11-28 15:25
Hi @Sap333, can you please let me know what MetaMask version you are currently on?

**Comment by christopherferreira9** [comment] 2024-01-17 15:24
Android status: 

https://github.com/MetaMask/metamask-mobile/assets/104831203/7e3df692-41d8-43e9-913a-b442cad26cc6

iOS status:

https://github.com/MetaMask/metamask-mobile/assets/104831203/e4ca7e7b-dfa6-48fe-8654-996e0e277a4d


Both with 7.12.3.

**Comment by omridan159** [comment] 2024-02-27 13:55
@Sap333 
We are aware of this issue in Firefox on Android specifically, and this is something that we are unable to fix on the Wallet side at the moment, as it relates to a third-party service, and we are working with them to resolve it.

For the time being, we are closing this ticket.

Thanks!

**Closed by omridan159** 2024-02-27 13:55 UTC
Labels: type-bug, team-sdk, external-contributor

**Comment by saadabbasi-v** [comment] 2024-06-10 15:58
@omridan159 
`We are aware of this issue in Firefox on Android specifically,`
Though the issue is closed. I just want to add that issue is not limited to android, I am trying it on iOS + Firefox.
Looking for an update.

Details:
iOS: v16.2 
Firefox: v127.0 (42448)
Metamask: v7.23.0 (1333)
