### ISSUE TITLE
Android DApp sends an approve request to MetaMask via WalletConnect V2, and the received approve quantity will change.

### ISSUE THREAD

**Issue by jianesrq0724** [MetaMask/metamask-mobile#7148] opened 2023-09-06 13:09 UTC
Android WalletConnect V2 connect MetaMask。
DApp sends approve request to MetaMask , and the MetaMask received approve quantity will change

dapp send data:
0x095ea7b300000000000000000000000080d225d3125de96b4799267557316d59530e23b700000000000000000000000000000000000000000000142ef487396f1a560000

MetaMask received data:
0x095ea7b300000000000000000000000080d225d3125de96b4799267557316d59530e23b700000000000000000000000000000000000000000000142ef487396f1a000000

dapp send  approveNum：
hex:0x142ef487396f1a560000

MetaMask received approveNum:
hex:0x142ef487396f1a000000

SentRequest(requestId=1694748097543430, sessionTopic=7abc97bbc7d1db3563bd46b9cec217abf59edc9dc0de20c4240fbc9d29bebfcb, method=eth_sendTransaction, params=[{"from": "0x8d7804d45a4c73d3ffa213647a3107f9209d298b","to": "0xf7213bfe27788dd14430a4f1f9dd447090ada21b","data": "0x095ea7b300000000000000000000000080d225d3125de96b4799267557316d59530e23b700000000000000000000000000000000000000000000142ef487396f1a560000","nonce": "0x627","gas": "0x10ab2"}], chainId=eip155:11155111)

**Comment by andreahaku** [comment] 2023-09-13 10:00
@jianesrq0724 we'll try to replicate this. Do you have a dapp ready for testing this so that the debugging would be easier and faster. Thanks

**Comment by abretonc7s** [comment] 2023-09-14 02:46
hi @jianesrq0724 , specifically if you can send us the payload and exact rpc call you are calling?

**Comment by jianesrq0724** [comment] 2023-09-15 03:27
> 你好@jianesrq0724，特别是您是否可以向我们发送您正在调用的有效负载和确切的 rpc 调用？
WalletConnect V2,  sepolia chain.

SentRequest(requestId=1694748097543430, sessionTopic=7abc97bbc7d1db3563bd46b9cec217abf59edc9dc0de20c4240fbc9d29bebfcb, method=eth_sendTransaction, params=[{"from": "0x8d7804d45a4c73d3ffa213647a3107f9209d298a","to": "0xf7213bfe27788dd14430a4f1f9dd447090ada21b","data": "0x095ea7b300000000000000000000000080d225d3125de96b4799267557316d59530e23b700000000000000000000000000000000000000000000142ef487396f1a560000","nonce": "0x627","gas": "0x10ab2"}], chainId=eip155:11155111)

**Comment by jianesrq0724** [comment] 2023-09-15 03:31
> @jianesrq0724 we'll try to replicate this. Do you have a dapp ready for testing this so that the debugging would be easier and faster. Thanks

WalletConnect V2 SentRequest:
SentRequest(requestId=1694748097543430, sessionTopic=7abc97bbc7d1db3563bd46b9cec217abf59edc9dc0de20c4240fbc9d29bebfcb, method=eth_sendTransaction, params=[{"from": "0x8d7804d45a4c73d3ffa213647a3107f9209d298b","to": "0xf7213bfe27788dd14430a4f1f9dd447090ada21b","data": "0x095ea7b300000000000000000000000080d225d3125de96b4799267557316d59530e23b700000000000000000000000000000000000000000000142ef487396f1a560000","nonce": "0x627","gas": "0x10ab2"}], chainId=eip155:11155111)

**Comment by abretonc7s** [comment] 2023-10-04 09:53
hi @jianesrq0724 , thank you for providing the payload, we will test and get back to you this week.

**Comment by davidlevy** [comment] 2023-10-17 08:52
Hi @abretonc7s I explained on the community forum, I experience the same issue with WalletConnect v2 / React Native : 
https://community.metamask.io/t/android-dapp-sends-an-approve-request-to-metamask-via-walletconnect-v2-and-the-received-approve-quantity-will-change/26909/6

Did you have a chance to debug the issue ?

**Comment by vania221** [comment] 2023-10-25 03:59
Жодних проблем не має

**Comment by christopherferreira9** [comment] 2023-12-07 10:39
Hi! I'm sorry for the delay. We're currently working on prioritising this for Q1 (we weren't able to fit it into 2023).

**Comment by omridan159** [comment] 2024-02-27 18:30
@jianesrq0724 
We successfully managed to reproduce the issue with Version `7.16.0` of the MetaMask mobile app. However, after a thorough investigation, it seems the issue is fixed. The upcoming version (`7.17.0` which should be out in the app stores in about two weeks) won't have this issue.

Therefore, I'm closing this ticket. 
I recommend trying again with the new Wallet version once it's released. If the problem persists, please feel free to open a new issue.

Thank you!

**Closed by omridan159** 2024-02-27 18:30 UTC
Labels: type-bug, team-sdk, Sev2-normal
