### ISSUE TITLE
[Bug]: Removing the size prop in the BottomSheetFooter buttons props breaks link variant

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#8595] opened 2024-02-15 17:53 UTC
### Describe the bug

Removing the size prop in the bottomsheetfooter buttons props messes with the link variant
second kinda of a blocker: disabled prop does not work

### Expected behavior

Removing size prop should not break link button variant

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/8112138/d321a91e-9b41-43a7-8784-13cb5abf7636

### Steps to reproduce

1. Use the BottomSheetFooter with link variant

### Version

develop

### Build type

None

### Device

iphone

### Operating system

iOS

### Severity

- Blocker for ramps

**Comment by georgewrmarshall** [comment] 2024-02-19 21:00
@Pedro-vk please add any additional information if needed

**Comment by wachunei** [comment] 2024-02-20 16:54
@georgewrmarshall No more additional information needed, the code + video is straightforward

**Comment by brianacnguyen** [comment] 2024-02-26 02:39
@georgewrmarshall This is not a bug. When you remove the size variant of ButtonLink, it defaults to size Auto, which sets the ButtonLink to the inline auto size so the behavior you saw is 100% intended

**Comment by georgewrmarshall** [comment] 2024-02-26 20:23
@brianacnguyen as discussed in our 1:1 I'll defer to your decision to leave as is or update BottomSheetFooter to adjust the size of the ButtonLink during the mapping of the `buttonPropsArray` and whether it makes sense or might just complicate the component

**Comment by brianacnguyen** [comment] 2024-02-27 03:50
Closed as ButtonLink is working as intended

**Closed by brianacnguyen** 2024-02-27 03:50 UTC
Labels: type-bug, team-design-system
