### ISSUE TITLE
Could not fetch chain ID. Is your RPC URL correct? local node at http://192.168.1.4:8545 (Chain ID: 31337)

### ISSUE THREAD

**Issue by renzhichaos** [MetaMask/metamask-mobile#5830] opened 2023-02-24 03:10 UTC
I Started HTTP and WebSocket JSON-RPC server at http://192.168.1.4:8545/ used by hardhat 
I can through Chrome MetaMask Browser Extension 10.24.2 add it but can't through android metamask mobile 6.0.1 add
when i submit rpc-url http://192.168.1.4:8545 and chainId 31337, it tips "Could not fetch chain ID. Is your RPC URL correct?" 
After reading some metamask mobile source code, I still can't understand why there is this prompt, can anyone answer it? Or know how to solve this problem? I need to test some features about NFTs locally.

**Comment by DigitalsupportTeam** [comment] 2023-02-27 05:40
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by tommasini** [comment] 2023-04-21 08:36
@renzhichaos Hey, thanks for reporting!

Do you know if the same happens on IOS as well?

**Comment by deshvin** [comment] 2023-09-12 23:28
@tommasini
I'm reopening this since it's still an issue, I can reproduce this in my local environment.

The firewall rules on my node are solid.

I can connect to my node using RPC `http://192.168.1.222:8545` on extension and iOS, but Android gives the `Could not fetch chain ID. Is your RPC URL correct?` error.

I noticed on iOS that when adding the custom network for the first time, I received a system prompt asking for permission to allow MetaMask to communicate with local devices on my network; I didn't receive this prompt on Android. I'm unsure if this is relevant, though.

**Android**: MetaMask v7.6.0 (1169)
**iOS**: MetaMask v7.6.0 (1169)
**Extension**: MetaMask v11.0.0

**Comment by anaamolnar** [comment] 2023-09-26 09:41
Closing this in favor of https://github.com/MetaMask/metamask-mobile/issues/6843

**Closed by anaamolnar** 2023-09-26 09:41 UTC
Labels: type-bug, Sev3-low, team-mobile-client
