### ISSUE TITLE
v4.4.0 RC: Browser: Favorites not consistently showing on browser home, new browser tab

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#4012] opened 2022-04-01 03:48 UTC
*Discovered during iOS regression; needs investigation on whether it occurs in Android regression*

Favorites are not displayed consistently on the browser home page.  This is easily reproducible when switching networks and going to browser and open new tab but this also can be reproduced manually removing and adding browser tabs. 

- Wallet view
- Ethereum Mainnet selected network
- Tap browser
- open new tab
- Chances are you won't see your favorites, or all your favories
- If favorites are showing on browser home then switch networks and retry browser

Expected: Favorites to always show on new browser tab regardless of what network wallet is on.
Video: https://recordit.co/uO6bjDUJl6

This is not happening in production.

**Comment by mobularay** [comment] 2022-04-01 16:07
@chrisleewilcox , in discussing with @andrepimenta

- this conversation had happened in Dec 2021. A GH issue #3331 has already been opened
https://consensys.slack.com/archives/CBW7S9FSN/p1638810018460500 CC @sethkfman 
- happening in prod

Not a release blocker

**Comment by gantunesr** [comment] 2022-04-04 04:02
I'll close this issue @chrisleewilcox, as you mention its a dupe of https://github.com/MetaMask/metamask-mobile/issues/3331 and its not a trivial fix as Andre explained in that conversation

**Closed by gantunesr** 2022-04-04 04:02 UTC
Labels: needs-dev-review
