### ISSUE TITLE
Clicking on the home button sometimes wouldn’t show users’ favorite sites

### ISSUE THREAD

**Issue by blackdevelopa** [MetaMask/metamask-mobile#3569] opened 2022-01-13 18:55 UTC
**Describe the bug**
Clicking on the home button sometimes wouldn’t show users’ favorite sites (about half of the time)

**Screenshots**

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the browser (test on iOS devices). You should see your favorite sites if you have some
2. Click on the home icon. The home screen is refreshed without the favorite sites
3. See the error

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment] 2022-04-20 21:09
Dupe of #3331

**Closed by gantunesr** 2022-04-20 21:09 UTC
Labels: bug
