### ISSUE TITLE
window.ethereum is randomly null in a Flutter web app

### ISSUE THREAD

**Issue by treeder** [MetaMask/metamask-mobile#1956] opened 2020-11-04 16:27 UTC
**Describe the bug**

Checking for window.ethereum (after load) is often null on flutter web apps. It would seem flutter is affecting whatever Metamask mobile is doing to inject the ethereum object. It doesn't happen every time, but typically on initial load it will happen.

The Chrome extension doesn't have this problem btw.

**To Reproduce**

This happens on any flutter web app, I put up the generic flutter app here to show the behavior: 

https://trust-test-4f535.web.app/

See source to verify the `addEventListener`. 

**Expected behavior**

window.ethereum to not be null. 

**Smartphone (please complete the following information):**

 - Device: Pixel 4 XL
 - OS: Android 11
 - App Version: 1.0.5 (39)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by rekmarks** [comment] 2020-11-09 20:13
@treeder, the provider will not always be available on page load in mobile. Can you please check if using `@metamask/detect-provider` resolves your issue? See our documentation for details: https://docs.metamask.io/guide/mobile-best-practices.html#the-provider-window-ethereum

**Comment by treeder** [comment] 2020-11-17 15:42
Tried the new code from that link and still the same thing and pushed here: https://trust-test-4f535.web.app/.  Even waits 10 seconds. Just random times there is no window.ethereum.

**Comment by rekmarks** [comment] 2020-11-17 16:39
@treeder thank you for letting us know. We've determined that this issue affects some Android versions, and provider injection fails completely in these cases, just as you said.

We are working on determining the cause of the issue.

**Comment by rekmarks** [comment] 2020-11-17 20:14
I'm closing this in favor of #1975, which we believe refers to the same problem. We will announce further updates there.

**Closed by rekmarks** 2020-11-17 20:14 UTC
Labels: android, browser, bug
