### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#611] opened 2019-04-17 22:56 UTC
once https://github.com/MetaMask/metamask-extension/issues/577 is done, we can use the same palette for a dark mode in the app

**Comment by iamonuwa** [comment] 2019-07-23 13:33
> once [MetaMask/metamask-extension#577](https://github.com/MetaMask/metamask-extension/issues/577) is done, we can use the same palette for a dark mode in the app

Was about to ask for this. But seems it's already planned. I love dark mode.

**Comment by omnat** [comment] 2020-12-01 02:31
Closing as duplicate of #1381

**Closed** 2020-12-01 02:31 UTC
Labels: needs-design

**Comment by cyberfunk** [comment] 2021-05-06 12:40
It’s 2021 has there been any progress with this project?
