### ISSUE TITLE
Dapp doesn't refresh

### ISSUE THREAD

**Issue by eloudsa** [MetaMask/metamask-mobile#1211] opened 2019-11-17 16:53 UTC
Hi,
I have a Dapp that is a simple Greetings message.
On Desktop, the Dapp is properly refreshed when the balance changes or when the greetings changes.
On Metamask Mobile, when the transaction is confirmed, the Dapp is not refreshed.
I'm using:
* React 16.11.0
* Drizzle 1.5.1
* iOS 13.1.3
* Metamask mobile 0.2.10 (341)
Thanks

**Comment by brunobar79** [comment] 2019-11-17 18:13
Duplicate of #1209. Closing this one as the other issue has repro steps

**Closed by brunobar79** 2019-11-17 18:13 UTC
