### ISSUE TITLE
bug: When the sign message is called in the combination of walletconnect + metamask-mobile + mobile device, it is called to unconditionally switch the chain to the ethereum mainnet

### ISSUE THREAD

**Issue by siosio34** [MetaMask/metamask-mobile#7206] opened 2023-09-13 01:57 UTC
**Describe the bug**
When the sign message is called in the combination of walletconnect + metamask-mobile + mobile device, it is called to unconditionally switch the chain to the ethereum mainnet.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**

https://wagmi.sh/examples/sign-message

1.Click the link above on your mobile device to open it.
2. Connect to any chain except the Ethereum mainnet.
3. click sign message button
4. Then, the signing modal should appear, but then the network switching modal will appear.

**Expected behavior**
I want to call only signMessage without the chain conversion modal appearing on the Ethereum mainnet.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] galaxy s21
 - OS: [e.g. iOS8.1] android 
 - App Version [e.g. 1.0.0] - 7.6.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?  Users using Wallet Connect on all mobile devices must encounter a network change modal when signing or making a transaction, and are currently stuck in infinite loading due to the Metamask Wallet Connect issue.

https://github.com/MetaMask/metamask-mobile/issues/6655#issuecomment-1711413243
https://github.com/MetaMask/metamask-mobile/issues/7023

- Add stats if available on % of customers impacted  If you are a WalletConnect mobile user, 100%
- Is this visible to all users? yes
- Is this tech debt? yes

**Comment by anaamolnar** [comment] 2023-09-20 12:39
Hello, @siosio34. Thanks for the report! I have assigned this to the team last week. They will take a look at this as soon as they can. Thank you for your patience and understanding!

**Comment by siosio34** [comment] 2023-09-21 01:40
@anaamolnar  Thank you for always.

**Comment by abretonc7s** [comment] 2023-10-04 09:50
@siosio34 did you manually set a chainId in your request?
Please share the specific code so we can investigate more deeply.

**Comment by siosio34** [comment] 2023-10-10 04:37
@abretonc7s 


https://wagmi.sh/examples/sign-message

There is an example code in the link above, so it would be a good idea to refer to it as is. In addition to the example code, the same problem as the reported issue exists even if you run the example with Wallet Connect on mobile.

**Comment by abretonc7s** [comment] 2023-10-19 13:51
Sorry but I am confused on your request, are you referring to an issue with the sdk or with wallet connect?

**Comment by siosio34** [comment] 2023-10-23 04:30
@abretonc7s  To be precise, the issue is that when you try to open the sign modal to proceed with signing after connecting metamask mobile using walletconnect, a sudden network switching modal appears.

**Comment by abretonc7s** [comment] 2023-10-25 09:42
Hi @siosio34 , I think a safe way to avoid the issue could be to always do a chain request before sending your signing request to make sure you are on the correct network so you can control the flow.

**Comment by imaksp** [comment] 2023-10-26 07:20
This could happen if wagmi's walletclient chain (passed on connect call) is different than Metamask (this could happen in metamask web extension too). 
& also I could not regenerate the issue as per your steps.

Steps which I followed:

1. Visit https://wagmi.sh/examples/sign-message
2. keep latest metamask mobile Android app on polygon mainnet & connect using walletconnect
3. after connection success enter message & click Sign
4. Metamask mobile will display sign prompt & after approval it won't display any switch network dialog.

**Comment by siosio34** [comment] 2023-10-26 08:27
@imaksp 


Would you like to close MetaMask in the background and reconnect to WalletConnect on the website?

**Comment by siosio34** [comment] 2023-10-26 08:42
@imaksp 


I think this video will be helpful. I took a picture of the case with my phone.

https://github.com/MetaMask/metamask-mobile/assets/7166022/8a621898-3766-4cfc-bafc-d70a91c346df

**Comment by imaksp** [comment] 2023-10-26 09:13
Hi, I connected wc using wagmi desktop site & mobile (by scanning QR), not tested this way. will try again.

**Comment by imaksp** [comment] 2023-10-26 10:09
Hi @siosio34 , I can regenerate it, using mobile site (in Android Chrome) , walletconnect & metamask app. 
it seems walletconnect and/or MM app behaviour is different if deeplink is used instead of QR scan. 
but still if wallet app's network & network passed in wagmi core's connect is same it (lib) won't call switch chain & you won't have this issue. but this is not an perfect solution, will let you know if I find any better workaround.

**Comment by christopherferreira9** [comment] 2023-10-26 13:45
Hi @siosio34 , Can you please provide a video of the bug you're mentioning? 

Connection with mainnet initially selected:

https://github.com/MetaMask/metamask-mobile/assets/104831203/1f39950c-0146-44b2-aab9-ef43c90eda94

Connection with other chain initially selected:


https://github.com/MetaMask/metamask-mobile/assets/104831203/5df702e3-c588-46ef-b550-7bfc76d0e657

This last video is the intended behaviour as it is [initially configured](https://wagmi.sh/examples/connect-wallet) for mainnet :
```
const { chains, publicClient, webSocketPublicClient } = configureChains(
  [mainnet],  // Here
  [alchemyProvider({ apiKey: 'yourAlchemyApiKey' }), publicProvider()],
)
```

**Comment by imaksp** [comment] 2023-10-26 14:08
> I think this video will be helpful. I took a picture of the case with my phone.

He already shared video in previous message, QR code based flow is working as expected, but with deeplink (if you open https://wagmi.sh/examples/sign-message in mobile browser ) based flow has bugs as mentioned below:
 
during my testing it shows switch chain for mainnet but after you click switch network  metamask app will go into background & it will open website/dapp & dapp will keep showing loading, after that you need to open MM app again using app switcher, & click on the sign in app. so it requires manual app switching (only checked on Android).

Also many times after switchChain success event is not received in dapp (in QR based flow too), so dapp keeps showing different chain, but that's different issue.

**Comment by christopherferreira9** [comment] 2023-10-26 14:20
@imaksp you're right! For some reason the page was not updated with the latest replies. It seems that there is definitely a regression here as the wallet is sending back after the chain switch and it should wait for the sign request to show up. Will escalate.

https://github.com/MetaMask/metamask-mobile/assets/104831203/91f91eb8-fc50-46ec-8e0c-5d71e36301f0

**Comment by siosio34** [comment] 2023-10-27 01:25
> @siosio34 as mentioned by @christopherferreira9 switch chain popup is intended behaviour as at least one chain is required by viem's walletclient, to solve that you can find the MM app's current chain after successful connection & you can pass that chain in walletClient & after that you can call signMessage method.

I don't quite understand what you said. From what I understand, this is the intended behavior when accessed through a deep link, and does this mean that to solve this, it should be solved through Viem or Walletconnect rather than MetaMask Mobile?

**Comment by imaksp** [comment] 2023-10-27 02:36
Hi @siosio34 yes it is wagmi/core & viem's behaviour if walletclient & wallet app's chain does not match it will call switchChain internally (for all connectors incl walletconnect, metamask etc), so you should solve it using that lib. Intitally pass all supported chains by you dapp in wagmi's config & after that use wallet's app current chain in creating walletclient & then call signMessage.

**Comment by siosio34** [comment] 2023-10-27 05:22
@imaksp 
I'm really sorry, but can you tell me the code? Or are you talking about writing something like below?

```tsx
async function signMessageCuston() {
      const { chain } = getNetwork()

      const walletCilent = await getWalletClient({
        chainId: chain.id,
      })

      walletCilent.signMessage(message)
}
```

**Comment by imaksp** [comment] 2023-10-27 05:28
yes chain id passed in getWalletClient should match with wallet app's current chain, so first you can find current network  & use this code. (current network should also be present in wagmi config otherwise it will be considered as unsupported chain)

**Comment by siosio34** [comment] 2023-10-27 05:34
When connecting to MetaMask with Wallet Connect, is it correct to use the API below to retrieve the chain ID currently connected to the application?

https://wagmi.sh/core/actions/getNetwork

**Comment by imaksp** [comment] 2023-10-27 05:37
Hi, yes & you can create discussion in wagmi repo f you face any further issue. as I think this is not the right place. Thanks.

**Comment by siosio34** [comment] 2023-10-27 05:47
thank you. I am always grateful to @imaksp  and the MetaMask Mobile team.

**Comment by siosio34** [comment] 2023-10-27 05:49
@imaksp 

https://github.com/wagmi-dev/wagmi/issues/2991#issuecomment-1713182095


It's probably related to this issue.

**Comment by siosio34** [comment] 2023-10-31 07:44
@imaksp 

https://github.com/MetaMask/metamask-mobile/issues/7206#issuecomment-1782312380

this solution not working haha...

**Comment by siosio34** [comment] 2023-11-07 06:26
@imaksp  

MetaMask Mobile 7.10.0 is coming out soon. Will this issue be resolved there?

**Comment by A-Feder** [comment] 2023-11-28 15:28
hey @siosio34 , just wanted to check if the issue is persisting after you updated MetaMask to the latest version

**Comment by siosio34** [comment] 2023-12-01 06:00
The issue still occurs in metamask mobile 7.11.0. @A-Feder

**Comment by siosio34** [comment] 2023-12-01 06:03
@A-Feder 

You can also test it yourself by referring to the link.

https://github.com/MetaMask/metamask-mobile/issues/7206#issuecomment-1780672072

 https://wagmi.sh/examples/sign-message

**Comment by omridan159** [comment] 2024-02-01 09:10
This PR resolves the issue:
https://github.com/MetaMask/metamask-mobile/pull/8496

**Closed** 2024-02-01 10:01 UTC
Labels: type-bug, team-sdk, Sev2-normal, WalletConnect
