### ISSUE TITLE
Cannot Open Metamask in Iphone XR IOS 15

### ISSUE THREAD

**Issue by Fadeli16** [MetaMask/metamask-mobile#3586] opened 2022-01-18 04:14 UTC
**Describe the bug**
I cant open my metamask this morning its stuck in opening screen and cant access my wallet, how to fix it? I not yet backup my phrase so i hope unistall and install again is not better option

**Screenshots**
![1108504C-7A9E-475A-9F81-AC494C43F9AC](https://user-images.githubusercontent.com/82067418/149869806-2db1e924-8ff8-4a98-aeea-12faefdd00ea.png)

**Smartphone (please complete the following information):**
 - Device: Iphone Xr
 - OS: iOS 15
 - App Version 3.8.0

-------------------------------------------------------------
_

**Comment by Fadeli16** [comment] 2022-01-18 04:28
@sethkfman please fix the bug

**Comment by gantunesr** [comment] 2022-01-25 14:03
Dupe of #3528

**Closed by gantunesr** 2022-01-25 14:03 UTC
Labels: bug
