### ISSUE TITLE
Icons not appearing for some dapps

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1335] opened 2020-02-10 23:34 UTC
![Screenshot_2020-02-09-14-33-48-250_io metamask](https://user-images.githubusercontent.com/44038140/74200038-b5bacb80-4c1a-11ea-9267-6a9589ec2296.jpg)

**Comment by rickycodes** [comment] 2020-02-15 06:43
this looks like a dupe of https://github.com/MetaMask/metamask-mobile/issues/1261

**Closed** 2020-03-30 15:02 UTC
Labels: bug
