### ISSUE TITLE
Switch networks api works on chrome extension, but not on mobile wallet apps. 

### ISSUE THREAD

**Issue by pashpashpash** [MetaMask/metamask-mobile#3882] opened 2022-03-11 06:00 UTC
**Describe the bug**
Metamask ``wallet_switchEthereumChain`` api works on chrome extension, but not on mobile wallet apps. 

**Screenshots**
This is my code:
```
    const handleSwitch = React.useCallback(() => {
        console.log('[SwitchChains] Handling switch', {
            active,
            account,
            library,
            chainId,
            isMetaMask,
            isCoinbaseWallet,
            isPortis,
        });
        if (isMetaMask || isCoinbaseWallet) {
            library.currentProvider
                ?.request({
                    method: 'wallet_switchEthereumChain',
                    params: [{ chainId: '0x' + to?.toString(16) }], // chainId must be in hexadecimal numbers
                })
                ?.then(r => {
                    console.log('[SwitchChains] Success switching to ', to);
                })
                ?.catch(e => {
                    console.log('[SwitchChains] Error!', { e });
                    // This error code indicates that the chain has not been added to MetaMask.
                    if (e.code === 4902) {
                        library.currentProvider
                            ?.request({
                                method: 'wallet_addEthereumChain',
                                params: getChainParams(to),
                            })
                            ?.then(() => {
                                console.log(
                                    '[SwitchChains] Success adding network: ',
                                    to
                                );
                            })
                            ?.catch(error => {
                                console.log(
                                    '[SwitchChains] Error adding network!',
                                    {
                                        error,
                                    }
                                );
                            });
                    }
                });
        } else if (isPortis) {
            portis.changeNetwork(137);
        }
    }, [to, chainId, library]);
```

**To Reproduce**
1. Go to ['this page'](https://redeemable.app/create) on the metamask wallet app on iOS. 
2. Connect your wallet to the webapp. Make sure it is not on Polygon, so the switch network button appears after you log in.
3. Once your wallet is connected, you will see a switch networks button (that calls the code above onPress).  Click the button.
4. The switch networks button fails on the metamask mobile app, but works with the chrome extension. 

**Expected behavior**
I would expect the switch networks api to work on metamask mobile apps the same way it does with the chrome extension -- that is, it would add/switch networks successfully.

**Smartphone (please complete the following information):**
Devide: iPhone 11 iOS version 15.3.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment] 2022-03-15 17:09
Dupe of #3312

**Closed by gantunesr** 2022-03-15 17:09 UTC
Labels: bug, severity2-normal
