### ISSUE TITLE
PollingBlockTracker - encountered an error while attempting to update latest block

### ISSUE THREAD

**Issue by csk882** [MetaMask/metamask-mobile#5467] opened 2023-01-10 11:08 UTC
I ran metro in metamask-mobile and started android.
If you move the screen after the app is loaded normally, the following error occurs. No matter what I do, the same error occurs.

 WARN  Require cycle: node_modules/react-native-crypto/index.js -> node_modules/react-native-randombytes/index.js -> node_modules/sjcl/sjcl.js -> node_modules/react-native-crypto/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/stream-browserify/index.js -> node_modules/stream-browserify/node_modules/readable-stream/readable.js -> node_modules/stream-browserify/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/whatwg-fetch/dist/fetch.umd.js -> node_modules/react-native/Libraries/Network/fetch.js -> node_modules/whatwg-fetch/dist/fetch.umd.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/react-native/Libraries/Network/fetch.js -> node_modules/react-native/Libraries/Network/fetch.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/react-native/Libraries/Network/fetch.js -> node_modules/react-native/Libraries/Network/fetch.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/react-native/Libraries/Network/fetch.js -> node_modules/react-native/Libraries/Network/fetch.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: app/core/Engine.js -> app/util/networks/index.js -> app/core/Engine.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: app/core/Engine.js -> app/core/NotificationManager.js -> app/core/Engine.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 WARN  Require cycle: node_modules/rn-fetch-blob/index.js -> node_modules/rn-fetch-blob/polyfill/index.js -> node_modules/rn-fetch-blob/polyfill/Blob.js -> node_modules/rn-fetch-blob/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/rn-fetch-blob/index.js -> node_modules/rn-fetch-blob/polyfill/index.js -> node_modules/rn-fetch-blob/polyfill/XMLHttpRequest.js -> node_modules/rn-fetch-blob/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/rn-fetch-blob/index.js -> node_modules/rn-fetch-blob/polyfill/index.js -> node_modules/rn-fetch-blob/polyfill/Fetch.js -> node_modules/rn-fetch-blob/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 INFO  Initializing react-native-branch v. 5.6.2
 LOG  Running "MetaMask" with {"initialProps":{"foxCode":"EXAMPLE_FOX_CODE"},"rootTag":1}
 LOG  Sentry Logger [Log]: Integration installed: ReactNativeErrorHandlers
 LOG  Sentry Logger [Log]: Integration installed: Release
 LOG  Sentry Logger [Log]: Integration installed: InboundFilters
 LOG  Sentry Logger [Log]: Integration installed: FunctionToString
 LOG  Sentry Logger [Log]: Integration installed: Breadcrumbs
 LOG  Sentry Logger [Log]: Integration installed: LinkedErrors
 LOG  Sentry Logger [Log]: Integration installed: UserAgent
 LOG  Sentry Logger [Log]: Integration installed: DebugSymbolicator
 LOG  Sentry Logger [Log]: Integration installed: RewriteFrames
 LOG  Sentry Logger [Log]: Integration installed: DeviceContext
 LOG  Sentry Logger [Log]: Integration installed: Dedupe
 LOG  Sentry Logger [Log]: Integration installed: ExtraErrorData
 LOG  Sentry Logger [Log]: Setting idle transaction on scope. Span ID: 8f221beb0c8504dc
 LOG  Sentry Logger [Log]: [Tracing] starting navigation transaction - Route Change
 LOG  Sentry Logger [Log]: Starting heartbeat
 LOG  Sentry Logger [Log]: pinging Heartbeat -> current counter: 0
 LOG  Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
 LOG  Sentry Logger [Log]: Integration installed: ReactNativeTracing
 LOG  Sentry Logger [Log]: [Tracing] finishing IdleTransaction 2023-01-10T01:44:23.550Z navigation
 LOG  Sentry Logger [Log]: [Tracing] flushing IdleTransaction
 LOG  Sentry Logger [Log]: Setting idle transaction on scope. Span ID: 8883e50029be5411
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because it's not included in the random sample (sampling rate = 0.2)
 LOG  Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
 LOG  Sentry Logger [Log]: [ReactNavigationV5Instrumentation] Will not send transaction "Wallet" due to beforeNavigate.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because its trace was not chosen to be sampled.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  Sentry Logger [Log]: Setting idle transaction on scope. Span ID: 86bd2415ed386e00
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because it's not included in the random sample (sampling rate = 0.2)
 LOG  Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
 LOG  Sentry Logger [Log]: [ReactNavigationV5Instrumentation] Will not send transaction "Asset" due to beforeNavigate.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because its trace was not chosen to be sampled.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  Sentry Logger [Log]: Setting idle transaction on scope. Span ID: 941a950c63cc4d9c
 LOG  Sentry Logger [Log]: [Tracing] starting navigation transaction - Route Change
 LOG  Sentry Logger [Log]: Starting heartbeat
 LOG  Sentry Logger [Log]: pinging Heartbeat -> current counter: 0
 LOG  Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
 LOG  Sentry Logger [Log]: Setting idle transaction on scope. Span ID: bffea60903c38b72
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because it's not included in the random sample (sampling rate = 0.2)
 LOG  Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
 LOG  Sentry Logger [Log]: [ReactNavigationV5Instrumentation] Will not send transaction "SendTo" due to beforeNavigate.
 LOG  Sentry Logger [Log]: Setting idle transaction on scope. Span ID: ba2643e30f7f28a7
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because it's not included in the random sample (sampling rate = 0.2)
 LOG  Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
 LOG  Sentry Logger [Log]: [Tracing] finishing IdleTransaction 2023-01-10T01:49:00.967Z navigation
 LOG  Sentry Logger [Log]: [Tracing] flushing IdleTransaction
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because its trace was not chosen to be sampled.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because its trace was not chosen to be sampled.
 LOG  Sentry Logger [Log]: Setting idle transaction on scope. Span ID: ae2df378622490ca
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because it's not included in the random sample (sampling rate = 0.2)
 LOG  Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
 LOG  Sentry Logger [Log]: Setting idle transaction on scope. Span ID: 836b1bbf41ee83d9
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because it's not included in the random sample (sampling rate = 0.2)
 LOG  Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
 LOG  Sentry Logger [Log]: [ReactNavigationV5Instrumentation] Will not send transaction "Amount" due to beforeNavigate.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because its trace was not chosen to be sampled.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because its trace was not chosen to be sampled.
 LOG  [MetaMask DEBUG]: Analytics 'trackEventWithParameters' - {"action": "Send Flow", "category": "Send Flow", "name": "Adds recipient address 'Send to'"} {"network": "mainnet"} undefined undefined
 LOG  Sentry Logger [Log]: Setting idle transaction on scope. Span ID: 99a5b258667f54b6
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because it's not included in the random sample (sampling rate = 0.2)
 LOG  Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
 LOG  Sentry Logger [Log]: [ReactNavigationV5Instrumentation] Will not send transaction "SendTo" due to beforeNavigate.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because its trace was not chosen to be sampled.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  Sentry Logger [Log]: Setting idle transaction on scope. Span ID: b902e4aa7c127ee0
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because it's not included in the random sample (sampling rate = 0.2)
 LOG  Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
 LOG  Sentry Logger [Log]: [ReactNavigationV5Instrumentation] Will not send transaction "Asset" due to beforeNavigate.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because its trace was not chosen to be sampled.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  [MetaMask DEBUG]: Analytics 'trackEventWithParameters' - {"action": "Send Flow", "category": "Send Flow", "name": "Cancel"} {"network": "mainnet", "view": "send_to"} undefined undefined
 LOG  Sentry Logger [Log]: Setting idle transaction on scope. Span ID: 90826d6f26794c7a
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because it's not included in the random sample (sampling rate = 0.2)
 LOG  Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
 LOG  Sentry Logger [Log]: [ReactNavigationV5Instrumentation] Will not send transaction "Wallet" due to beforeNavigate.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  Sentry Logger [Log]: [Tracing] Discarding transaction because its trace was not chosen to be sampled.
 LOG  Sentry Logger [Log]: [Tracing] No active IdleTransaction
 LOG  [MetaMask DEBUG]: Analytics 'trackEventWithParameters' - {"category": "Network Switched"} {"chain_id": "5", "source": "Settings"} undefined undefined
Error: ENOENT: no such file or directory, open '/home/csk882/metamask-mobile/http:/localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at getCodeFrame (/home/csk882/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:919:18)
    at Server._symbolicate (/home/csk882/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:992:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server._processRequest (/home/csk882/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:403:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/csk882/metamask-mobile/http:/localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true'
}
Error: ENOENT: no such file or directory, open '/home/csk882/metamask-mobile/http:/localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at getCodeFrame (/home/csk882/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:919:18)
    at Server._symbolicate (/home/csk882/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:992:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server._processRequest (/home/csk882/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:403:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/csk882/metamask-mobile/http:/localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true'
}
 ERROR  [Error: PollingBlockTracker - encountered an error while attempting to update latest block:
construct@[native code]
Wrapper@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:25912:64
construct@[native code]
_createSuperInternal@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:242864:406
EthereumRpcError@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:242888:26
getEthJsonRpcError@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:242812:78
internal@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:242738:34
createInternalError@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:243308:83
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:243245:38
generatorResume@[native code]
asyncGeneratorStep@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:27213:26
_next@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:27235:29
tryCallOne@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:32448:16
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:32549:27
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:33717:26
_callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:33613:17
_callReactNativeMicrotasksPass@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:33652:17
callReactNativeMicrotasks@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:33862:44
__callReactNativeMicrotasks@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:8476:46
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:8254:45
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:8459:15
flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:8253:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]]
Error: ENOENT: no such file or directory, open '/home/csk882/metamask-mobile/http:/localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at getCodeFrame (/home/csk882/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:919:18)
    at Server._symbolicate (/home/csk882/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:992:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server._processRequest (/home/csk882/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:403:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/csk882/metamask-mobile/http:/localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true'
}
Error: ENOENT: no such file or directory, open '/home/csk882/metamask-mobile/http:/localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at getCodeFrame (/home/csk882/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:919:18)
    at Server._symbolicate (/home/csk882/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:992:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server._processRequest (/home/csk882/metamask-mobile/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:403:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/csk882/metamask-mobile/http:/localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true'
}

**Comment by cortisiko** [comment] 2023-01-22 17:32
Closing since this relates to https://github.com/MetaMask/metamask-mobile/issues/5515#issuecomment-1397380771

**Closed by cortisiko** 2023-01-22 17:32 UTC

**Comment by det-joe** [comment] 2023-05-31 02:17
This error message came from Infura, and it was caused by not been able to read .env/.js.env properly.

At least in my case, the Infura project id was undefined in the code (it took me 4 painful days to realize this...) and thus all Infura API call failed, eventually the wallet UI was not able to update current state (asset/NFT etc.) for all chains that rely on Infura API.

**Comment by codescrafter** [comment] 2024-05-10 20:55
> MM_INFURA_PROJECT_ID

worked for me
