### ISSUE TITLE
[Bug] Deeplinks don't work because `chainId` is not detected

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7177] opened 2023-09-08 11:54 UTC
**Describe the bug**
I cannot use any Deeplink transaction because of an error saying network with `chainId` xyz is not detected.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/92a4ea77-3736-4336-8031-ca78697534c0

**To Reproduce**
_Steps to reproduce the behavior_
1. Create a deeplink https://metamask.github.io/metamask-deeplinks/#
2. Scan or click the link with the wallet
3. See `network with chainId XYZ not detected`

This happens both if you don't specify the chainId and if you specify the chainId on the deeplink.

**Expected behavior**
Deeplinks should work both if you specify the chaniId and if you don't

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `main`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by seaona** [comment] 2023-09-13 08:06
Seems hard to repro. Some observations:
Saw this happen after triggering this error and being logged out and logged in again

Repro:
1. Trigger this error https://github.com/MetaMask/metamask-mobile/issues/7149
2. Scan a deeplink

**Comment by ssain2021** [comment] 2023-11-11 13:02
In my website, I am using web3.js for wallet connection, and browser extension for most wallets are working fine on laptop/desktop. But I am getting issue with deeplink on metamask browser using mobile devices. The connect button works, but unable to fetch any wallet balances. The error is with chainID (chainID is not detected). Could someone please help me resolve the issue ? Thanks..

**Comment by gauthierpetetin** [comment] 2024-02-09 16:25
Closing this issue as we're not able to reproduce it anymore.

**Closed by gauthierpetetin** 2024-02-09 16:25 UTC
Labels: type-bug, deeplinks, Sev2-normal, team-mobile-platform
