### ISSUE TITLE
Cookies functionality not working

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/metamask-mobile#4245] opened 2022-05-06 04:59 UTC
**Describe the bug**
The cookies functionality have been broken for the past releases. This bug is causing a lot of issues to the developer community and not allowing Dapps to work properly with MetaMask mobile.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

Some issues provide screenshots and/or recordings. They'll be referenced.

**To Reproduce**
_Steps to reproduce the behavior_

Some issues go over the steps to reproduce this bug. They'll be referenced.

**Expected behavior**
Cookies functionality should work properly in MMM.

**Smartphone (please complete the following information):**
 - Device: All devices
 - OS: iOS and Android
 - App Version [e.g. 1.0.0] - v5.0.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- Is this visible to all users? `YES`
- Is this tech debt? `NO`

**Comment by Cianekjr** [comment] 2022-05-07 18:21
Hello.

I'm gonna describe my problem. In my case I use getServerSideProps in nextjs:

```
const MyItemsPage = () => {
  // just to show if metamask wallet is injected
  useEffect(() => {
    const interval = setInterval(() => {
      toast.info(typeof window.ethereum);
    }, 4000);
    return () => clearInterval(interval);
  }, []);
  return <div></div>;
};

export const getServerSideProps = withSession(async function ({ req }) {
  const user = req.session.get("user");

  console.log({ user });
  if (!user) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      user,
    },
  };
});

export default MyItemsPage;
```

After log in I open /my-items page on desktop/iphone:

```
-----------------------------------
console.log({ user }) => 
{
  user: {
    id: 6,
    metamaskAddress: '0x62...7a5',
    nickname: 'cianekjr'
  }
}
-----------------------------------
toast.info(typeof window.ethereum) => Object
-----------------------------------
```
so I have user and metamask wallet is injected - perfect.

Now I do the same on android:
```
-----------------------------------
console.log({ user }) => 
{ user: undefined }
{
  user: {
    id: 6,
    metamaskAddress: '0x62...7a5',
    nickname: 'cianekjr'
  }
}
-----------------------------------
toast.info(typeof window.ethereum) => undefined
-----------------------------------
```

Why two requests are made? First without session (cookies) passed and second one with session. And ok, I got user from server from second request, but metamask wallet isn't injected so now if I want to make some transactions I can't.

If I remove:
```
  if (!user) {
    return {
      notFound: true,
    };
  }
```

```
-----------------------------------
console.log({ user }) => 
{ user: undefined }
-----------------------------------
toast.info(typeof window.ethereum) => Object
-----------------------------------
```

so now wallet is connected, but I don't have user session.

Of course I can fix this problem just not using session on server, but there are some drawbacks:
- time to rewrite all pages which use session in getServerSideProps and do everything on client side,
- handle all loading states with skeletons,
- can't do redirects on server. For example I go to /my-items and after some time my code checks that user is not logged in so I have to redirect him to /sign-in using router.push. It makes UX much worse than using redirect on server.

Because of that bug 20% of my users (android users) can't interact with my site because wallet is not injected. Fingers crossed for fast fix :D.

**Comment by jeromew** [comment] 2022-05-12 14:14
I can confirm that the android version of metamask-mobile browser seem to have a problem with websites that use server side sessions and exchange the session ids via cookies. It also affects websites developed with Ruby On Rails session handling.

**Comment by JonathanTFairy** [comment] 2022-05-20 23:25
Hi, we're being having the same issues with the cookies not working on our side for android devices.

I've being doing some digging on the server side of this and found the following.

When rendering the webpage my server receives all the request without cookies. No matter how many times I reload the page all request related to loading the page come without cookies. Doe to this behavior, a new server session is assigned to each page reload.

On the other hand, when making asynchronous request. They correctly preserve cookies between subsequent request but the cookies are not from the loaded pages rather they seems to be assigned independently from the page loaded and this cause the session on the request to be different from the session on the loaded page.

To illustrate my point here are some logs:

This log is when loading the page, it those not have a session saved on cookies (no cookies are included in the request) so it assigns a new one:
```
[2022-05-21 09:00:57] USER AGENT: Mozilla/5.0 (Linux; Android 11; SM-A505G Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.61 Mobile Safari/537.36
[2022-05-21 09:00:57] RECEIVED SESSION ID: 
[2022-05-21 09:00:57] SESSION ID: 8d684f69aa8d2a2e6cfbd90a64defc19
```

From the page that was just loaded. We make an asynchronous request to get user information to proceed with a login. The request already has a session saved on cookies but it is completely different from the one the page itself got.

```
[2022-05-21 09:02:29] USER AGENT: Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/OSM1.180201.023) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
[2022-05-21 09:02:29] RECEIVED SESSION ID: 38741c2d468300639ddb5346141e1048
[2022-05-21 09:02:48] SESSION ID: 38741c2d468300639ddb5346141e1048
```

Finally this is an async request to log in the user, It shares the same cookies as the previous request and again is different from the one the page should be using.

```
[2022-05-21 09:02:48] USER AGENT: Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/OSM1.180201.023) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
[2022-05-21 09:02:48] RECEIVED SESSION ID: 38741c2d468300639ddb5346141e1048
[2022-05-21 09:02:48] SESSION ID: 38741c2d468300639ddb5346141e1048
```

I was able to confirm this behavior on samsung phones, My main driver (Samsung A50) with MetaMask v5.1.1 and a Samsung M20 with MetaMask v5.1.1.

Another thing worthy to note is the user agent.
The user agent when rendering the webpage is different from the one making the async request.
For the A50 the user agent when rendering the page is:
`Mozilla/5.0 (Linux; Android 11; SM-A505G Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.61 Mobile Safari/537.36`
For the M20 is:
`Mozilla/5.0 (Linux; Android 10; SM-M205M Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.3`

And for both the user agent use for async request is:
`Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/OSM1.180201.023) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36`

**Comment by php4fan** [comment] 2022-06-20 12:12
Guys you should forget about providing an in-app browser. It's a huge waste of resources (and of users' time, because by providing it you create the expectation that it will at least barely work, and therefore we'll try it).

Do you seriously think you are able to provide a half-decent browser capable of competing with Google Chrome or Safari?? Well obviously not, as this issue proves (basic cookie handling broken = browser completely unusable). And even if you were, do you think users would be willing to switch to a browser embedded in a wallet app for their everyday browsing?

Instead, focus on integrating with existing browsers. Properly handling EIP-681 links would be a good place to start.

**Closed** 2022-12-16 14:42 UTC
Labels: type-bug, Sev2-normal, Priority - High, stability-team
