### ISSUE TITLE
Ethereum provider injection randomly fails on Android

### ISSUE THREAD

**Issue by arnoudcommandeur** [MetaMask/metamask-mobile#1975] opened 2020-11-10 16:37 UTC
**Describe the bug**
When I open my DApp, the web3 provider is not always injected. It doesn't make sence I use @metamask/detect-provider or plain window.ethereum call.

**To Reproduce**
_Steps to reproduce the behavior_
1. Start DApp 
2. Check if Web3 is injected via:

```
async function testEthereum() {

  const provider = await detectEthereumProvider()

  if (provider) {
    alert('YES');
  } else {
    alert('ERROR!');
      setTimeout(testEthereum, 3000); // 3 seconds
  }
}
```

I also tried adding an eventlistener, but this doesn't' work as well:

```
      window.addEventListener('ethereum#initialized', App.initWeb3, {
        once: true,
      });

```

In my HTML file I added:

`<script src="https://unpkg.com/@metamask/detect-provider/dist/detect-provider.min.js"></script>
`

3. Sometimes the web3 is not available. After refreshign the page, sometimes it works, sometimes it does not work.

**Expected behavior**
I expect the provider is always available.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 10
 - OS: Android 10
 - App Version 1.0.5 (39)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by rekmarks** [comment] 2020-11-10 18:20
Ref: #1931, #1956

**Comment by KarlWerft** [comment] 2020-11-12 16:06
Hi rekmarks,

did you solve the metamask detection problem already? I have the same issue.
Sometime the provider is detected, sometimes not, actually more often not.

This really completely stops any possible mobile usage of the dapp. I am totally frustrated.

**Comment by arnoudcommandeur** [comment] 2020-11-12 16:11
Hi @KarlWerft , unfortunately I haven't found a solution yet. It is really frustrating!

**Comment by KarlWerft** [comment] 2020-11-12 16:32
Maybe setting a higher timeout within the options of detectEthereumProvider?
Do you know if detectEthereumProvider excately return null or something else when it is not working?
The biggest probleem is that I cannot debug the mobile app. Maybe we could use a simple javascript alert to check, what is happening excatly? Unfortunately I cannot even call the dapp from my handy via WLAN intranet, because of ssl certificate issues. WLAN is no localhost :-(

**Comment by rekmarks** [comment] 2020-11-12 16:44
Hello, I'm sorry you are experiencing this problem. We believe that this is a problem with the Android browser/WebView implementation.

@KarlWerft, are you also on Android?

**Comment by KarlWerft** [comment] 2020-11-12 16:47
yes. Might  a higher timeout help linke detectEthereumProvider({timeout: 6000}) ?

**Comment by KarlWerft** [comment] 2020-11-12 16:47
like not linke

**Comment by rekmarks** [comment] 2020-11-12 16:50
We believe that, in these cases, the injection is failing completely, and that no timeout will help. That said, it can't hurt to try! Can you try a `10000` timeout?

**Comment by KarlWerft** [comment] 2020-11-12 16:52
i will try it as soon as I will be back at my development machine.

**Comment by arnoudcommandeur** [comment] 2020-11-12 19:57
I have tried different approaches. My conclusion is that web3 sometimes is not injected at all, dispite all the ways you can detect web3. When it is not injected, I tried detection after a few seconds, but unfortunately without any result.

**Comment by KarlWerft** [comment] 2020-11-13 11:18
The timeout had no positive effect. I read somewhere that a excately similar sounding problem occured when using the react module serviceworker. Did ever read about this?

**Comment by arnoudcommandeur** [comment] 2020-11-13 11:30
Hi @KarlWerft I have no experience with react.

**Comment by KarlWerft** [comment] 2020-11-13 13:30
React has nothing to do with the effect it seems. What version of Android did you experience the web3 problem with? Was Android 9? Would be an idea to see if different Versions behave differently or if different webkits do.

**Comment by KarlWerft** [comment] 2020-11-16 13:44
> We believe that, in these cases, the injection is failing completely, and that no timeout will help. That said, it can't hurt to try! Can you try a `10000` timeout?

Hi rekmarks,
I still don't have any solution for using metamask mobile on Android devices. Do you have any idea what I could do for a work around? it would be pretty sad if the only solution would be to restrict usage to apple devices, wouldn't it?
Are you planning at MetaMask to deal with the problem in any way?

**Comment by rekmarks** [comment] 2020-11-16 16:31
Hi @KarlWerft, we are troubleshooting this internally in an attempt to find a solution. The issue only appears to affect a minority of Android devices, and we're not sure why. I unfortunately cannot give an estimate for how long it will take at this time, but rest assured that it's one of our top priorities.

**Comment by arnoudcommandeur** [comment] 2020-11-16 18:15
If there is anything I can do to solve this issue, please let me know!

**Comment by shendel** [comment] 2020-11-17 20:05
> Hi @KarlWerft, we are troubleshooting this internally in an attempt to find a solution. The issue only appears to affect a minority of Android devices, and we're not sure why. I unfortunately cannot give an estimate for how long it will take at this time, but rest assured that it's one of our top priorities.


if it helps. I noticed that the 'ethereum#initialized' event is triggered before reloading the page - if you select "reload" in the menu, then the debug alert is triggered a split second before reloading

**Comment by shendel** [comment] 2020-11-23 21:16
@rekmarks , @omnat any ideas exists?? i se you are prerere v1.0.6, v1.0.7, but no more info about this bug....
One week left....

**Comment by shendel** [comment] 2020-11-23 21:18
@rekmarks , @omnat - can you setup your cli for build dev apk version? https://github.com/MetaMask/metamask-mobile/issues/1226

**Comment by shendel** [comment] 2020-11-23 21:50
@rekmarks , @omnat  - on real device - same picture
WTF!??
https://www.youtube.com/watch?v=TiJM5_nopUs

**Comment by shendel** [comment] 2020-11-23 22:12
Real device - android 8.1, Emulator 9.x, and @arnoudcommandeur with android 10 - your build-in dBrowser dont work

**Comment by omnat** [comment] 2020-11-23 22:41
Hi @shendel, we didn't work on this issue yet. 
Check what's in the latest releases here: https://github.com/MetaMask/metamask-mobile/releases

**Comment by EvilJordan** [comment] 2020-11-29 05:02
FYI, this is also a problem on iOS. Even the most basic page, with zero functionality, just detecting if there is a provider, fails.

**Comment by rekmarks** [comment] 2020-11-29 05:27
That's the first we've heard about this occurring on iOS. @EvilJordan, can you please provide further details in a new issue?

**Comment by EvilJordan** [comment] 2020-11-29 05:32
Sure!

Try this in MM Mobile's Browser and you'll get an "undefined":
```
<!doctype html>
<html>
<head>
	<script>
		window.addEventListener('load', async () => {
			alert(window.ethereum);
		});
	</script>
</head>
<body>
	Hello!
</body>
</html>
```

**Comment by rekmarks** [comment] 2020-11-29 05:36
Ah, we expect `window.ethereum` to be undefined in that case. If you run that event handler on a timeout of 1-2 seconds, it should be defined. This issue is about the provider _never_ being injected.

Please see this page in our documentation for more details: https://docs.metamask.io/guide/mobile-best-practices.html#provider-availability

**Comment by EvilJordan** [comment] 2020-11-29 05:44
Don't mean to clog up the issue, but this does nothing. Doesn't even fire alerts in MM mobile:

```
<!DOCTYPE html>
<html>

<head>
    <script>
        if (window.ethereum) {
            handleEthereum();
        } else {
            window.addEventListener('ethereum#initialized', handleEthereum, {
                once: true,
            });

            // If the event is not dispatched by the end of the timeout,
            // the user probably doesn't have MetaMask installed.
            setTimeout(handleEthereum, 3000); // 3 seconds
        }

        function handleEthereum() {
            const {
                ethereum
            } = window;
            if (ethereum && ethereum.isMetaMask) {
                alert('Ethereum successfully detected!');
                // Access the decentralized web!
            } else {
                alert('Please install MetaMask!');
            }
        }
    </script>
</head>

<body>
	Hello!
	<script>
		window.addEventListener('load', async () => {
			setTimeout(handleEthereum, 3000);
		});
	</script>
</body>

</html>
```

**Comment by EvilJordan** [comment] 2020-11-29 05:45
MY BAD. My mistake. It DOES fire alerts, but always, "Please install Metamask!"

**Comment by rekmarks** [comment] 2020-11-29 05:47
Hm, in that case, something else is wrong. Please open a new issue.

**Comment by shendel** [comment] 2020-11-29 13:09
I think, bug in https://github.com/MetaMask/inpage-provider, witch used by https://github.com/MetaMask/mobile-provider/

https://github.com/MetaMask/mobile-provider/blob/master/src/content-script/inpage-bundle.js
updated 4 mounth ago

**Comment by rekmarks** [comment] 2020-11-29 18:47
@shendel, can you expand on what you think the bug is? There is to my knowledge nothing in `inpage-provider` that could cause the provider to never be injected as we see here.

**Comment by rekmarks** [comment] 2020-11-29 19:00
To expand on that point, `inpage-provider` exports the function `initProvider`, which initializes the provider and sets it as `window.ethereum`. However, the provider script _injection_ is handled by the React Native `WebView` component, as you can see [here](https://github.com/MetaMask/metamask-mobile/blob/f3a066e/app/components/Views/BrowserTab/index.js/#L1632-L1650).

In reviewing how we handle script injection on Android, it appears that this is due to an outstanding problem with the React Native component. See [this](https://github.com/react-native-webview/react-native-webview/pull/1099#issuecomment-645219546) and later comments for https://github.com/react-native-webview/react-native-webview/pull/1099.

**Comment by shendel** [comment] 2020-11-29 21:20
@rekmarks 
you're wasting my time (again)
i tested
1.0.2 - bug
1.0.4 - bug
1.0.5 - bug
1.0.6 - bug
1.0.7 - bug
I did not find more apk in the public domain (I looked well)
And the bug is not only on android (https://github.com/MetaMask/metamask-mobile/issues/2015) - on iOS too....
If you make a build for developers (and will not force them to eliminate dependencies, sign something there and other heresy that 90% do not need to know), then maybe I'll spend my time again.

I have no desire, no time to engage in spiritualism, to strain my intuition again - I pointed out a possible (99%) problem
If you respected the developers, and made a separate apk for them, then m would not waste your time, and we (third-party developers) would help you

How me debug my app (https://github.com/MetaMask/metamask-mobile/issues/1226) - spend two days of my life to understand that this is not my bug ??

**Comment by shendel** [comment] 2020-11-29 21:34
Last apps - metamask
![image](https://user-images.githubusercontent.com/1880211/100553982-9e7cc580-32a2-11eb-8aa4-089236f3e0e8.png)
OperaMobile
![image](https://user-images.githubusercontent.com/1880211/100553997-c0764800-32a2-11eb-9d54-61738e11a823.png)
TrustWallet
![image](https://user-images.githubusercontent.com/1880211/100554014-f1567d00-32a2-11eb-94a9-bed86e561d2f.png)
CoinBase
![image](https://user-images.githubusercontent.com/1880211/100554029-1814b380-32a3-11eb-8594-4298f39f0f1c.png)

K.O. - Your App (Metamask-mobile) with Your test (dApp)
![image](https://user-images.githubusercontent.com/1880211/100554109-a5f09e80-32a3-11eb-83a2-b84c64e6aeb0.png)
"Click here to install metamask" - Really?? (https://github.com/MetaMask/metamask-mobile/issues/2015)
![image](https://user-images.githubusercontent.com/1880211/100554152-d8020080-32a3-11eb-8a0a-7add3f1157bc.png)

**Comment by shendel** [comment] 2020-11-29 21:36
@rekmarks  bug there - https://github.com/MetaMask/mobile-provider/blob/master/src/content-script/inpage-bundle.js

**Comment by rekmarks** [comment] 2020-11-29 22:11
@shendel, I am sorry that you have had a frustrating experience debugging this issue. We are well aware that the MetaMask Mobile developer experience can leave much to be desired. When we leave something in a state that doesn't meet your — and not to mention our own — expectations, it is because we were forced to prioritize other things. We have talked about releasing an APK in the past, and I will make sure we reevaluate our ability to release one ASAP.

As to your specific problem, whatever is happening in #2015, it is not the same issue as this. Nor is the bug in `inpage-provider` or `mobile-provider`. When I go to to https://swaponline.github.io on MetaMask Mobile on iOS, your connection logic works perfectly.

If you review the links in [my previous comment](https://github.com/MetaMask/metamask-mobile/issues/1975#issuecomment-735439226), you will see that there is an outstanding issue with `react-native-webview` where the browser injection logic fails under certain circumstances on Android. I only discovered that outstanding issue this morning, and shared it immediately here.

I am afraid that there is nothing anyone can do until a fix is merged on `react-native-webview`, or we discover some other workaround. We will update this issue as soon as we learn more.

**Comment by omnat** [comment] 2020-12-01 02:19
#2015 related

**Comment by 101001000** [comment] 2020-12-02 17:25
Same problem with pocophone F1 android 9, 1/5 times it connects, I have to reload it all the time

**Comment by treeder** [comment] 2020-12-08 21:26
@rekmarks I don't think this is specific to React, the same thing happens with Flutter apps too: https://github.com/MetaMask/metamask-mobile/issues/1956

**Comment by rekmarks** [comment] 2020-12-08 21:38
Ah, I see what you mean @treeder, but I'm referring to `react-native-webview`, which is used by the MetaMask Mobile browser.

**Comment by treeder** [comment] 2020-12-09 13:23
Oh I see, thanks for clarifying. 👍

**Comment by shendel** [comment] 2020-12-09 23:39
@rekmarks, 
Any progress or ideas on how to solve this?
Do you understand that waiting for a solution from the developers `react-native-webview` can take infinity time (forever)?
For example - in wallet-connect it was (https://github.com/WalletConnect/walletconnect-monorepo/issues/384), is, and it will probably be a problem ... But its developers just threw a `bone` for other developers and closed issue without fixing this error ...
May be use some hard-fix??
I recently updated the device - on Huawei Y6s (Andoid 9 - updates from November - there is a same problem)

**Comment by andrepimenta** [comment] 2020-12-10 11:21
We have identified the problem, the injection is happening sometimes before the document is loaded which produces an error. We are currently actively working on this and we may have a fix for this soon.

**Closed** 2021-01-18 15:11 UTC
Labels: android, browser, bug, dapp-compatibility, next up

**Comment by open-contracts** [comment] 2021-09-12 01:34
I'm having this problem. The 'ethereum#initialized' event is not triggered on Android inside the metamask app.

```
var provider = null;
var user = null;
var contract = null;

if (window.ethereum) {
  setup();
} else {
  window.addEventListener('ethereum#initialized', setup, {
    once: true,
  });
  setTimeout(setup, 30000); // 30 seconds in which nothing happens on android
}

function setup() {
  $('#network').html("starting connection..."); // this is only displayed after 30 seconds
  const {ethereum} = window;
  ethereum.on('chainChanged', (_chainId) => window.location.reload());
  const newAccounts = ethereum.request({method: 'eth_requestAccounts'});
  provider =  new ethers.providers.Web3Provider(ethereum, 'any');
  provider.getNetwork().then((chain) => {$('#network').html(chain.name);});
  //++ const openProvider = new opencontracts.providers.Web3Provider(provider);
  user = provider.getSigner();
}
```

**Comment by sikandarhayatkhan** [comment] 2021-09-21 20:59
Hello, so I have recently encountered this issue 'ethereu#intialized' event is not triggered by metamask on android, this issue is related to the head section of your app, your head section should be empty e.g if you are using react or HTML your head section only contain title nothing else if you are placing style tag in it remove it then try it. it will work fine.

**Comment by jamesmorgan** [comment] 2021-09-27 16:02
> Hello, so I have recently encountered this issue 'ethereu#intialized' event is not triggered by metamask on android, this issue is related to the head section of your app, your head section should be empty e.g if you are using react or HTML your head section only contain title nothing else if you are placing style tag in it remove it then try it. it will work fine.

Do you me literally nothing? as in you cant load `scripts`, `meta` or `styles` in your head to get MM to work on android?

**Comment by sikandarhayatkhan** [comment] 2021-09-27 18:09
> 
> 
> > Hello, so I have recently encountered this issue 'ethereu#intialized' event is not triggered by metamask on android, this issue is related to the head section of your app, your head section should be empty e.g if you are using react or HTML your head section only contain title nothing else if you are placing style tag in it remove it then try it. it will work fine.
> 
> Do you me literally nothing? as in you cant load `scripts`, `meta` or `styles` in your head to get MM to work on android?

Yeah, this is weird but after spending hours this is the only way that works every time.

**Comment by jamesmorgan** [comment] 2021-09-27 19:26
I tworked. I am using `nuxt` ssr - looking at the source generated we have the following opening element `<head >` instead of `<head>`.

I changed the default template (which appears to leave a trailing space) and it worked ... amazing! No other changes to the head section other than removing this trailing space - main problem was Android Chrome did not work on MM mobile.

So many hours lost looking at this issue thank you very much. @sikandarhayatkhan  🙏🏻

**Comment by andrewrothman** [comment] 2021-10-04 23:22
Hi all. I'm still unable to access `window.ethereum` on Android, even without any `<head>` at all: https://github.com/MetaMask/metamask-mobile/issues/3258

I'd be very grateful if anyone sees anything wrong with my approach or could use any more info. Thanks so much.

**Comment by CryoWebToken** [comment] 2022-03-31 23:25
this still doesnt work! opens metamask fine on pc wont do anything but load on mobile (chrome)

Any ideas??

`import Web3 from "web3";

const initWeb3 = () => {
  return new Promise(async (resolve, reject) => {
    if (window.ethereum) {
      const web3 = new Web3(window.ethereum);
      try {
        await window.ethereum.enable();
        resolve(web3);
      } catch (error) {
        reject(error);
      }
    } else if (window.web3) {
      const web3 = window.web3;
      console.log("Injected web3 detected.");
      resolve(web3);
    } else {
      const provider = new Web3.providers.HttpProvider("http://localhost:9545");
      const web3 = new Web3(provider);
      console.log("No web3 instance injected, using Local web3.");
      resolve(web3);
    }
  });
};

export { initWeb3 };`

**Comment by omnat** [comment] 2022-04-01 04:19
which app version are you on @CryoWebToken

**Comment by JoelStrawn** [comment] 2022-04-24 00:50
I could not access window.ethereum on Android until I added the **.html** ext to the filename.  Hope this helps someone.

**Comment by jahvi** [comment] 2022-04-30 13:02
@jamesmorgan Thanks you don't know how much time I spent trying to figure this out.

What made it worse for me was that this worked perfectly on another app using nuxt but after reading your comment I noticed the <head> tag in my other app didn't have a whitespace even though the app.html template is exactly the same, same nuxt versions as well.

**Comment by Mithila-Panagoda** [comment] 2022-12-21 12:31
this issue is still there has any one found a fix for this

**Comment by majidmadadi** [comment] 2023-01-04 21:54
The issue is sill there with react.

**Comment by devbrooklyn** [comment] 2023-02-07 22:06
I was finally able to fix the issue in my app (after an **entire day** debugging) by removing the following link tags of Google Fonts from the `<head>` section:

```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
```

**Comment by puderty** [comment] 2023-02-17 14:15
> I was finally able to fix the issue in my app (after an **entire day** debugging) by removing the following link tags of Google Fonts from the `<head>` section:
> 
> ```
> <link rel="preconnect" href="https://fonts.googleapis.com">
> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
> ```

Why is it working by remove these?

**Comment by augustovicente** [comment] 2023-08-11 12:08
I am still having this issue

**Comment by Keleigh123** [comment] 2023-12-13 17:33
Hi there, has anyone solved this issue? Ethereum still fails to inject on android more often than it getting injected. Can someone  please help
