### ISSUE TITLE
Wallet Connect – send transaction approval not working on MetaMask after Android version 4.1.1

### ISSUE THREAD

**Issue by jayvs6341** [MetaMask/metamask-mobile#4264] opened 2022-05-10 03:57 UTC
**Describe the bug**
I am working on android application  to connect with MetaMask using WalletConnect protocol.
The connection works fine.
But **eth_sendTransaction** doesn't work.
Metamask is not responding.

I tested several wallets.
eth_sendTransaction is possible for TrustWallet, imToken and others.

Any help would be much appreciated.

Sample Code to check: **https://github.com/pink-room/walletconnectkit-android/tree/main/sample**
Library I am using :- WalletConnectKit : **https://github.com/pink-room/walletconnectkit-android**
**https://github.com/pink-room/walletconnectkit-android/issues/13**

**Screenshots**
Metamask :- V4.2.2 and After ( Not working )
_https://drive.google.com/file/d/1iwbsJSxlbKKE1nirc2VHhVu46FjU-m8N/view?usp=sharing_

Metamask :- V4.1.1 ( Working )
_https://drive.google.com/file/d/1dGs2GIqBEcqc40buZW3Voyy3mq0cMVDO/view?usp=sharing_

**To Reproduce**
Steps to reproduce the behaviour

1. checkout and run [Sample Code](https://github.com/pink-room/walletconnectkit-android/tree/main/sample)
2. Try to connect by clicking the [Connect] button
3. Try to eth_sendTransaction by clicking the [Transaction] button
4. Metamask V4.2.2 and later no response, no behaviour

**Expected behaviour**
Expect to see a send transaction request dialog in MetaMask

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxt M42 5G]
 - OS: [e.g. Android 12]
 - App Version [e.g. 4.2.2] - Settings > About MetaMask

**Comment by gantunesr** [comment] 2022-05-10 16:32
Can you verify this is in v5.1.0 or later?

**Comment by jayvs6341** [comment] 2022-05-11 02:20
> Can you verify this in v5.1.0 or later?

Yes, I tested in the latest build from playstore. It has still the same issue.

**Comment by jayvs6341** [comment] 2022-05-11 02:41
> Can you verify this in v5.1.0 or later?

The latest version on Playstore is V5.0.1 and the send transaction issue is still there.

I downloaded the v5.1.0 from ( https://www.apkmirror.com/apk/consensys/metamask-buy-send-and-swap-crypto/) , but I am getting following issue while adding Polygon Mumbai Net.
![metamask](https://user-images.githubusercontent.com/3488841/167758109-56cc4fc5-34d5-4e7c-a58c-7daa6ca0cd15.jpg)

**Comment by jayvs6341** [comment] 2022-05-11 02:48
> @jayvs6341 can you also please check your Android settings.
> 
> Open Android settings , search 'default' and select "Choose Default apps' > "Choose Default apps" > Opening Links > scroll down to MetaMask and tap it > Supported Web addresses > check if links are selected or "verified/trusted" by default (most importantly metamask.app.link). If they are not, then check them/it
> 
> Thanks.

Thanks for your reply. There is some issue with adding Polygon Testnet on Metamask. I will check with other network and post my response here asap.

**Comment by jayvs6341** [comment] 2022-05-11 04:38
> Can you verify this in v5.1.0 or later?

@gantunesr 
Sorry to say, but it is not not working.

**Comment by jayvs6341** [comment] 2022-05-11 04:39
> @jayvs6341 can you also please check your Android settings.
> 
> Open Android settings , search 'default' and select "Choose Default apps' > "Choose Default apps" > Opening Links > scroll down to MetaMask and tap it > Supported Web addresses > check if links are selected or "verified/trusted" by default (most importantly metamask.app.link). If they are not, then check them/it
> 
> Thanks.

@andreahaku 
Sorry to say, but this solution also dont work. Still the transaction dialog dont appear.

**Comment by jayvs6341** [comment] 2022-05-13 11:09
@gantunesr @andreahaku 

Hello guys, this is gentle remainder about the issue i am still facing. I have following points you to be focused.

1. Metamask v4.1.1 is working properly on transaction request approval thru wallet connect
2. Transaction request approval is a critical functionality for our app to connect to metamask thru wallet connect
3. Trust wallet is functioning normal for transaction request approval thru wallet connect

Hope you guys have a great weekend.

**Comment by jayvs6341** [comment] 2022-05-20 10:14
@gantunesr @andreahaku 
Hello Gustavo, Andrea
This issue is blocking our dApp development to initate the transaction approval request from our dApp to metamask wallet.
It's working on v4.1.1 but it did not work on v4.2.2 to v5.1.0
Is there any update that this issue will have resolution soon so that we can count on metamask solution for our wallet connect?

**Comment by jayvs6341** [comment] 2022-05-24 07:47
@gantunesr @andreahaku 

I tested v5.1.1 , still has the same issue.

Transaction alert is not coming up.

**Comment by gantunesr** [comment] 2022-06-08 19:17
Hey @jayvs6341, we're currently researching the root cause. Thanks for your patience.

**Comment by afterlifehy** [comment] 2022-06-09 15:14
@gantunesr I have the same problem，personal_sign doesn't work. Metamask is not responding.

**Comment by jayvs6341** [comment] 2022-06-10 09:40
> Hey @jayvs6341, we're currently researching the root cause. Thanks for your patience.

Hey @gantunesr 
Thanks for your response.

Looking forward for your revert.

**Comment by Basavaraj367** [comment] 2022-06-20 07:34
> @gantunesr I have the same problem，personal_sign doesn't work. Metamask is not responding.

hi have found solution for this if u got solution please share with me.

**Comment by afterlifehy** [comment] 2022-06-20 15:09
> > @gantunesr I have the same problem，personal_sign doesn't work. Metamask is not responding.
> 
> hi have found solution for this if u got solution please share with me.

I haven't found solution, so I have to wait for matemask to update

**Comment by php4fan** [comment] 2022-07-10 10:45
I get the same issue when sending a transaction request from a webpage using JavaScript via WalletConnect.

Sometimes it works. Sometimes, MetaMask shows up for a fraction of a second and immediately closes, without prompting for transaction confirmation. Sometimes MetaMask doesn't even pop up at all.

This is fucking pathetic.

**Comment by vincentzmbizi** [comment] 2022-07-25 06:34
@tommasini @gantunesr 
I saw tommasini addressing to improve transaction editor component code #4654.  Will this issue be resolved in July release?

We tested latest android release V5.3.0 and the wallet transaction approval is still not working.

It has not been working since android release V4.1.1 in March. Please advise urgently.

**Comment by vincentzmbizi** [comment] 2022-08-03 20:14
@gantunesr 
V5.4.0 was released. Is this issue, #4264 fixed?

**Comment by php4fan** [comment] 2022-08-03 20:56
Nope, still not fixed.
It can easily be tested here: https://opentarget.org/test/stupid/mm/wc/

**Comment by php4fan** [comment] 2022-08-03 21:20
When I observe this connecting via WalletConnect from a webpage, this seems to happen systematically when one of these conditions are met:
a. the current account doesn't have enough funds for the transaction, or
b. the transaction is going to fail with an error thorwn from the contract

(which I think may be two facets of the same case, because in case 'b' gas estimation will fail and the transaction will be estimated as extremely expensive, so you will almost certainly not have enough funds if you are a normal person)

When I test it with enough funds and with a transaction that is not going to fail, it works.

Can anybody that is facing this from android apps confirm the same is true for you? @afterlifehy @jayvs6341 

If you can confirm that, I think this is the same as #4646. After all, isn't MetaMask's end of the WalletConnect protocol exactly the same, whether at the other end is a native app or a javascript script in a browser?

**Comment by vincentzmbizi** [comment] 2022-08-04 10:46
@gantunesr @tommasini 
#4264 is high priority bug and there is no update from MetaMask.  This should not be the right response from ConsenSys.
Any visibility you can share with the community?

**Comment by php4fan** [comment] 2022-08-04 13:10
> from ConsenSys.

Wow, so there's an actual corporation behind MetaMask!? I thought it was developed by a handful of enthusiasts in their very limited spare time. That's the kind of scenario form which one could expect this level of quality.

**Comment by vincentzmbizi** [comment] 2022-08-04 13:54
MetaMask is from a giant company, ConsenSys. I have a very high expectation and respect of ConsenSys. WE need to raise the bar!

**Comment by php4fan** [comment] 2022-08-04 14:20
> MetaMask is from a giant company

Well, then there is no excuse, this is just pathetic. It's a half-baked product that can't be relied upon for a hobby project, let alone trusted with real money; it's totally unusable because of a plethora of bugs (in 10 minutes of use you stumble upon more bugs than you can report in one hour) and it's been so for at least months (that's how long I've used it, it's probably way longer or forever), and they haven't done anything about it, except, every time a new release comes out, ask bug reporters if the issue is still there.

I always wondered how on earth this managed to become the most popular wallet app and extension. Now I guess I get it. If it's a giant company, maybe at the beginning they did put resources on it, and perhaps in its early stage for the limited functionality that it had it worked decently, either that or it had nothing to compete with. Then they just let it rot.

If they're not willing to put resources into maintaining it, they should officially abandon it, and pull it out from app and extension stores so they don't actively harm users.

> I have a very high expectation and respect of ConsenSys

Well I certainly don't now.

> WE need to raise the bar!

We need a bar.

**Comment by vincentzmbizi** [comment] 2022-08-04 14:29
Do you test any other wallet better than MetaMask in wallet connect?

**Comment by php4fan** [comment] 2022-08-04 14:38
> Do you test any other wallet better than MetaMask in wallet connect?

I briefly tested TrustWallet, it's mostly garbage but it doesn't have this specific issue.

**Comment by vincentzmbizi** [comment] 2022-08-04 14:42
which wallet is not garbage at the moment?

**Comment by vincentzmbizi** [comment] 2022-08-04 14:43
Did you test coinbase wallet with walletlink (now called coinbase SDK) whether the transaction approval is working?

**Comment by andreahaku** [comment] 2022-08-04 14:51
Can you please do me a favour and go to [https://example.walletconnect.org/](https://example.walletconnect.org/) and try connecting to MM mobile and try an 'eth_sendTransaction' with the wallet on ETH mainnet. If it works, then please do using another network.

I tested and it works on Android (11 and 12) and iOS.

If possible using the latest version of the app (5.4.0) available on stores.

Wait for your tests. Thanks.

**Comment by php4fan** [comment] 2022-08-04 14:52
> I tested and it works on Android (11 and 12) and iOS.

Did you test with an account that doesn't have enough funds? Did you test with a transaction that is going to fail (throwing an error in the contract)?

**Comment by php4fan** [comment] 2022-08-04 14:54
Also did you test on the BSC blockchain?

**Comment by vincentzmbizi** [comment] 2022-08-04 15:25
@php4fan   MM v4.1.1 is working on transaction approval.  Can you use v4.1.1 to test your app whether it's OK. 
 The subsequent release from v4.2.2 to latest v5.4.0 is not working: https://www.apkmirror.com/apk/metamask-web3-wallet/metamask-buy-send-and-swap-crypto/metamask-buy-send-and-swap-crypto-4-1-1-release/

**Comment by jayvs6341** [comment] 2022-08-04 15:26
@andreahaku

Using WalletConnect in android, when we send a transaction, it doesn't show any popup to approve or reject.

This feature was working perfectly fine on the 4.1.1 version of metamask.

Can you please compare the code of newer versions with 4.1.1.

This is not a new feature, this is just a bug that was already working in older versions.

You need to just compare the codebase.

Please do the needful.

**Comment by php4fan** [comment] 2022-08-04 15:28
@vincentzmbizi 

> which wallet is not garbage at the moment?

None that I've been able to find (and I tried quite a few).

My main complaint with all the mobile app wallets that I tried is that they don't allow you to manually initiate and make a transaction to a smart contract with hex data (or data in any form). That is, you have an app that is capable of making any arbitrary transaction to any arbitrary address with any arbitrary data, but only if it gets requested to do so via an API or protocol (such as WalletConnect or scanning a QR code), not manually by entering the data. That's just idiotic. That would be like an email client capable of clicking on a link that sends a pre-built message, but without a UI to compose a message. Sometimes the same vendor makes a browser extension or desktop/web application that does allow that, and yet they deem it unnecessary to put the same feature into their mobile app.
MetaMask is the only mobile app that has this feature (in this they were pioneers!), but it has been broken for years and they haven't fixed it yet.

Besides that they are all plagued with countless bugs making them unusable just like MetaMask, maybe a bit more, maybe a bit less.
I also discarded right away those which don't support the BSC (or allow you to add an arbitrary network).
I also couldn't find any that handled EIP-681 links (now I don't remember if they work in MM in a very narrow subset of cases, like with no data, but definitely not in the general case).

> Did you test coinbase wallet 

no. I don't remember which basic feature it lacked that I needed that made me discard it right away.

**Comment by vincentzmbizi** [comment] 2022-08-04 15:33
@php4fan can you check MM V4.1.1 whether it's working on transaction approval in your app.  This will help Andrea to understand our issue

**Comment by php4fan** [comment] 2022-08-04 15:34
@vincentzmbizi 
> MM v4.1.1 is working on transaction approval. 

That's interesting. That kind of confirms my theory that there was a time when MM was at least usable, perhaps even great, which explains how it could reach its popularity. Then the decline came afterwards.

> Can you use v4.1.1 to test your app whether it's OK

Sorry I don't have the time for that. If it worked for you I'm pretty sure I'd get the same result.

> This will help Andrea to understand our issue

Yeah, I think Andrea should try that.

**Comment by vincentzmbizi** [comment] 2022-08-04 15:36
@php4fan You're quite knowledgeable and ConsenSys & MetaMask should give you a developer award.  Hope that MetaMask will make a difference!

**Comment by php4fan** [comment] 2022-08-04 15:55
@jayvs6341 
> Using WalletConnect in android, when we send a transaction, it doesn't show any popup to approve or reject.

To me that happens when and only when I don't have enough funds for the transaction or the transaction is going to fail.
Is that the case for you as well, or does it happen to you always, even with transactions that are going to succeed and for which you have enough funds?

**Comment by vincentzmbizi** [comment] 2022-08-04 16:53
> > MetaMask is from a giant company
> 
> Well, then there is no excuse, this is just pathetic. It's a half-baked product that can't be relied upon for a hobby project, let alone trusted with real money; it's totally unusable because of a plethora of bugs (in 10 minutes of use you stumble upon more bugs than you can report in one hour) and it's been so for at least months (that's how long I've used it, it's probably way longer or forever), and they haven't done anything about it, except, every time a new release comes out, ask bug reporters if the issue is still there.
> 
> I always wondered how on earth this managed to become the most popular wallet app and extension. If it's a giant company, I guess maybe at the beginning they did put real resources on it, and perhaps in its early stage for the limited functionality that it had it worked decently, either that or it had nothing to compete with. Then they just let it rot thinking it would maintain itself, or that the community would for free.
> 
> If they're not willing to put resources into maintaining it, they should officially abandon it, and pull it out from app and extension stores so they don't actively harm users.
> 
> > I have a very high expectation and respect of ConsenSys
> 
> Well I certainly don't now.
> 
> > WE need to raise the bar!
> 
> We need a bar.

@gantunesr @andreahaku 
I don't think this is what Joseph Lubin, Founder and CEO of ConsenSys expects to see the feedback from the android community. Is MetaMask serious in android mobile space?  This requires a bold action and commitment from ConsenSys and MetaMask team. Never give up.  We will win together for the android mobile space!

**Comment by php4fan** [comment] 2022-08-04 17:12
> Is MetaMask serious in android mobile space?

MetaMask is not remotely serious in general, it's not just android. The Chrome browser extension is slightly less pathetic, but the effort they put into fixing issue is the same, i.e. non-existent.

> We will win together

I don't think we stand a chance. It's not up to us. If they don't give a **** about the project, it will die. The only hope would be they decide quickly: either get working on it, or shut it down for good. But that doesn't seem likely either. If they just raised millions (and haven't moved a finger in 4 months), this is probably going to be a slow agony. If I could bet money on this, I'd bet the cryptocurrency bubble will burst and the world will stop giving a damn about blockchains way before MetaMask makes any significant progress.

**Comment by vincentzmbizi** [comment] 2022-08-04 17:22
Joseph Lubin is Co-Founder of the Ethereum Project and the Founder of ConsenSys, with $450m funding to revamp MetaMask. I don't see any reason or excuse not to make MetaMask a revolution change and a success.
I will observe for another month to see how it goes.

**Comment by jayvs6341** [comment] 2022-08-05 04:36
> @jayvs6341
> 
> > Using WalletConnect in android, when we send a transaction, it doesn't show any popup to approve or reject.
> 
> To me that happens when and only when I don't have enough funds for the transaction or the transaction is going to fail. Is that the case for you as well, or does it happen to you always, even with transactions that are going to succeed and for which you have enough funds?

@php4fan 
This happens me all the time.

**Comment by andreahaku** [comment] 2022-08-05 12:46
@jayvs6341 @php4fan @vincentzmbizi if you are here to help debug and fix bugs you are welcome and we thank you for that. I'd suggest keeping all the other arguments out of Github issue reporting. Thanks. I think we are all here to make MetaMask a better product and user experience. I am for sure. So, please, keep the 'noise' out of Github. It'd be very beneficial for developers and users. Thanks again.

We are working on replicating and fixing the issue. We are aware of issues related to deep link switching networks and we already have a fix for that which will be released in one of the coming updates. This is the reason why I'm asking you to test on ETH Mainnet for now. To narrow down and understand if it's the deep link mechanism that is not working for you or if it is something beyond that.

From what most of you are reporting it seems that deep links work but the bug seems to be after that.

@jayvs6341 can you please confirm that you are using the latest version of the app (5.4.0) and you are testing on ETH Mainnet? Also are you able to connect WC to MetaMask first? Is the issue after the connection or WC connection confirmation modal doesn't appear? Also, are you testing using [https://example.walletconnect.org/](https://example.walletconnect.org/)? Thanks a lot.

Thanks again.

**Comment by jayvs6341** [comment] 2022-08-05 15:08
> @jayvs6341 @php4fan @vincentzmbizi if you are here to help debug and fix bugs you are welcome and we thank you for that. I'd suggest keeping all the other arguments out of Github issue reporting. Thanks. I think we are all here to make MetaMask a better product and user experience. I am for sure. So, please, keep the 'noise' out of Github. It'd be very beneficial for developers and users. Thanks again.
> 
> We are working on replicating and fixing the issue. We are aware of issues related to deep link switching networks and we already have a fix for that which will be released in one of the coming updates. This is the reason why I'm asking you to test on ETH Mainnet for now. To narrow down and understand if it's the deep link mechanism that is not working for you or if it is something beyond that.
> 
> From what most of you are reporting it seems that deep links work but the bug seems to be after that.
> 
> @jayvs6341 can you please confirm that you are using the latest version of the app (5.4.0) and you are testing on ETH Mainnet? Also are you able to connect WC to MetaMask first? Is the issue after the connection or WC connection confirmation modal doesn't appear? Also, are you testing using https://example.walletconnect.org/? Thanks a lot.
> 
> Thanks again.

@andreahaku 
Yes, I am using the latest 5.4.0 version.
I tested on Mainnet as well as Polygon mumbai network.

I am able to connect to the metamask first and getting the wallet address.

Yes, when I try to execute transaction, the confirmation dialog don't appear.

I am testing in Android application using following library.

**https://github.com/pink-room/walletconnectkit-android**

**Comment by andreahaku** [comment] 2022-08-05 17:51
> @andreahaku Yes, I am using the latest 5.4.0 version. I tested on Mainnet as well as Polygon mumbai network.
> 
> I am able to connect to the metamask first and getting the wallet address.
> 
> Yes, when I try to execute transaction, the confirmation dialog don't appear.
> 
> I am testing in Android application using following library.
> 
> **https://github.com/pink-room/walletconnectkit-android**

Thanks this is really helpful. Did you try using https://example.walletconnect.org/ connect and then 'eth_sendTransaction'? Can you do it so that I may understand if the problem is with the 'eth_sendTransaction' method itself or maybe something wrong/different in the library you are using. Thanks again.

**Comment by jayvs6341** [comment] 2022-08-08 11:40
> > @andreahaku Yes, I am using the latest 5.4.0 version. I tested on Mainnet as well as Polygon mumbai network.
> > I am able to connect to the metamask first and getting the wallet address.
> > Yes, when I try to execute transaction, the confirmation dialog don't appear.
> > I am testing in Android application using following library.
> > **https://github.com/pink-room/walletconnectkit-android**
> 
> Thanks this is really helpful. Did you try using https://example.walletconnect.org/ connect and then 'eth_sendTransaction'? What I need to know is if you can see the confirmation modal with the info about the transaction. Can you do it so that I may understand if the problem is with the 'eth_sendTransaction' method itself or maybe something wrong/different in the library you are using. Thanks again.

@andreahaku

**Comment by jayvs6341** [comment] 2022-08-08 11:42
> > @andreahaku Yes, I am using the latest 5.4.0 version. I tested on Mainnet as well as Polygon mumbai network.
> > I am able to connect to the metamask first and getting the wallet address.
> > Yes, when I try to execute transaction, the confirmation dialog don't appear.
> > I am testing in Android application using following library.
> > **https://github.com/pink-room/walletconnectkit-android**
> 
> Thanks this is really helpful. Did you try using https://example.walletconnect.org/ connect and then 'eth_sendTransaction'? What I need to know is if you can see the confirmation modal with the info about the transaction. Can you do it so that I may understand if the problem is with the 'eth_sendTransaction' method itself or maybe something wrong/different in the library you are using. Thanks again.

@andreahaku 
Thanks for your reply.

This link , "https://example.walletconnect.org/" is a web application right. And I am using the walletconnect android sdk.

In the library, "wss://bridge.aktionariat.com:8887" this is the bridge url I have currently.

Can you please explain me how your specified URL I can use in the android side.

**Comment by andreahaku** [comment] 2022-08-08 12:03
> @andreahaku Thanks for your reply.
> 
> This link , "https://example.walletconnect.org/" is a web application right. And I am using the walletconnect android sdk.
> 
> In the library, "wss://bridge.aktionariat.com:8887" this is the bridge url I have currently.
> 
> Can you please explain me how your specified URL I can use in the android side.

Yes, this is a WC test web app. You should be able to open it on a mobile browser (Chrome) on the device where you also have MM mobile installed. Try connecting first and then use the button to test an 'eth_sendTransaction'. This is for me to understand where the problem lies. If it's in the deep linking phase (which I don't think at that point), or in the way the 'eth_sendTransaction' is issued/parsed/handled.

Thanks again for your support in debugging this thing.

**Comment by jayvs6341** [comment] 2022-08-08 12:17
> > @andreahaku Thanks for your reply.
> > This link , "https://example.walletconnect.org/" is a web application right. And I am using the walletconnect android sdk.
> > In the library, "wss://bridge.aktionariat.com:8887" this is the bridge url I have currently.
> > Can you please explain me how your specified URL I can use in the android side.
> 
> Yes, this is a WC test web app. You should be able to open it on a mobile browser (Chrome) on the device where you also have MM mobile installed. Try connecting first and then use the button to test an 'eth_sendTransaction'. This is for me to understand where the problem lies. If it's in the deep linking phase (which I don't think at that point), or in the way the 'eth_sendTransaction' is issued/parsed/handled.
> 
> Thanks again for your support in debugging this thing.

@andreahaku 

I tested the link as per your suggestion.

It can connect to my MM and get the wallet address, but when I click on eth_sendTransaction , nothing happens. I tested couple of times.

Here is a video recording link.

Can you please check once.

**https://drive.google.com/file/d/1j0jdpFRiB89wmgxzjuQT_6jFctwCCQZ7/view?usp=sharing**

**Comment by jayvs6341** [comment] 2022-08-08 13:15
@andreahaku 

I have tested the web link on MM v4.1.1

You can see in the video, the Confirmation dialog popup on MM when we call the eth_transaction button.

**https://drive.google.com/file/d/1__gdkXnXOLqfoP1QorYuC-dh1S-q46Gd/view?usp=sharing**

**Comment by jayvs6341** [comment] 2022-08-08 13:24
@andreahaku 

I have one suggestion.

As the transaction approval is working on MM v4.1.1, can you please compare the code changes from V4.1.1 to newer versions.

I think, this way, you can figure it out the root cause.

**Comment by andreahaku** [comment] 2022-08-08 15:16
> I tested the link as per your suggestion.
> 
> It can connect to my MM and get the wallet address, but when I click on eth_sendTransaction , nothing happens. I tested couple of times.
> 
> Here is a video recording link.
> 
> Can you please check once.
> 
> **https://drive.google.com/file/d/1j0jdpFRiB89wmgxzjuQT_6jFctwCCQZ7/view?usp=sharing**

It doesn't even open the app! That's the first time I have seen something like this. Yes, we will compare the two versions.
Thanks @jayvs6341

**Comment by php4fan** [comment] 2022-08-08 19:16
@andreahaku may I suggest (or remind) you to look at https://github.com/MetaMask/metamask-mobile/issues/4646 if you haven't already? They may or may not be the same issues but they look very related; it seems to me that 4646 may be easier for you to reproduce, and that perhaps could lead you to get more insight about both.

**Comment by andreahaku** [comment] 2022-08-09 14:05
> @andreahaku
> 
> I have one suggestion.
> 
> As the transaction approval is working on MM v4.1.1, can you please compare the code changes from V4.1.1 to newer versions.
> 
> I think, this way, you can figure it out the root cause.

With version 4.2 we did refactor both WC and deep links managers. We also updated related modules etc. So I think that probably something in the configuration update is causing the issue. Now the thing is that this is only happening on a certain setup. And with the devices that I have (and can simulate) I'm not able to replicate your specific issue.

But I can tell you that I'm working on a test version with potential fixes that I'll eventually ask you to test privately.

In the meantime, I'd be very grateful if you could test the same thing on another Android (better id 12 as is the version with potentially more issues) device the very same test you did using the WC web example web app. Thanks a lot!

**Comment by php4fan** [comment] 2022-08-09 14:19
> But I can tell you that I'm working on a test version with potential fixes that I'll eventually ask you to test privately.

Can I test that too when it's ready?

**Comment by jayvs6341** [comment] 2022-08-10 04:36
> > @andreahaku
> > I have one suggestion.
> > As the transaction approval is working on MM v4.1.1, can you please compare the code changes from V4.1.1 to newer versions.
> > I think, this way, you can figure it out the root cause.
> 
> With version 4.2 we did refactor both WC and deep links managers. We also updated related modules etc. So I think that probably something in the configuration update is causing the issue. Now the thing is that this is only happening on a certain setup. And with the devices that I have (and can simulate) I'm not able to replicate your specific issue.
> 
> But I can tell you that I'm working on a test version with potential fixes that I'll eventually ask you to test privately.
> 
> In the meantime, I'd be very grateful if you could test the same thing on another Android (better id 12 as is the version with potentially more issues) device the very same test you did using the WC web example web app. Thanks a lot!

@andreahaku 

That's amazing. Thanks for your efforts.

I tested the issues on 3 devices.

Android -> 12
Android  -> 9
Android -> 11

But this issue I am facing on all devices.

**Comment by andreahaku** [comment] 2022-08-10 16:44
@jayvs6341 @php4fan thanks again and will try to keep you updated on my development. In the meanwhile are you able to provide me with the "user agent" used to call the deep link? I just had a meeting with Branch.io and they made me realise that this is important info to understand the "strange" behaviour of deep links in your cases. Thanks!

**Comment by jayvs6341** [comment] 2022-08-11 02:43
> @jayvs6341 @php4fan thanks again and will try to keep you updated on my development. In the meanwhile are you able to provide me with the "user agent" used to call the deep link? I just had a meeting with Branch.io and they made me realise that this is important info to understand the "strange" behaviour of deep links in your cases. Thanks!

@andreahaku 
Thanks for the update.

We are using following library base on WalletConnect.

**https://github.com/pink-room/walletconnectkit-android**

I think the url for deeplink is,

**wss://bridge.aktionariat.com:8887**

LEt me know, if you required anything from myside.

**Comment by jayvs6341** [comment] 2022-08-23 13:21
@andreahaku 

Hello,

**Comment by jayvs6341** [comment] 2022-08-23 13:22
@andreahaku 

Hello,
Hope you guys doing great.

Any update for the issue ?

We saw 5.5.0 release on Aug 10. Do we expect our fix will be included on next release?

**Comment by andreahaku** [comment] 2022-08-23 15:39
> @andreahaku
> 
> Hello, Hope you guys doing great.
> 
> Any update for the issue ?
> 
> We saw 5.5.0 release on Aug 10. Do we expect our fix will be included on next release?

Hi @jayvs6341, we are still working on a fix as we are taking the occasion to refactor a few things together all related to WalletConnect and deep links. So it'll take a little more time than we initially thought. Thanks for your patience.

**Comment by jayvs6341** [comment] 2022-08-24 03:36
@andreahaku 
Ok got it.

Thanks for the update.

**Comment by jayvs6341** [comment] 2022-09-07 06:07
Hey @andreahaku 

Hope you are doing well.

Can you please let us know the status and also when this issue can be sorted out.

We cannot wait for indefinite time.

Hope you understand the situation.

**Comment by andreahaku** [comment] 2022-09-07 10:07
@jayvs6341 I'm working on it and doing some tests. I hope to be able to have something for external tests later next week as we are planning to also have some feedback from Branch.io on how to improve the reliability of deep links based on our setup.

Totally understand you and I thank you for your patience.

**Comment by jayvs6341** [comment] 2022-09-07 11:20
@andreahaku 

Ok, thanks for the update.

**Comment by tommasini** [comment] 2022-09-14 18:03
@jayvs6341 The eth_sendTransaction from an android mobile app It's fixed on release 5.6.1. I will close this issue, but if it still happens to you please feel free to open a new one or comment on this one to reopen it!

**Comment by jayvs6341** [comment] 2022-09-15 11:48
@tommasini 
Where you released the 5.6.1 version ?

I dont find it on Google Play store or apkmirror.

**Comment by tommasini** [comment] 2022-09-15 13:22
My bad @jayvs6341 it's uploading to the stores, soon it ends I will comment here

**Comment by gantunesr** [comment] 2022-09-15 13:37
@jayvs6341 you can access the APK in our release notes. The release is still rolling out in the meanwhile.

https://github.com/MetaMask/metamask-mobile/releases/tag/v5.6.1

**Comment by jayvs6341** [comment] 2022-09-15 17:00
@gantunesr 

Thanks , I will check it.

**Comment by php4fan** [comment] 2022-09-17 12:35
Nope, not fixed.
At least, #4646 is not fixed (sending transaction through WalletConnect from a web page), which I think is the same underlying issue.

**Comment by jayvs6341** [comment] 2022-09-20 13:07
@andreahaku @gantunesr @tommasini 

I verified it with some use-cases. It is working perfectly.

Thank you so much guys for your handwork and efforts.

Much appriciated.

I am still going through some of the other test cases.

**Comment by php4fan** [comment] 2022-09-20 13:22
Wow, then they must be two different issues. Please do look into 4646 which has been completely ignored this whole time and is equally serious.

**Comment by php4fan** [comment] 2022-09-20 13:53
@jayvs6341 BTW can you confirm that _failing_ transactions, and attempts to do transactions with insufficient funds,  also work for you as expected, particularly on the BSC chain?

**Comment by gantunesr** [comment] 2022-10-10 17:32
Hey everyone, I'll close this issue since the main problem is solved. @php4fan we're already working on the solution for your issue and we'll follow up in https://github.com/MetaMask/metamask-mobile/issues/4646. Thanks!

**Closed by gantunesr** 2022-10-10 17:32 UTC
Labels: type-bug, Sev2-normal, technical research, Priority - High, WalletConnect, stability-team
