### ISSUE TITLE
v4.4.0 RC: Swaps: Not all swap transactions are shown on Polygon Mainnet

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#4009] opened 2022-04-01 00:05 UTC
*Discovered during iOS regression; needs investigation on whether it occurs in Android regression*

Only the most recent swap transaction is showing for wallet that has done multiple swaps along with an old one with our test wallet.

- Given I have MATIC funds in my wallet on the Polygon Mainnet
- When I make three swap transactions from MATIC => WMATIC
- Then three swap transactions should display in Transactions screen

In the recording you will see three swaps occur one after the other but you will only see the most recent swap transaction and a previous swap transaction.  Expected to see three transactions for the three swaps.

Video: https://recordit.co/mWPwbBsTAZ

**Comment by mobularay** [comment] 2022-04-01 16:12
@chrisleewilcox , in discussion with @andrepimenta 

- does this happen in prod already? if so, then we need to prioritize this for next release
- is this a new bug not in prod? if so, this is considered a release blocker
- additional info to know: do all the submitted transactions show up on PolygonScan?

**Comment by wachunei** [comment] 2022-04-01 16:22
is this a duplicate of https://github.com/MetaMask/metamask-mobile/issues/3820 ?

**Closed** 2022-04-04 04:05 UTC
Labels: needs-dev-review
