### ISSUE TITLE
.xyz Domain in MM Browser Showing “EnsIpfsResolver” Error if not with Ethereum Main Network.

### ISSUE THREAD

**Issue by lalawila** [MetaMask/metamask-mobile#4252] opened 2022-05-08 14:04 UTC
relation: [https://community.metamask.io/t/xyz-domain-in-mm-browser-showing-ensipfsresolver-error/17928](relation question)

I have a .xyz website that fail to load in metamask if not with Ethereum Main Network.
It will be ok if open with Ethereum Main Network first then switch network to polygon.

Same scene is alright in desktop browser with metamask extension.

Action recording:  [https://www.youtube.com/shorts/7m7h981zwxM](https://www.youtube.com/shorts/7m7h981zwxM)

operating system: IOS 15.4.1
MetaMask version: v5.0.1(877)

**Comment by jhxyz** [comment] 2023-03-01 02:23
Hi! Was this issue fixed? It looked like it was fixed in the below merge but the issue isn't closed. @tommasini? 🙏 https://github.com/MetaMask/metamask-mobile/pull/4173

**Comment by tommasini** [comment] 2023-03-01 03:29
@jhxyz Thanks for coming back here!
Yes, this was fixed on that PR, I will close this issue if some issue appear, please open a new one!

**Closed by tommasini** 2023-03-01 03:29 UTC
Labels: type-bug
