### ISSUE TITLE
max token (UNI) transfer crashing the app

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2329] opened 2021-03-03 02:24 UTC
Repro steps:
- go to token (UNI)
- tap Swap button from token view
- 'max token' (there is plenty UNI)
- app crashes

Could reproduce consistently 3-4 times. happening both when tapping 'Swap' from within the token view, and from main wallet view. 
Only reproducible for me for UNI
cc @ibrahimtaveras00 saw something like this?

iOS - iPhone 8+
version - 587

**Comment by wachunei** [comment] 2021-03-03 02:59
I can't reproduce:

https://user-images.githubusercontent.com/1024246/109745862-3c8a6f80-7bb3-11eb-829e-00d280befacf.MP4

**Comment by ibrahimtaveras00** [comment] 2021-03-03 17:44
I have not seen anything similar to that, nor could I reproduce as well; seen here = http://recordit.co/J6LrQETsGF

**Comment by wachunei** [comment] 2021-03-09 13:18
Reproduced and fixed in https://github.com/MetaMask/metamask-mobile/pull/2361

**Closed** 2021-03-16 17:51 UTC
Labels: QA Passed, fixed, swaps
