### ISSUE TITLE
BNB: "Submitted" transactions are not updating to "Completed" when blockchain shows success

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#4893] opened 2022-08-22 21:35 UTC
Updated Description: "Submitted" transactions are not updating to "Confirmed" when blockchain shows success on block explorer.

"Submitted" transactions are not updating to "Completed" when blockchain shows success on Binance mainnet.  When transaction is in this stated the "Speed Up" and "Cancel" will always show popup for retry but retry fails because transactions is already completed.

https://recordit.co/PrmH6nkGiB

**Comment by chrisleewilcox** [comment] 2022-08-22 21:38
Related issue: https://app.zenhub.com/workspaces/mobile-qa-board-6249fe41701a8f001195ca64/issues/metamask/metamask-mobile/4804

**Comment by blackdevelopa** [comment] 2022-09-27 14:54
I am unable to reproduce this for days now and will like to move it back to our backlog for whenever it happens again.
I am certain the challenge isn't with the code (mobile or controller), but with the RPCProvider (https://bsc-dataseed1.binance.org) we use for BSC (not Infura parsed). There's little or nothing we can do at this time to fix this and from observing the logs, it updates itself after sometime.
What really happens? We use the eth_getTransactionByHash method in our controllers code to check when a transaction has been added to a block (that is confirmed). Ideally, it returns the block number alongside other important details. For this bug (that is random), it doesn't return the block number even though transaction is now confirmed. Since the controller code doesn't get the block number, the mobile app doesn't.

@chris.wilcox can we close this PR until it happens again?

**Comment by chrisleewilcox** [comment] 2022-10-11 20:41
Was not able to reproduce with new refactor changes from [4835](https://github.com/MetaMask/metamask-mobile/pull/4835)

**Closed** 2022-10-11 20:42 UTC
Labels: QA in Progress, Sev2-normal, Mobile QA board, transaction safety team
