### ISSUE TITLE
Error when logging in. 

### ISSUE THREAD

**Issue by Darkdragon2682** [MetaMask/metamask-mobile#1496] opened 2020-04-18 01:03 UTC
After sending ETH, it asks to create a password. After creating the password, it crashed before giving the seed phrase. When I use the created password, it gives the error in the screenshot. It happens every time. The password works because it gives invalid password error when I give the wrong password. 

![Screenshot_20200417-205034_MetaMask](https://user-images.githubusercontent.com/63887313/79624276-a8283300-80ee-11ea-815f-5e2489428818.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung s7 Active
 - OS:
 - Version: Latest 

-------------------------------------------------------------

**Comment by Darkdragon2682** [comment] 2020-04-18 19:49
Update... It seems to connect when the fingerprint option is on.

**Comment by omnat** [comment] 2020-04-28 01:05
Thanks for the update! Can you login with your password now too?

**Comment by georgeandrei** [comment] 2020-05-18 09:25
The same issue on infinix 05 brand telephone

**Comment by omnat** [comment] 2020-05-21 00:29
We aren't able to reproduce this. Can you share any details that can help with reproduction?

**Comment by rdymac** [comment] 2020-06-02 11:55
The error message shown in the screenshot look exactly the same as in #1607

`Error: Unknown error: Could not encrypt value for service com.metamask`

@Darkdragon2682 @georgeandrei could you please try following @ibrahimtaveras00 instructions in this other issue https://github.com/MetaMask/metamask-mobile/issues/1607#issuecomment-637064790 to check if this is the same case of _face recognition_ or _Irises_ features being enabled?

**Comment by omnat** [comment] 2020-12-05 01:14
Related #1811

**Comment by omnat** [comment] 2020-12-07 19:51
couldn't reproduce.

next steps:
check Sentry and support team if this has come up

**Comment by andrepimenta** [comment] 2021-08-17 17:03
This error should be fixed in newer releases. Please open another issue if the error still persists.

**Closed by andrepimenta** 2021-08-17 17:03 UTC
Labels: bug, needs-reproduction
