### ISSUE TITLE
Invalid amount error when initiating ERC20 token transfer from dApp

### ISSUE THREAD

**Issue by jahvi** [MetaMask/metamask-mobile#3999] opened 2022-03-31 13:38 UTC
**Describe the bug**
I'm getting an "Invalid amount" error when trying to initiate an ERC20 token transfer from my dapp. The "Confirm" button is then disabled and I can't continue to send the transaction.

This works fine on chrome using the browser extension, transfers also work in desktop and mobile if I initiate them from MM using the "Assets" tab.

**Screenshots**
![ss](https://user-images.githubusercontent.com/661330/161065835-5fb24850-d36d-4907-97e7-e20ed0335896.jpeg)

**To Reproduce**
I'm using the following code to initiate the transfer, using ethers.js v5.5.

```javascript
import { ethers } from "ethers";

const contract = new ethers.Contract("CONTRACT_ADDRESS", ABI, signer);

await contract.transfer(
 "ADDRESS",
  ethers.utils.parseEther("1")
);

...
```

This is a sample hex data for a transaction that shows as "invalid amount", if you try to simulate it on tenderly you'll see it goes through ok so there isn't any problems with the actual tx data:

Contract (rinkeby): `0x4d0154255b66d44d273b06a1e54281c541aeb61d`
Data:
```
0xa9059cbb0000000000000000000000004d0154255b66d44d273b06a1e54281c541aeb61d0000000000000000000000000000000000000000000000000de0b6b3a7640000
```

Result:
![Screenshot 2022-03-31 at 14 36 36](https://user-images.githubusercontent.com/661330/161067966-d0fe9dac-7cce-4663-b4bf-8ffefba6d222.jpg)

**Expected behavior**
MetaMask should allow me to continue to send the transaction.

**Smartphone (please complete the following information):**
 - Device: Google Pixel
 - OS: Android 10
 - App Version: 4.3.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by ryeshrimp** [comment] 2022-04-01 21:53
I too, have this same issue on my website. Same code as author but instead using web3js.

**Comment by lax1n** [comment] 2022-04-03 15:13
Same issue here. Mobile only. Tried both ethers and web3 on fresh projects.

For some people it works to click on "estimated gas fee" amount and then clicking "save". It is then possible to confirm the transfer. So the issue might be related to that.

A second working "workaround" scenario:

1. Give myself allowance (call tokenContract.increaseAllowance(myself, amount)
2. Call tokenContract.transferFrom(myself, contributionWallet, amount)

Success (no "invalid amount" issue).

**Comment by jahvi** [comment] 2022-04-03 17:47
@lax1n Thanks, I couldn't get the first workaround to work for me and I can't use the second one for my dapp use case unfortunately but hopefully it'll help point in the right direction.

**Comment by lax1n** [comment] 2022-04-03 21:09
I actually found a fix for this today.

You need to set `gas` and `gasPrice` for the transaction.

Transfer example:

```
{
  method: 'eth_sendTransaction',
  params: [{
    to: <token-address>,
    from: <wallet-address>,
    data: <transaction-data>,
    gas: <gas>,
    gasPrice: <gas-price>
  }],
}

```

You can get the `gas` from calling `eth_estimateGas`. See examples [here](https://www.quicknode.com/docs/ethereum/eth_estimateGas).

And the `gasPrice` from calling `eth_gasPrice`. Examples [here](https://www.quicknode.com/docs/ethereum/eth_gasPrice)

**Comment by jahvi** [comment] 2022-04-04 11:22
I tried adding `maxFeePerGas`, `maxPriorityFeePerGas`, `gasPrice` and `gasLimit` params to the transfer method call but still got the same issue on mobile.

Ethers.js won't let me override `gas` directly.

**Comment by jahvi** [comment] 2022-04-04 19:49
@BurasovArtem Thanks this workaround works for me as well.

**Comment by Sotatek-SonLai** [comment] 2022-04-06 03:38
> Work for me
> 
> ```
> const gasLimit = await contract.estimateGas.transfer(to, amount);
> const gasPrice = await provider.getGasPrice();
> 
> contract.transfer(to, amount, {
>     gasLimit: gasLimit,
>     gasPrice: gasPrice
> }).then((transaction) => {
>     ...
> })
> ```

I tried. it's work !!! tks....

**Comment by johnson298** [comment] 2022-04-06 03:40
> Work for me
> 
> ```
> const gasLimit = await contract.estimateGas.transfer(to, amount);
> const gasPrice = await provider.getGasPrice();
> 
> contract.transfer(to, amount, {
>     gasLimit: gasLimit,
>     gasPrice: gasPrice
> }).then((transaction) => {
>     ...
> })
> ```

I tried ! it's work. tks thằng em

**Comment by Sarajaybooking11** [comment] 2022-06-27 09:47
> Work for me
> 
> ```
> const gasLimit = await contract.estimateGas.transfer(to, amount);
> const gasPrice = await provider.getGasPrice();
> 
> contract.transfer(to, amount, {
>     gasLimit: gasLimit,
>     gasPrice: gasPrice
> }).then((transaction) => {
>     ...
> })
> ```

my transfer function only takes in to argument, which are the to and amount. how do i add gas to it

**Comment by paddyfink** [comment] 2022-07-01 21:38
I can confirm that setting the gas limit and price also worked for me:
```
const _amount = ethers.utils.parseUnits(amount.toString(), decimals);

  const gasLimit = await tokenContract.estimateGas.transfer(to, _amount);
  const gasPrice = await provider.getGasPrice();

  const tx = await tokenContract.transfer(to, _amount, { gasLimit: gasLimit, gasPrice: gasPrice });
```

**Comment by tommasini** [comment] 2022-12-15 17:36
Since the last solution worked, I will close this issue.
Thanks to all for the support and if you find something we appreciate your reports!

**Closed by tommasini** 2022-12-15 17:36 UTC
Labels: type-bug, stability-team
