### ISSUE TITLE
[Bug] Ledger account disappears

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8713] opened 2024-02-24 00:29 UTC
### Describe the bug

I had a strange series of events that resulted in the paired Ledger account disappearing from my account list.  I had enabled custom nonce and was attempting to test whether I could stack multiple send tx before approving them on the Ledger hardware at the time.  This may not be very reproducible, but I want to report it anyway.

This is most certainly an edge case, but I am concerned that I managed to make the account disappear.

### Expected behavior

Given that I have paired a Ledger account with MMM
And I have enabled custom nonce in settings>advanced
When I approve nonce x+1 in advance of nonce X
And both tx get accepted into a block
Then the Ledger account should not disappear from the account list

### Screenshots/Recordings

I do have a recording at better resolution, but is too large to attach and with the upcoming sunset on recordit.co I am attaching a low res version here:
https://github.com/MetaMask/metamask-mobile/assets/32695229/0fde7c74-3789-4bae-b8f5-16fd40fb4313

### Steps to reproduce

These steps are admitedly a bit silly, but they are the events that occurred that resulted in the account disappearing:

1. Have iOS device set with a 30s screen lock
2. Have FaceID present and enabled
3. Import an SRP with FaceID as the auth method on MMM
4. Change to Sepolia
5. Enable custom nonce in settings>advanced
6. Pair Ledger address
7. Initiate a send tx (Nonce 41)
8. After confirming in MetaMask and while waiting for approval on Ledger
9. Tap outside of the `Confirm Transaction by pressing two buttons on your Ledger` pop-up to close it
10. When returned to the confirmation increment the nonce to +1 of the tx that is still awaiting action on Ledger device (42)
11. Tap back to edit the amount
12. Tap Next
13. Increment the nonce again to +1 on the confirmation page, because it was reset to the same as the tx still awaiting action on Ledger (42)
14. Tap `Confirm with Ledger`
15. When Nonce +1 (42) arrives on Ledger, approve on Ledger
16. Now nonce +1 (42) is submitted, but original nonce (41) was never approved on Ledger
17. Now draft a send tx for the original nonce (41) and tap `Confirm with Ledger`
18. Again tap outside of the `Confirm Transaction by pressing two buttons on your Ledger` pop-up to close it
19. Approve original nonce (41) on Ledger and note that MMM shows tx submitted
20. After original nonce (41) is confirmed note the prompt to enable push notifications
21. Allow the device to screen lock after 30s
22. Immediately unlock
23. Note push notification consent presented over black screen while authenticating with faceID
24. After authenticating, tap `Yes` on push notifications
25. Note that I am returned to wallet view and the Ledger account is no longer selected (~3m 5s in recording)
26.  Tap accounts drop-down and notice that Ledger account is no longer present (~3m 27s)

### Version

[7.17.0 RC1 build 1266](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8e47bc85-2c5b-4f1d-b643-7abb6e878827)

### Build type

None

### Device

iPhone Xs iOS 17.3.1

### Operating system

iOS

### Additional context

Tested with Ledger Nano X hardware v2.0,  firmware 2.2.3, micro controller 2.30, bootloader 1.16
LNX Ethereum version 1.10.3

### Severity

This is super edgy, but the account should not just disappear

**Comment by dawnseeker8** [comment] 2024-02-28 06:45
I am unable to replicate this issue with multiple transaction submit, however, the only time i can make the ledger account disappear is doing following: (very similiar issue with #8693)

1. install the fresh metamask mobile in android. (must be fresh MMM app)
2. restore a account using SRP.
3. when account appear. click the account, and bring up the account drop down list.
4. select `Add account and hardware wallet`  -> `Add hardware wallet`
5. Select `ledger` and then allow all permission required.
6. and then add a `ledger` account in MMM.
7. Now you can close MMM and relaunch metamask. (or wait for screen lock and reactive to force user relogin)
8. After user login again. you will notice `ledger` account disappear in the list.

After deep into detail about the issue and debug the code. i can confirm that this issue has same cause as #5721 (the behaviour is difference however, they all touch the same flow in `vault.js` during login and reset password).

and this account disappear issue only happen at the first time you relogin to MM either from lock screen or from relauch the app. and it wont happen in the second time. that is because the first time user login, the code inside `authentication.ts` will `recreateVaultWithSamePassword` due to `ENCRYPTION_LIB` in asyncStorage have value of `null`.  and after the first time user login, `ENCRYPTION_LIB` will have value set. and the next time user login, system wont run `recreateVaultWithSamePassword`. that is why second time account wont disappear.

anyway, i have tested the fix for [PR](https://github.com/MetaMask/metamask-mobile/pull/8740) for fixing #5721 , and confirm the fix will fix above issue.  i will link this issue to above PR.

**Comment by angelcheung22** [comment] 2024-02-28 09:54
Lets test this one again after the other PR got merged, and see if issue still exist. Onhold for now

**Comment by angelcheung22** [comment] 2024-03-05 09:30
@vivek-consensys can we retry this one too?

**Comment by vivek-consensys** [comment] 2024-03-05 13:11
Unable to reproduce this issue on iPhone 13 using iOS 17.3.1. 
Branch: _fix/5721-ledger-keyring-disappear-issue_

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3F4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72f1cc356428b4ba20bf491d36fb974d8e7b9c60/RPReplay_Final1709644099.MP4)

**Closed by vivek-consensys** 2024-03-05 13:11 UTC
Labels: type-bug, Sev2-normal, Priority - High, Ledger, regression-RC, team-hardware-wallets, release-7.17.0
