### ISSUE TITLE
Navigation within the explore menu

### ISSUE THREAD

**Issue by iamonuwa** [MetaMask/metamask-mobile#1003] opened 2019-08-18 10:23 UTC
Steps to reproduce
1. Go to browser
2. Under the explore tab
3. Choose an option to go to
4. Use the back arrow to navigate back to the explore menu
5. Choose another option
6. Notice the bug there.

**Comment by estebanmino** [comment] 2019-08-19 15:59
Hi @iamonuwa thanks for reporting! Which device and MetaMask version are you using? Thanks!

**Comment by iamonuwa** [comment] 2019-08-19 17:04
Version 0.2.2 (15)

**Comment by ibrahimtaveras00** [comment] 2019-08-22 18:26
Closing this one, it's a duplicate of [https://github.com/MetaMask/metamask-mobile/issues/1002](url)

**Closed by ibrahimtaveras00** 2019-08-22 18:26 UTC
Labels: bug, needs-reproduction
