### ISSUE TITLE
[Bug]: After updating to v7.10.0, deeplink with url no longer works if MM mobile is not already running in the background

### ISSUE THREAD

**Issue by davidliudev** [MetaMask/metamask-mobile#7766] opened 2023-11-12 04:11 UTC
### Describe the bug

When I clicked a deeplink that open MM mobile with a URL, in previous version, it works normally regardless of whether metamask is already running or not. 

However when updated to v7.10.0 in iOS, it will only do the url redirection if MM is already running in the background. If no instance of MM is already running, it will open MM but never redirect to the URL.

This seemed to happen both in Android and iOS as reported by our dev team. 

Combined with https://github.com/MetaMask/metamask-mobile/issues/7724 this essentially makes our application completely unusable on Android, as the workaround of this issue by killing MM every time on Android no longer works.

### Expected behavior

The MM should always redirect to the specified url in deeplink

### Steps to reproduce

1. Kill all instance of Metamask
2. Go to our app app.crossspace.io
3. Click login using MM
4. MM is opened, but with no url redirection

When MM is already running, repeat the above step, MM can redirect to the correct url.

### Version

v7.10.0

### Build type

None

### Device

iPhone 13 Pro Max

### Operating system

iOS

**Comment by sbalcin** [comment] 2023-11-13 10:32
same issue, any comment or workaround on that ?

**Comment by anaamolnar** [comment] 2023-11-13 10:49
Hello, @sbalcin. Thanks for reporting! I will pass this on to the appropriate team for review.

**Comment by christopherferreira9** [comment] 2023-11-16 10:55
Hi @davidliudev, @sbalcin 
Can you please share the deeplink you're trying to open for us to replicate on our side?

**Comment by davidliudev** [comment] 2023-11-17 08:51
Hi @christopherferreira9 please refer to https://github.com/MetaMask/metamask-mobile/issues/7724 's example as posted by one of our engineers.

**Comment by christopherferreira9** [comment] 2023-11-17 09:29
I'm going to close this in favour of https://github.com/MetaMask/metamask-mobile/issues/7724

**Comment by davidliudev** [comment] 2023-11-17 12:13
hihi @christopherferreira9 please reopen as this is another issue separate from 7724

**Comment by davidliudev** [comment] 2023-11-17 12:15
@christopherferreira9 

to add more context,
this issue happened on both ios and android but 7724 only happened on android.
this issue is about opening deeplink with url and it does not work and this issue is only introduced in 7.10.0, while the 7724 issue has already existed before 7.10.0

**Comment by christopherferreira9** [comment] 2023-11-17 14:44
Got it, because you referenced 7724 as steps to reproduce this one I assumed it affected both. Reopening

**Comment by davidliudev** [comment] 2023-11-17 15:30
Oh sorry for the confusion.

I meant the deeplink there.
Let me copy it here as well:

sign message deeplink :
dapp://app.crossspace.io/async/async-sign?sid=52390eb9-858b-44c0-b199-f9e0e92268db

trade deeplink:
dapp://app.crossspace.io/async/async-trade-keys?address=0x655008151f2dbeb52029Cf051bfaFa0ca7f479c4&abi=tradeAbi&function_name=sellShares&args=%5B%220xA30Eb0e0e2B632Df08a4328604be2fBbFe54B35d%22%2C%226551d203264ad02968234b30%22%2C1%5D&value=0&contractNetwork=80001&feedID=6551d203264ad02968234b30&orderInfo=%7B%22ticketPrice%22%3A%2218000000000000000%22%2C%22creatorKeyQuantity%22%3A%22382556488862933290%22%2C%22keyPrice%22%3A%228050466206443634%22%2C%22fee%22%3A%222605046620644362%22%2C%22totalPrice%22%3A%2223445419585799272%22%2C%22tradeType%22%3A%22sell%22%2C%22amount%22%3A1%7D&sid=6538cd4e-cf33-4602-9e04-1d9f60f3910e

**Comment by brianonchain** [comment] 2023-11-17 16:23
My App was also deeplinking users to the MetaMask browser smoothly until something happened; now it only deeplinks into Metamask browser if MetaMask App already running in bg (if metamask app not running in bg, the app opens but stays in the wallet interface, the metamask briswer does not open).

Thank you @davidliudev for figuring out it was the new update, it has been driving me crazy.

**Comment by christopherferreira9** [comment] 2023-11-17 17:54
Next week I will go back version by version to figure out what broke it, I'm sorry for the inconvenience.

**Comment by brianonchain** [comment] 2023-11-17 18:35
Actually, I don't know if it's v7 that broke it, it could be earlier, as
per this comment:
https://github.com/MetaMask/metamask-mobile/issues/4760#issuecomment-1211754291

Maybe @tommasini will have some answers?

**Comment by christopherferreira9** [comment] 2023-11-23 10:24
**Android:**
- 7.8 ✅
- 7.9 ✅
- 7.10 ❌
- 7.11 ❌

Serve a static HTML Dapp:
<a href="dapp://app.crossspace.io/async/async-sign?sid=52390eb9-858b-44c0-b199-f9e0e92268db"> DEEPLINK </a>

**Steps to reproduce:**
1. Close MetaMask
2. Tap the dapp deeplink -> See issue.

**Expected Result:**
A inapp browser tab is opened with the crossspace dapp.

**Actual Result:**
Nothing happens after MM opens

Extra data:
- Biometric was enabled for the tests


Will make sure to check iOS when fixing this.

**Comment by davidliudev** [comment] 2023-12-05 01:52
Is there any updates on this? Users are complaining that they cannot login using MM....

**Comment by davidliudev** [comment] 2023-12-05 01:53
We may have to stop using MM and force to switch to other wallet solutions if this is not working for too long.

**Comment by christopherferreira9** [comment] 2023-12-14 10:44
HI @davidliudev ! We are working on a fix for this and it should be available on the coming releases.

**Comment by kkharji** [comment] 2024-01-14 08:52
Hey @christopherferreira9 any updates on this one. Thanks

**Comment by christopherferreira9** [comment] 2024-01-15 10:19
Hi all! We haven't managed to work on this issue yet. We'll update this issue once we do. We're sorry for the delay

**Closed** 2024-02-01 10:01 UTC
Labels: type-bug, deeplinks, team-sdk, Sev3-low, external-contributor

**Comment by kr-nikunj** [comment] 2024-02-08 06:13
> This PR resolves the issue: #8469

For my device, it is not working
Android: version 13,
Metamask: version 7.14.0

it is still working if I open metamask as a background application
