### ISSUE TITLE
personal_sign not works with WalletConnect v2

### ISSUE THREAD

**Issue by kecson** [MetaMask/metamask-mobile#6701] opened 2023-06-25 09:05 UTC
**Describe the bug**

No authorization is displayed after the personal_sign call

**To Reproduce**

1. MetaMask active `Ethereum Mainnet `
3. open https://react-app.walletconnect.com
4. select a `Polygon Mainnet` that is not equal to your MetaMask active chain
5. MetaMask scan qrcode, approve connect.
6. DApp select Polygon account send  personal_sign request
7. MetaMask is not displayed after the `personal_sign` call
![image](https://github.com/MetaMask/metamask-mobile/assets/10434414/f958243c-2da8-41da-ad18-8e529915b976)

**Smartphone (please complete the following information):**
 - OS: Android and iOS
 - App Version [e.g. v7.0.1]

**Comment by JayChowMu** [comment] 2023-06-26 04:43
Same problem here

**Comment by imaksp** [comment] 2023-06-26 12:05
It works only if network matches, might be related to this:
https://github.com/MetaMask/metamask-mobile/issues/6655#issuecomment-1602118833

**Comment by vkuts** [comment] 2023-06-26 19:27
Experiencing this issue as well when our dapp's chain does not match the wallet's chain. This is breaking our SIWE flow.

**Comment by kecson** [comment] 2023-06-27 02:10
> Experiencing this issue as well when our dapp's chain does not match the wallet's chain. This is breaking our SIWE flow.

When will this be fixed and is there a plan?

**Comment by imaksp** [comment] 2023-06-27 02:32
Actually the issue is selecting other chain than active is not properly tested/supported by metamask, wc v2 might be calling switch chain internally if active chain is different than passed & that call never completes so any other calls like personal sign won't work. This is serious issue but metamask has assigned medium priority to it (programmatic switch & add chain issue), not sure if this will be fixed even in 7.2.
As a workaround dapp needs to ask user to manually switch before connect. Which is definitely not ideal.

**Comment by leye195** [comment] 2023-06-28 06:56
Also experiencing same issue...hope it will be fixed soon

**Comment by christopherferreira9** [comment] 2023-09-06 10:19
Hi! We currently only support one active chain which needs to be synced between dapp and the Wallet.

**Closed by christopherferreira9** 2023-09-06 10:19 UTC
Labels: type-bug, team-sdk, Sev2-normal, WalletConnect
