### ISSUE TITLE
[Bug]: Lost access to wallet

### ISSUE THREAD

**Issue by x68-46** [MetaMask/metamask-mobile#8140] opened 2023-12-17 11:06 UTC
### Describe the bug

I sent an NFT to my wallet on my phone long ago (https://etherscan.io/tx/0x40f02ab36a05baf37a1743068c37a5f8f49198ecf2b10212fd04f1bb218c7c49) and now when I check on it, I can login to my wallet, but the wallet keeps loading, 0 transactions, and I cannot reveal my private key nor backup my phrase to export my account, because it says "Couldn't unlock your account. Please try again." even though I use the correct password, same for login. If I tap on General settings, I also get weird error.

### Expected behavior

To receive my NFT, and be able to export my account, and get access to it.

### Screenshots/Recordings

![Screenshot_20231217_115901_MetaMask](https://github.com/MetaMask/metamask-mobile/assets/68998708/168949a6-11c0-49c7-a2a9-2868085eadcd)
![Screenshot_20231217_113635_MetaMask](https://github.com/MetaMask/metamask-mobile/assets/68998708/04c1a2de-5f3d-4980-a916-52f8decb806f)
![Screenshot_20231217_113643_MetaMask](https://github.com/MetaMask/metamask-mobile/assets/68998708/80b05fca-cdd7-4885-8f08-b3a4bb69c043)
![Screenshot_20231217_113658_MetaMask](https://github.com/MetaMask/metamask-mobile/assets/68998708/efaaa878-0a29-400d-b454-ea597cf7e7b6)

### Steps to reproduce

I just downloaded the app from Google Play, and sent an NFT to it.

### Error messages or log output

```shell
View: Root
TypeError: Cannot read property 'toLowerCase' of undefined
```

### Version

7.10.0

### Build type

None

### Device

Samsung Z Fold 3

### Operating system

Android

### Additional context

My state logs: 
[388278018660631.txt](https://github.com/MetaMask/metamask-mobile/files/13695781/388278018660631.txt)

**Comment by yaerna1984** [comment] 2023-12-28 07:20
I have the same issue. Any updates on this bug?

**Comment by yaerna1984** [comment] 2023-12-28 09:43
Can the dev team please take some time to look at this issue? I think this is very critical. We can't access our funds. We also can't reveal SRP(even tho we have the password to the account) because Metamask doesn't recognize the account. More and more people are having the same issue and looks like there hasn't been a fix even though it's been 3 months.
Here's a few other:
#8196 #7365

I've also seen a couple of them on Metamask's Community Forum. Thank you!

@anaamolnar @gauthierpetetin @kevinghim

**Comment by x68-46** [comment] 2023-12-28 11:14
> I hope I don't come off rude by saying the following at this time of the year, but can the dev team please take some time to look at this critical issue? Due to this bug, we can't access our funds. The app doesn't load, which is one thing, but it doesn't recognize the account so it doesn't let us reveal the SPR though we've got the right password. More and more people are starting to have the same issue. And I've seen a few bug reports going back 3 months on this issue, which is very overwhelming.
> 
> Here's a few other bug reports on this subject: (pretty sure there are more - some people just posted about it on the community forum.) #8196 #7365
> 
> Thank you for your help!
> 
> @anaamolnar @gauthierpetetin @kevinghim @jpcloureiro @sethkfman

I agree, I'm fortunate that I only have a cheap NFT on this account, having any bigger amount I would freak out! I hope the devs fix it and our wallets can be recovered!

**Comment by AlexJupiter** [comment] 2024-01-16 12:43
@vivek-consensys has looked into this but we're having trouble reproducing this.

**Comment by anaamolnar** [comment] 2024-02-01 22:06
Hey @x68-46.  Thank you for your patience while the team has investigated this. This issue should be fixed in 7.15. Please try to update manually from the Play Store and let us know if this continues to occur. Could you let me know if you are still having issues with this error and disclosing your secret recovery phrase after doing so? Thanks!

**Comment by x68-46** [comment] 2024-02-20 10:30
> Hey @x68-46.  Thank you for your patience while the team has investigated this. This issue should be fixed in 7.15. Please try to update manually from the Play Store and let us know if this continues to occur. Could you let me know if you are still having issues with this error and disclosing your secret recovery phrase after doing so? Thanks!

When is 7.15 released in the Play Store? It's still 7.14.

**Comment by Twanm123** [comment] 2024-03-21 12:49
Has this been fixed? Im having the exact same issue. On my iphone, version 7.18 which is the latest version. Im hoping an update will fix it! ....

**Comment by sigspam** [comment] 2024-03-25 08:58
This issue still persists in 7.18.0 (1281). I am having a similar problem with my accounts all not loading and unable to retrieve SRP with it stating "Couldn't unlock your account. Please try again". 3 months later and still no fix apparently.

**Comment by gauthierpetetin** [comment] 2024-03-26 08:58
Duplicate of this issue: https://github.com/MetaMask/metamask-mobile/issues/7365

**Comment by x68-46** [comment] 2024-03-27 19:01
> Hey @x68-46. Thank you for your patience while the team has investigated this. This issue should be fixed in 7.15. Please try to update manually from the Play Store and let us know if this continues to occur. Could you let me know if you are still having issues with this error and disclosing your secret recovery phrase after doing so? Thanks!

still not working as of 7.18

**Comment by AlexJupiter** [comment] 2024-04-22 12:36
@gauthierpetetin could we perhaps close this issue to direct all conversations on this to the duplicate with more activity? https://github.com/MetaMask/metamask-mobile/issues/7365

**Comment by gauthierpetetin** [comment] 2024-04-22 13:18
Sure! Closing as duplicate: https://github.com/MetaMask/metamask-mobile/issues/7365

**Closed by gauthierpetetin** 2024-04-22 13:18 UTC
Labels: type-bug, ready-for-dev, external-contributor
