### ISSUE TITLE
> weve got a few reports from users that metamask mobile is not accepting cookies set in the browser from github login flow, preventing users from logging in on gitcoin

### ISSUE THREAD

**Issue by csplawn918794** [MetaMask/metamask-mobile#1286] opened 2020-01-21 23:27 UTC
> weve got a few reports from users that metamask mobile is not accepting cookies set in the browser from github login flow, preventing users from logging in on gitcoin
> 
> i got this from a user.. looking for more information to validate exactly whats going on.
> 
> ![Screenshot_20200110-215041_MetaMask (1)](https://user-images.githubusercontent.com/513929/72230667-3206b400-3574-11ea-85ac-1e0fa59a4413.jpg)

_Originally posted by @csplawn918794 in https://github.com/MetaMask/metamask-mobile/issues/1273#issuecomment-576933442_

**Comment by brunobar79** [comment] 2020-01-21 23:39
duplicate of #1273

**Closed by brunobar79** 2020-01-21 23:39 UTC
