### ISSUE TITLE
[Bug]: MM V7.7.0 mobile will crash break when switching network

### ISSUE THREAD

**Issue by LouisLiu00** [MetaMask/metamask-mobile#7285] opened 2023-09-21 11:10 UTC
### Describe the bug

【IOS 16.6.1 】MM V7.7.0 mobile will crash break when switching network

### Expected behavior

Switch network

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/63631719/6cb701f4-831f-49ce-ba1a-ee47b7842200

### Steps to reproduce

1. Open MM
2. Swich network
3. App Break

### Error messages or log output

```shell
No
```

### Version

7.7.0

### Build type

None

### Device

IOS 16.6.1

### Operating system

iOS

**Comment by cortisiko** [comment] 2023-09-27 06:38
Hey @LouisLiu00 can you add more details on how you are able to reproduce? Did you add a custom network via a dapp/manually adding a network? Did you submit any transactions prior? I see you have polygon Mumbai and polygon mainnet added to your network list, did you add both of them via a dapp? 


Did you submit any transactions before switching networks? The more information you give us relating to this bug the easier it would be to pin point!

**Comment by LouisLiu00** [comment] 2023-09-27 07:32
@cortisiko Hi,

Just like the video, it always breaks whenever I switch to `Mainnet` from any other network.
Polygon and Mumbai are networks added via dapp, and MM `Add Network` is triggered when I `Switch Network` via dapp.
There are no transactions during the switch network, I only use the connect wallet and sign for the dapp.

Also I noticed that when switching networks the balance did not update at the same time. There is **Polygon 0.96855 MATIC (Mumbai 45.08491 MATIC)** and when I switch to Mainnet it shows 0.96855 ETH (Mumbai 45.08491 ETH). Is this an anomaly of the MM network connection?

Below is the complete video demo:


https://github.com/MetaMask/metamask-mobile/assets/63631719/04287887-0315-441d-881e-031727bc68e0

**Comment by gauthierpetetin** [comment] 2023-11-01 16:16
Hi @LouisLiu00 , do you still have the issue when you upgrade to the latest version of Mobile app (currently 7.9.0) ?

**Comment by siosio34** [comment] 2023-11-02 01:43
This error has been occurring to me since version 7.4.0.

https://github.com/MetaMask/metamask-mobile/issues/7206
https://github.com/MetaMask/metamask-mobile/issues/7023

**Comment by gauthierpetetin** [comment] 2023-11-03 16:18
This [PR](https://github.com/MetaMask/metamask-mobile/pull/7667) may fix the issue in 7.10.0, please let us know if the issue still persists once 7.10.0 is rolled out.

**Comment by LouisLiu00** [comment] 2023-11-06 09:48
@gauthierpetetin Yes, the bug is still working in version 7.9.1 .

**Comment by gauthierpetetin** [comment] 2024-02-09 16:27
Closing this issue as we're not able to reproduce it and haven't received any other report.

**Closed by gauthierpetetin** 2024-02-09 16:27 UTC
Labels: type-bug, Sev1-high, team-mobile-platform, regression-prod-7.7.0
