### ISSUE TITLE
Mobile App’s Misinterpreting My Deposit Requests

### ISSUE THREAD

**Issue by cawcawcondor** [MetaMask/metamask-mobile#1283] opened 2020-01-17 17:22 UTC
I’m trying to deposit OXT through my browser into my Orchid account (VPN software thing), and when I go to deposit, say, 2.00 OXT, it tries to perform a transaction of 2E18 OXT, which is VERY incorrect. It works totally fine on the Chrome extension, but does not work properly in the mobile app.

[This video](https://imgur.com/a/xutgiCT) shows the issue I’m talking about.

**Comment by brunobar79** [comment] 2020-01-21 23:46
Duplicate of #1243

Will be fixed by #1251

**Closed by brunobar79** 2020-01-21 23:46 UTC
