### ISSUE TITLE
Token payment request bugs

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1566] opened 2020-05-12 23:25 UTC
**Describe the bug**
Token payment request not consistent with ETH payment requests

**Screenshots**

1. Balance undefined on when Edit request. 

![Image from iOS (68)](https://user-images.githubusercontent.com/44038140/81754869-0df8a800-946c-11ea-943a-ea6bb5cbe353.png)
![Image from iOS (67)](https://user-images.githubusercontent.com/44038140/81754882-12bd5c00-946c-11ea-985b-938ffd431af2.png)

2. Different behavior on account switcher than in ETH payment request
![Image from iOS (70)](https://user-images.githubusercontent.com/44038140/81755143-d5a59980-946c-11ea-84c1-8c5a15959732.png)

![Image from iOS (63)](https://user-images.githubusercontent.com/44038140/81755174-e9e99680-946c-11ea-9330-c34c567ff333.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Scan token payment request
2. See the inconsistent token screens

**For getting to the undefined state:**
1. create a request for an ERC20 token 
2. go to an account that doesn't have that token 
3. scan the QR code, or open the deep link 
4. once on confirm view, tap on the edit button

**Expected behavior**
Similar to ETH request - shows balance, checks balance for account switching 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone8]
- Version: 0.2.16

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by danjm** [comment] 2020-05-13 15:03
@omnat Are there any more specific instructions for reproducing the first issue? I am unable to recreate: https://streamable.com/m2jn4j

**Comment by danjm** [comment] 2020-05-13 15:09
@omnat For the second issue, I guess the desire is for the account list to show token balances instead of ETH and prevent switching if the token balances are too low?

This requires an update to how we handle token balance data, with non-trivial changes in gaba and the extension. I'd recommend we push that to the next release.

**Comment by ibrahimtaveras00** [comment] 2020-05-13 15:47
Interesting, I too cannot reproduce issue 1 on OnePlus 3T device; seen here = http://recordit.co/FufU8yMjju

**Comment by omnat** [comment] 2020-05-13 17:52
Not critical for a release bug.  
![RecordIt-1589391866](https://user-images.githubusercontent.com/44038140/81846943-bf98e700-9507-11ea-8127-022fa64a3f37.gif)

**Comment by ibrahimtaveras00** [comment] 2020-05-13 23:39
I will remove release bug label as issue 1 has been addressed 

Issue 2 can be worked on post release 👍

**Comment by andrepimenta** [comment] 2021-08-17 17:07
Should be fixed.

**Closed by andrepimenta** 2021-08-17 17:07 UTC
Labels: bug
