### ISSUE TITLE
[Bug] Connect more accounts displays all the balances cut

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6858] opened 2023-07-21 10:13 UTC
**Describe the bug**
Whenever we are navigating on a dapp, and we click Connect More Accounts, we can see how all the balances are cut off the screen.

**Screenshots**

![image](https://github.com/MetaMask/metamask-mobile/assets/54408225/1e84c35f-f84d-45d1-bc9f-fad03af4bf10)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the test dapp
2. Click on the Accounts menu
3. Click on Connect More Accounts
4. See all balances cut

**Expected behavior**
Balances should be displayed correctly

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: production `7.3.0`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by chrisleewilcox** [comment] 2023-07-25 17:57
Duplicate of this https://app.zenhub.com/workspaces/mobile-release-regression-6249e5242464b70013315a98/issues/gh/metamask/mobile-planning/1146

Closing.

**Closed by chrisleewilcox** 2023-07-25 17:57 UTC
Labels: type-bug, Sev2-normal, team-mobile-ux
